### ISSUE TITLE
:feather: Strange schema with sqlite/docker :whale: 

### ISSUE THREAD

**Issue by adriens** [schemacrawler/SchemaCrawler#1040]
### Description

While generating a schema on a sqlite database, I got the following strange things : 

- VARCHAR2(X)(X)
- Weird schema on FK on `SHARKS.ID` 

![image](https://user-images.githubusercontent.com/5235127/222932984-4c3ed08d-2bec-4b02-82ee-8677fc443bb4.png)

### How to Reproduce

I used this command : 

```shell
docker run \
--mount type=bind,source="$(pwd)",target=/home/schcrwlr \
--rm -it \
schemacrawler/schemacrawler \
/opt/schemacrawler/bin/schemacrawler.sh \
--server=sqlite \
--database=shark-attacks-ncl.sqlite \
--info-level=standard \
--command=schema \
--output-file=shark-attacks-ncl.png
```

I used the following image : 

![image](https://user-images.githubusercontent.com/5235127/222933084-e68aa6b3-2556-4c8b-b81d-902f68b13cd2.png)

Below the database schema:
<pre>SQLite version 3.41.0 2023-02-21 18:09:37
Enter &quot;.help&quot; for usage hints.
sqlite&gt; .schema
CREATE TABLE CONSERVATION_STATUS (
    id VARCHAR(2) PRIMARY KEY,
    id_long VARCHAR(25),
    cat VARCHAR(20),
    desc VARCHAR(100)
);
CREATE TABLE LUNAR_PHASIS(
    id VARCHAR2(15) PRIMARY KEY,
    phase VARCHAR2(15),
    www_phase VARCHAR2(50),
    illuminated_portion_northern VARCHAR2(60),
    illuminated_portion_south  VARCHAR2(60),
    visibility VARCHAR2(60),
    average_moonrise_time  VARCHAR2(5),
    culmination  VARCHAR2(5),
    average_moonset_time  VARCHAR2(5),
    www_illustration_north_png  VARCHAR2(100),
    www_illustration_south_png VARCHAR2(100),
    www_photo_jpg VARCHAR2(100)
);
CREATE TABLE SHARKS(
    id VARCHAR(20) PRIMARY KEY,
    description VARCHAR(23),
    scientific_name VARCHAR(26),
    conservation_status VARCHAR(2),
    FOREIGN KEY (conservation_status) REFERENCES CONSERVATION_STATUS(id)
);
CREATE TABLE SHARK_ATTACKS_NCL (
    case_number VARCHAR(12) PRIMARY KEY,
    date TEXT,
    moon_phase_rate INTEGER,
    moon_phase VARCHAR(15),
    year_month VARCHAR(7),
    year INTEGER,
    month INTEGER,
    dow VARCHAR(9),
    season VARCHAR(6),
    type VARCHAR(10),
    country VARCHAR(13),
    comune_nom VARCHAR(11),
    coast VARCHAR(4),
    location VARCHAR(30),
    details_plage VARCHAR(50),
    code_cog INTEGER,
    province VARCHAR(4),
    geo_point VARCHAR(30),
    activity VARCHAR(13),
    name VARCHAR(25),
    sex VARCHAR(1),
    age INTEGER,
    injury VARCHAR(15),
    is_fatal VARCHAR(1),
    time VARCHAR(5),
    day_part VARCHAR(3),
    species VARCHAR(11),
    species_1 VARCHAR(11),
    species_2 VARCHAR(11),
    skark_size_centimeters INTEGER,
    source VARCHAR(100),
    www_sharkattack_file VARCHAR(100),
    www_nc1 VARCHAR(100),
    sharkattack_id VARCHAR(12),
    FOREIGN KEY (moon_phase) REFERENCES LUNAR_PHASIS(id),
    FOREIGN KEY (species_1) REFERENCES SHARKS(ID),
    FOREIGN KEY (species_2) REFERENCES SHARKS(ID)
);</pre>

### SchemaCrawler Version

schemacrawler/schemacrawler:latest (3e1d941fc4c0)

`16.19.7` : 

![image](https://user-images.githubusercontent.com/5235127/222933276-3ca18ab5-bc9d-42fb-91ab-c431dd2443ed.png)

### Java Version

N/A

### Operating System and Version

Linux

### Relational Database System and Version

sqlite:3.41.0

### JDBC Driver and Version

embedded

**Comment by sualeh** [comment]
@adriens - the SQLite JDBC driver is case-sensitive, and SchemaCrawler honors that. Please change your DDML to reference `SHARKS(id)` in the foreign keys, like this:

```sql
--- ...
    FOREIGN KEY (species_1) REFERENCES SHARKS(id),
    FOREIGN KEY (species_2) REFERENCES SHARKS(id)
-- ...
```

**Comment by sualeh** [comment]
The `VARCHAR2(X)(X)` issue is another quirk of the SQLite JDBC driver. It reports `VARCHAR2` with the size in parentheses. This can be fixed in the JDBC driver code, and when I get a chance, I will create a PR there.

**Comment by sualeh** [comment]
> While generating a schema on a sqlite database, I got the following strange things :

> VARCHAR2(X)(X)

@adriens - SchemaCrawler 16.19.9 ships with the latest version of the SQLite JDBC driver which fixes this issue.
