### ISSUE TITLE
Markdown output

### ISSUE THREAD

**Issue by dannief** [schemacrawler/SchemaCrawler#1091]
### Feature Request

I would like markdown support for database dictionary output. This would allow the dictionary to be better integrated into doc site generators such as docusaurus and mkdocs that support markdown.

### Possible Alternatives

I've tried converting the HTML produced to markdown, with some success. Usually the output would require some tweaking. It would be great to have first-class support for markdown (with links) in SchemaCrawler

### Additional Context

Mkdocs for example does have some support for linking to static non-markdown files but it would not be added to the navigation of the site

**Comment by sualeh** [comment]
@dannief If I came up with first-class support for Markdown in SchemaCrawler, I would not be able to make everybody happy. Instead, SchemaCrawler allows you to write some Python, JavaScript or Ruby scripts to generate any output that you would like, including Markdown.

Take a look at [Automatically Document Your Database in Markdown](https://dev.to/sualeh/automatically-document-your-database-in-markdown-elf) to get started with generating Markdown documentation for your database.

Here are some other formats that you can generate using the same technique:
- [[Create Nice-looking Schema Diagrams in PlantUML](https://dev.to/sualeh/create-nice-looking-schema-diagrams-in-plantuml-1jo5)](https://dev.to/sualeh/generate-good-looking-plantuml-diagrams-for-your-database-3g19)
- [Generate dbdiagram.io Diagrams for Your Database](https://dev.to/sualeh/how-to-generate-dbdiagram-io-diagrams-for-your-database-431l)
