### ISSUE TITLE
database and schemas option doesn't seem to limit crawler access

### ISSUE THREAD

**Issue by OsoRojo** [schemacrawler/SchemaCrawler#1109]
### Description

I'm having the exact same issue as referenced in issue #231 only the command in question is using the right parameter names I believe.  I get the exact same error message (after starting the shell with WARN logging enabled):

> The server principal "aUser" is not able to access the database "ADatabase" under the current security context.

I'm using the shell from within a Docker container in this case though, and not directly invoking from the command line.

`connect --server=sqlserver --user=aUser --password=aPassword --host=host.mysite.org --database=ADatabase --schemas=ADatabase.dbo`

(user, password, database name and hostname have been obfuscated to protect the guilty)

I've even gone so far as to try and use the config exclusions to forcibly exclude `ADatabase` from the scan, but it still gives the exact same error message.

I am admittedly a SQL Server rookie, and greatly wish I was running against Postgres which I got to work in about 10 minutes flat.  I tried with another user that arguably DOES have access to the 'bad database', but in that case the account is configured oddly and I need to specify the domain and can't seem to figure out the magic incantation to make that work.  

Any help or tips would be appreciated.  

Environment:
  SchemaCrawler 16.19.9
  Linux 5.15.49-linuxkit
  Eclipse Adoptium OpenJDK 64-Bit Server VM 11.0.18+10

### SchemaCrawler Version

16.19.9

### Java Version

openjdk 11.0.18 2023-01-17

### Operating System and Version

Linux 5.15.49-linuxkit

### Relational Database System and Version

SQL Server 2014

### JDBC Driver and Version

whatever is packaged in that Docker image

**Comment by sualeh** [comment]
@OsoRojo Do you have any updates?

**Comment by sualeh** [comment]
Closing due to no updates
