### ISSUE TITLE
ORA-00904:"USERS". "ORACLE_MAINTAINED": invalid identifier

### ISSUE THREAD

**Issue by chenjunchang** [schemacrawler/SchemaCrawler#1128]
### Description

ORA-00904:"USERS". "ORACLE_MAINTAINED": invalid identifier

code:

final LoadOptionsBuilder loadOptionsBuilder =
                LoadOptionsBuilder.builder()
                        // Set what details are required in the schema - this affects the
                        // time taken to crawl the schema
                        .withSchemaInfoLevel(SchemaInfoLevelBuilder.builder().withInfoLevel(InfoLevel.minimum)
                                .setRetrieveDatabaseInfo(true)
                                .setRetrieveTables(true)
                                .setRetrieveAdditionalTableAttributes(true)
                                .setRetrieveTableColumns(true)
                                .setRetrievePrimaryKeys(true)
                                .setRetrieveColumnDataTypes(true)
                                .setRetrieveAdditionalColumnAttributes(true)
                                .setRetrieveAdditionalColumnMetadata(true)
                                .toOptions());
        final SchemaCrawlerOptions options =
                SchemaCrawlerOptionsBuilder.newSchemaCrawlerOptions()
                        .withLimitOptions(limitOptionsBuilder.toOptions())
                        .withLoadOptions(loadOptionsBuilder.toOptions());

### SchemaCrawler Version

16.19.9

### Java Version

8

### Operating System and Version

linux

### Relational Database System and Version

unknown

### JDBC Driver and Version

ojdbc7:12.1.0.2

**Comment by sualeh** [comment]
@chenjunchang Please provide the complete logs. Set `Level.ALL` in your code, and capture the logs.

**Comment by chenjunchang** [comment]
Thank you for your response. Due to encountering an error in the production environment, I was unable to obtain the logs. Additionally, the version of the Oracle database involved is relatively low. I tried version 19c without any issues, so it's possible that the field in question does not exist in the lower version of the database.

**Comment by sualeh** [comment]
@chenjunchang I am closing this issue, since it is not a SchemaCrawler issue, and is related to your environment.
