### ISSUE TITLE
java.sgl SQLException:ORA-16000: database or pluggable database open for read-only access

### ISSUE THREAD

**Issue by chenjunchang** [schemacrawler/SchemaCrawler#1129]
### Description

java.sgl SQLException:ORA-16000:
database or pluggable database open for read-only access
ORA-06512: at "SYS.DBMS_LOCK", line 378
ORA-06512: at "SYS.DBMS_LOCK", line 411
ORA-06512: at "SYS KUPUSUTILITIES INT". line 1738
ORA-06512: at "SYS. DBMS_ METADATA", line 1216
ORA-06512: at "SYS. DBMS_METADATA", line 8546
ORA-06512: at line 2

code:

final LoadOptionsBuilder loadOptionsBuilder =
                LoadOptionsBuilder.builder()
                        // Set what details are required in the schema - this affects the
                        // time taken to crawl the schema
                        .withSchemaInfoLevel(SchemaInfoLevelBuilder.builder().withInfoLevel(InfoLevel.minimum)
                                .setRetrieveDatabaseInfo(true)
                                .setRetrieveTables(true)
                                .setRetrieveAdditionalTableAttributes(true)
                                .setRetrieveTableColumns(true)
                                .setRetrievePrimaryKeys(true)
                                .setRetrieveColumnDataTypes(true)
                                .setRetrieveAdditionalColumnAttributes(true)
                                .setRetrieveAdditionalColumnMetadata(true)
                                .toOptions());
        final SchemaCrawlerOptions options =
                SchemaCrawlerOptionsBuilder.newSchemaCrawlerOptions()
                        .withLimitOptions(limitOptionsBuilder.toOptions())
                        .withLoadOptions(loadOptionsBuilder.toOptions());

### SchemaCrawler Version

16.19.9

### Java Version

8

### Operating System and Version

linux

### Relational Database System and Version

19c

### JDBC Driver and Version

ojdbc7:12.1.0.2

**Comment by sualeh** [comment]
@chenjunchang Please provide the complete logs. Set Level.ALL in your code, and capture the logs.

**Comment by chenjunchang** [comment]
Thank you for your reply. Due to encountering an error in the production environment, I was unable to obtain the logs. Additionally, the Oracle database involved is an ADG database, for which I only have read access.

**Comment by sualeh** [comment]
@chenjunchang I am closing this issue, since this is not a SchemaCrawler issue. It is related to your environment.
