### ISSUE TITLE
Multiple different quote characters applied with schema inclusion rules

### ISSUE THREAD

**Issue by csemrau** [schemacrawler/SchemaCrawler#1130]
### Description

We read the structure of a DB schema, and want to ignore all other schemas. We are using a schema inclusion rule which quotes the schema name with `Identifiers.STANDARD` to match the quoting that is applied internally. Since the update to schema crawler 16.19.9 (from 16.19.2), this fails at least in MariaDB when the schema name is quoted. We haven't tested our other supported DBs yet. The schema is excluded because the schema name is now quoted with back ticks.

I investigated and debugged a bit and learned that the schema is checked twice and the inclusion rule must succeed both checks, but different quote strings are used in both places.

    Including <"base-int"> since it matches /"base-int"/
    Excluding <`base-int`> since it does not match /"base-int"/

Is this mixture of identifier quote strings intentional, or should it be considered a bug?

I already updated our inclusion rule to accept both characters to keep us going.

### How to Reproduce

We are running the schema crawler like this:

	final SchemaCrawlerOptions options = SchemaCrawlerOptionsBuilder.newSchemaCrawlerOptions()
			.withLimitOptions(LimitOptionsBuilder.builder()
					.includeSchemas(new RegularExpressionInclusionRule(Identifiers.STANDARD.quoteName(catalog))).toOptions())
			.withLoadOptions(LoadOptionsBuilder.builder()
					.withSchemaInfoLevel(SchemaInfoLevelBuilder.standard()).toOptions());
	final DatabaseConnectionSource dataSource = DatabaseConnectionSources.fromDataSource(getDataSource());
	final Catalog database = SchemaCrawlerUtility.getCatalog(dataSource, options);

Based on a hint in issue #1053, I specified the `identifiers` in the `SchemaRetrievalOptions`. Setting the `identifiers` was more tricky than I expected, because you cannot set the `identifiers` directly on the options builder. I found a workaround by going through `identifierQuoteString` and a `fromConnection` call. For this test, I replaced the last line above with this code:

	final SchemaRetrievalOptionsBuilder schemaRetrievalOptionsBuilder = SchemaRetrievalOptionsBuilder
			.builder(SchemaCrawlerUtility.matchSchemaRetrievalOptions(dataSource))
			.withIdentifierQuoteString("#")
			.fromConnnection(jdbcConnection);
	final Catalog database = SchemaCrawlerUtility.getCatalog(dataSource, schemaRetrievalOptionsBuilder.toOptions(), options, new Config());

Looking at the log output below, it seems that the first check is still using `Identifiers.STANDARD`, i.e. double quotes, and only the second check uses the specified identifier quote string.

### Relevant log output

```shell
-- generated by: SchemaCrawler 16.19.9
-- generated on: 2023-05-17T18:58:20.2083619
-- database: MariaDB 10.9.2-MariaDB-1:10.9.2+maria~ubu2204
-- driver: MariaDB Connector/J 3.1.4
-- operating system: Windows 10 10.0
-- JVM system: Azul Systems, Inc. OpenJDK 64-Bit Server VM 17.0.5+8-LTS

For the original code, this is the debug log out relating to the inclusion of schemas:

2023-05-17 20:51:42,544 DEBUG [pool-7-thread-5] s.inclusionrule.RegularExpressionRule: Excluding <information_schema> since it does not match /"base-int"/
2023-05-17 20:51:42,545 DEBUG [pool-7-thread-5] s.inclusionrule.RegularExpressionRule: Including <"base-int"> since it matches /"base-int"/
2023-05-17 20:51:42,548 DEBUG [pool-7-thread-6] s.inclusionrule.RegularExpressionRule: Excluding <`base-int`> since it does not match /"base-int"/

For the updated code, this is the output:

2023-05-17 20:58:20,228 DEBUG [pool-7-thread-5] s.inclusionrule.RegularExpressionRule: Excluding <information_schema> since it does not match /"base-int"/
2023-05-17 20:58:20,229 DEBUG [pool-7-thread-5] s.inclusionrule.RegularExpressionRule: Including <"base-int"> since it matches /"base-int"/
2023-05-17 20:58:20,234 DEBUG [pool-7-thread-6] s.inclusionrule.RegularExpressionRule: Excluding <#base-int#> since it does not match /"base-int"/
```

### SchemaCrawler Version

16.19.9

### Java Version

17

### Operating System and Version

Windows 10

### Relational Database System and Version

MariaDB 10.9.2

### JDBC Driver and Version

MariaDB Connector/J 3.1.4

**Comment by sualeh** [comment]
@csemrau Thanks for debugging and providing a detailed issue report. Please see if SchemaCrawler v16.19.10 has the fix for your issue. You can use the regular MariaDB quotes, "\`" (back-tick). Please see [SpecialNamesTest.java](https://github.com/schemacrawler/SchemaCrawler/blob/main/schemacrawler-dbtest/src/test/java/schemacrawler/integration/test/SpecialNamesTest.java#L106-L114) as an example.
