### ISSUE TITLE
Extracting multiple schema

### ISSUE THREAD

**Issue by NarayanAher** [schemacrawler/SchemaCrawler#1157]
### Description

Command

```bash
schemacrawler \
connect --server=sqlserver --database=SchemaCrawler  --schemas=SchemaCrawler.*\.p.*|.*\.s.* --user=LoaderRC20 --password=MSSwamiji#2206 --info-level=maximum --command=details --log-level=SEVERE  --output-format=text --output-file=/Users/narayanaher/SCHEMA101.txt --no-info=true  --load-row-counts --title="Attempting Multiple Schemas"
```

doesnot return schema starting with P & S

### SchemaCrawler Version

16.19.10

### Java Version

1.8.0.341

### Operating System and Version

MacOS

### Relational Database System and Version

N. A.

### JDBC Driver and Version

N.A.

**Comment by NarayanAher** [comment]
@sualeh  attached three files, one shows the help referred from schemacrawler -h command and other two are output of the command with log-level = config and log-level = all.

SQL Database is MSSql 2019

[BikeStores Sample Database - create objects.txt](https://github.com/schemacrawler/SchemaCrawler/files/11669113/BikeStores.Sample.Database.-.create.objects.txt)

[SchemaCrawler_Input.txt](https://github.com/schemacrawler/SchemaCrawler/files/11668885/SchemaCrawler_Input.txt)
[SchemaCrawler_Output02.txt](https://github.com/schemacrawler/SchemaCrawler/files/11668886/SchemaCrawler_Output02.txt)
[SchemaCrawler_Output01.txt](https://github.com/schemacrawler/SchemaCrawler/files/11668887/SchemaCrawler_Output01.txt)

**Comment by sualeh** [comment]
@NarayanAher - please try running this command:

```bash
schemacrawler \
--server sqlserver \
--host sqlserver \
--database SchemaCrawler \
--schemas "SchemaCrawler.*\.(pr|sa).*" \
--user SA \
--password Schem#Crawl3r \
--info-level minimum \
-c list
```

**Comment by NarayanAher** [comment]
@sualeh Thanks a ton, the solution worked as expected.  Now working on getting Database objects (triggers, procedures, packages & functions) thru schemacrawler.  If there is any reference document, please share.  thanks
