### ISSUE TITLE
Name Generation Functionality Error (cleanname)

### ISSUE THREAD

**Issue by Lee-WonJun** [schemacrawler/SchemaCrawler#1179]
### Description

[code](https://github.com/schemacrawler/SchemaCrawler/blob/f2c57df0f47072bbcb37ebea07e0f3b9d959d5e4/schemacrawler-scripting/src/main/resources/scripts/mermaid.py#L6)
```python
# Mermaid only allows alphanumeric identifiers
def cleanname(name):
    namepattern = r'[^0-9a-zA-Z]'
    cleanedname = re.sub(namepattern, '', name)
    if not cleanedname:
        cleanedname = "UNKNOWN"
    return cleanedname
```
`cleanname` function is filter via regex in `mermaid.py`

But as I see, Mermaid supports dashes (-) and underscores (_) as well, and specifically, underscores are commonly used in DB schema.

![image](https://github.com/schemacrawler/SchemaCrawler/assets/10369528/882531ef-31c3-47ca-8e24-a79daafa8817)
[link](https://mermaid.js.org/syntax/classDiagram.html#define-a-class)

so IMHO, we can modify regex in `mermaid.py`

### SchemaCrawler Version

SchemaCrawler 16.19.11

### Java Version

Eclipse Adoptium OpenJDK 64-Bit Server VM 17.0.7+7

### Operating System and Version

 Windows 11 10.0

### Relational Database System and Version

Postgres

### JDBC Driver and Version

-

**Comment by Lee-WonJun** [comment]
I have noticed that this repository does not accept PRs. Therefore, I would like to share [example commit](https://github.com/Lee-WonJun/SchemaCrawler/commit/b950486d4bf64f9500540beea4b8796fa8965e28)

**Comment by sualeh** [comment]
@Lee-WonJun Thanks for the detailed issue description, and example commit. This will be released in the next release. Is this blocking you, or can you wait for the next release?

**Comment by Lee-WonJun** [comment]
that's find, i already printed my own mermaid code by my commit script
