### ISSUE TITLE
:robot:  ChatGPT plugin > Make it possible to choose AI engine (gtp4, gpt3-turbo) :brain: 

### ISSUE THREAD

**Issue by adriens** [schemacrawler/SchemaCrawler#1200]
### Feature Request

Currently we cannot choose the underlying used engine.
Depending on contexts (and the money he may want to spend or not), it could dbe interesting for end-user to choose bewteen gpt-3.5, gpt-4, or other versions into the command-line options.

### Possible Alternatives

N/A

### Additional Context

In some contexts, we may like to get a smater analysis on shemacrawler-GPT, also playing wit info-levels, ofr example : 

1. First fast and cheep discover on gtp-3.5 and normal info level
2. Finally switch to gpt-4 and full info level

### :pray: Other

Wuld it possible to get : 

- 1 AI milestone i in which we could follow AI implementation status
- Maybe a dedciated discussion track ?

**Comment by sualeh** [comment]
This is already available with the `--model` command-line switch.

**Comment by adriens** [comment]
> This is already available with the `--model` command-line switch.

Would you complete it in the ["Use ChatGPT to Explore Your Database Schema"  DEV.to](https://dev.to/sualeh/use-chatgpt-to-explore-your-database-schema-e73) post ?

Also, did you make a little benchmark on outputs ?

**Comment by adriens** [comment]
(I mean, is the money expand worth it ?)

**Comment by sualeh** [comment]
I will test it, and add it to the post also.

**Comment by sualeh** [comment]
@adriens - I do not have access to the gpt-4 model yet. I will test when I have access. If you have access, you can use `--model gpt-4`.

**Comment by adriens** [comment]
@sualeh , I thought gpt-4 was available since this week-end, see ["How can I access GPT-4?"](https://help.openai.com/en/articles/7102672-how-can-i-access-gpt-4)

Probably a question of days :thinking: 
![image](https://github.com/schemacrawler/SchemaCrawler/assets/5235127/728e6d7b-0783-472f-9064-fdbda04aee89)
