### ISSUE TITLE
:money_with_wings: Count token before to run a command :telescope: 

### ISSUE THREAD

**Issue by adriens** [schemacrawler/SchemaCrawler#1202]
### Feature Request

Before to send a question, or before to launch a chat, switch to a mode where, instead of giving the answer, we may get the prdictive cost of our query (eg. the tokens)

This a done in Python in many cases for PROMPT tuning, still here are some elements : 

- [What are tokens and how to count them?](https://help.openai.com/en/articles/4936856-what-are-tokens-and-how-to-count-them)
- [How to count tokens with tiktoken](https://github.com/openai/openai-cookbook/blob/main/examples/How_to_count_tokens_with_tiktoken.ipynb)
- [What is the OpenAI algorithm to calculate tokens?](https://community.openai.com/t/what-is-the-openai-algorithm-to-calculate-tokens/58237)
- [Tracking token usage](https://python.langchain.com/docs/modules/model_io/models/llms/how_to/token_usage_tracking) (langchain `get_openai_callback`)

**Comment by sualeh** [comment]
@adriens I am not going to work on this. I don't think it will add value to SchemaCrawler users.

**Comment by adriens** [comment]
So would it possible to get the amount of token used as log output ?

**Comment by sualeh** [comment]
Yes, that is already in the log output, if you use `--log-level=ALL`

**Comment by adriens** [comment]
:ok_hand: Perfect :pray:
