### ISSUE TITLE
Choco package upgrade?

### ISSUE THREAD

**Issue by crowz4k** [schemacrawler/SchemaCrawler#1223]
### Description

Can we upgrade choco package?

https://community.chocolatey.org/packages/schemacrawler#releasenotes

### SchemaCrawler Version

16.19.6

### Java Version

latest

### Operating System and Version

Windows

### Relational Database System and Version

SQL 

### JDBC Driver and Version

latest

**Comment by adriens** [comment]
it usually is part of CI pipeline 💭

**Comment by sualeh** [comment]
> it usually is part of CI pipeline 💭

It was turned off. I just turned it back on.

**Comment by crowz4k** [comment]
Thank you!

**Comment by sualeh** [comment]
@crowz4k - please check https://community.chocolatey.org/packages/schemacrawler-java-binary/16.20.4 for the release.

**Comment by crowz4k** [comment]
Yep thank you!
