### ISSUE TITLE
No tables returned from `Catalog.getTables()` on Postgres 11 & 15

### ISSUE THREAD

**Issue by Mahoney** [schemacrawler/SchemaCrawler#1243]
### Description

Running schema crawler against postgres 15 with default options, it never finds any tables because [it always exits `TableRetriever.createTable` at line 117](https://github.com/schemacrawler/SchemaCrawler/blob/c4a8201b7745957d3af67fb576a763f1eddae901/schemacrawler-api/src/main/java/schemacrawler/crawl/TableRetriever.java#L117).

This is because [`MetadataResultSet.getString("TABLE_CAT")` always returns `null` at TableRetriever:105](https://github.com/schemacrawler/SchemaCrawler/blob/c4a8201b7745957d3af67fb576a763f1eddae901/schemacrawler-api/src/main/java/schemacrawler/crawl/TableRetriever.java#L105), but the `NamedObjectList<SchemaReference> schemas` parameter has the catalog name. So `schemas` has the schema with `NamedObjectKey("test", "public")` but it is then looked up with `NamedObjectKey(null, "public")`, which unsurprisingly returns null.

### SchemaCrawler Version

16.20.4

### Java Version

17

### Operating System and Version

macOs 13.5.1

### Relational Database System and Version

PostgreSQL 15

### JDBC Driver and Version

org.postgresql:postgresql:42.6.0

**Comment by Mahoney** [comment]
Got it to work by changing the options to:
```
SchemaRetrievalOptionsBuilder.builder()
            .withDoesNotSupportCatalogs()
            .toOptions()
```
Guess it would be nicer not to have to, but perhaps this is as designed.

**Comment by sualeh** [comment]
@Mahoney SchemaCrawler is tested with PostgreSQL, and no code tweaks (such as the one above) are needed if you use the [SchemaCrawler plugin for PostgreSQL](https://central.sonatype.com/artifact/us.fatehi/schemacrawler-postgresql/16.20.4/versions). This is a separate jar that needs to be on your CLASSPATH. See the [unit tests](https://github.com/schemacrawler/SchemaCrawler/blob/main/schemacrawler-postgresql/src/test/java/schemacrawler/integration/test/PostgreSQL14Test.java) to get an idea of how to code.

**Comment by sualeh** [comment]
@Mahoney SchemaCrawler is [tested without the plugin](https://github.com/schemacrawler/SchemaCrawler/blob/main/schemacrawler-dbtest/src/test/java/schemacrawler/integration/test/WithoutPluginPostgreSQLTest.java), though I recommend using the plugin.

**Comment by sualeh** [comment]
@Mahoney Any updates?

**Comment by Mahoney** [comment]
I was already using the plugin.

I switched from `SchemaCrawler(dataSource, schemaRetrievalOptions, schemaCrawlerOptions).crawl()` to `SchemaCrawlerUtility.getCatalog(dataSource, schemaCrawlerOptions)` and that worked as expected. Thanks!

**Comment by sualeh** [comment]
@Mahoney Perfect. That is the simplest way to use it.
