### ISSUE TITLE
Unknown command <serialize> when using api

### ISSUE THREAD

**Issue by Whatshiywl** [schemacrawler/SchemaCrawler#1270]
### Description

When I try to generate a JSON output via the SchemaCrawler API importing dependencies with Maven, I get an error stating that the `serialize` command is unknown. Other commands like `schema` do work correctly.
The same error does not happen when running schemacrawler via the commandline and it also doesn't happen when using the API when I manually download the SchemaCrawler distribution and add it to my classpath, so I suspect I'm missing a maven dependency.

### How to Reproduce

I have created a gist with my current setup. I'm building it with `mvn package` and running with `java -jar [generated.jar]`.
Here's my [Main.java](https://gist.github.com/Whatshiywl/e58e4621e09654f19c5b8c399e30845c#file-main-java) class.
Here's my [pom.xml](https://gist.github.com/Whatshiywl/e58e4621e09654f19c5b8c399e30845c#file-pom-xml) file.
I've also added the [full output](https://gist.github.com/Whatshiywl/e58e4621e09654f19c5b8c399e30845c#file-output-txt) (error at the end).
Finally, [here is the result](https://gist.github.com/Whatshiywl/e58e4621e09654f19c5b8c399e30845c#file-dependency-tree-txt) of `mvn dependency:tree`. I seem to have all schemacrawler*.jar that comes with the downloaded distribution.

### Relevant log output

```shell
Exception in thread "main" schemacrawler.schemacrawler.exceptions.ExecutionRuntimeException: Unknown command <serialize>
        at schemacrawler.tools.executable.CommandRegistry.findSupportedCommands(CommandRegistry.java:190)
        at schemacrawler.tools.executable.CommandRegistry.configureNewCommand(CommandRegistry.java:118)
        at schemacrawler.tools.executable.SchemaCrawlerExecutable.loadCommand(SchemaCrawlerExecutable.java:218)
        at schemacrawler.tools.executable.SchemaCrawlerExecutable.execute(SchemaCrawlerExecutable.java:110)
        at foo.bar.Main.main(Main.java:64)
```

### SchemaCrawler Version

16.20.4

### Java Version

11.0.19

### Operating System and Version

Ubuntu 22.04.2

### Relational Database System and Version

Microsoft SQL Server 2017 CU31 - 14.0.3456.2 (x64)

### JDBC Driver and Version

SQLServerDriver  12.2

**Comment by sualeh** [comment]
Take a look at https://github.com/sualeh/schemacrawler-issue1270

**Comment by Whatshiywl** [comment]
Thank you for the quick response! I cloned your project and ran `mvn package && java -jar target/issue1270-1.0-SNAPSHOT-jar-with-dependencies.jar` and ended up getting the same error. Do you mind sharing what OS you are using? I'm thinking it could be an issue with me using Ubuntu?

**Comment by Whatshiywl** [comment]
Update: I just followed the same steps described above (using your project) on Windows 11 and I still see the same issue. Maybe I'm missing something?
This is the output from `mvn dependency:tree` (same on Ubuntu and Windows)
```
[INFO] foo.bar:issue1270:jar:1.0-SNAPSHOT
[INFO] +- us.fatehi:schemacrawler:jar:16.20.4:compile
[INFO] |  \- org.slf4j:slf4j-nop:jar:2.0.7:compile
[INFO] |     \- org.slf4j:slf4j-api:jar:2.0.7:compile
[INFO] +- us.fatehi:schemacrawler-scripting:jar:16.20.4:compile
[INFO] +- us.fatehi:schemacrawler-sqlite:jar:16.20.4:compile
[INFO] |  \- org.xerial:sqlite-jdbc:jar:3.42.0.0:compile
[INFO] +- com.fasterxml.jackson.core:jackson-core:jar:2.15.2:compile
[INFO] +- com.fasterxml.jackson.core:jackson-databind:jar:2.15.2:compile
[INFO] |  \- com.fasterxml.jackson.core:jackson-annotations:jar:2.15.2:compile
[INFO] +- com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:jar:2.15.2:compile
[INFO] |  \- org.yaml:snakeyaml:jar:2.0:compile
[INFO] \- com.fasterxml.jackson.datatype:jackson-datatype-jsr310:jar:2.15.2:compile
```

**Comment by sualeh** [comment]
Did you correct the code (pom.xml and database connection credentials) to use SQL Server instead of SQLite? Does the code run from within your IDE?

**Comment by Whatshiywl** [comment]
I have tried using your project as-is, with minimal setup. Just cloning the repo, building with maven and running the resulting JAR, without changing any of the files. I have also tried changing the pom.xml and Main.java code to include the sqlserver driver and point it to the database I want. Both setups resulted in the same error, both on Ubuntu and on Windows.

As for the IDE, I'm using vscode, but I'm not using any built-in functions or plugins to build or run the application. I'm always running maven and java directly from the integrated terminal. Just to be sure, I opened a separate terminal (bash for Ubuntu and Powershell for Windows), navigated to the project folder and ran the same maven and java commands as described above. Still the problem remains.

Once again, I tried running the `schema` command as a sanity check to make sure the driver and database connections are working properly and that the core of schemacrawler is able to make the connection and retreive the necessary information. On all test cases (connect to test.db using sqlite vs connect to my database using sqlserver, ubuntu vs windows, run from vscode vs separate terminal) the `squema` command works without issues. The only thing I changed was:
```
    final SchemaCrawlerExecutable command = new SchemaCrawlerExecutable("serialize");
    command.setOutputOptions(outputOptions.toOptions());
```
to
```
    final SchemaCrawlerExecutable command = new SchemaCrawlerExecutable("schema");
    // command.setOutputOptions(outputOptions.toOptions()); // comment this out to default output to text
```

It still looks like for some reason the `serialize` command is not being added into the CommandRegistry.

**Comment by Whatshiywl** [comment]
Update: In trying to debug the issue, I have replaced my code with the following:
code:
`CommandRegistry.getCommandRegistry().getCommandLineCommands().forEach(c -> System.out.println(c.getName()));`
output:
```
command:schema
null
```

code:
`CommandRegistry.getCommandRegistry().getSupportedCommands().forEach(c -> System.out.println(c));`
output:
```
brief - Shows basic schema information, for tables, views and routines, columns, primary keys, and foreign keys
count - Shows counts of rows in the tables
details - Shows maximum possible detail of the schema, including privileges, and details of privileges, triggers, and check constraints
dump - Shows data from all rows in the tables
list - Shows a list of schema objects
quickdump - Shows data from all rows in the tables, but row order is not guaranteed - this can be used with a minimum info-level for speed
schema - Shows the commonly needed detail of the schema, including details of tables, views and routines, columns, primary keys, indexes, foreign keys, and triggers
```

This seems to add to the idea that the `serialize` command is just not being added to the registry.

**Comment by sualeh** [comment]
@Whatshiywl I have ensured that the code I sent you runs within an IDE. If you are running it from the command-line, you will need to generate complete logs using `--log-level=ALL`, and send them to me.

**Comment by Whatshiywl** [comment]
I'm not sure what you mean by "run within an IDE" and I'm curious as to what the differences are between our setups.
Also, by "running from the command-line" I mean I'm executing the generated `.jar` with `java` directly. I'm not running the `schemacrawler` command.

I have changed `new LoggingConfig(Level.OFF);` to `new LoggingConfig(Level.ALL);` and added the output generated by your project to my gist. Here's the link: https://gist.github.com/Whatshiywl/e58e4621e09654f19c5b8c399e30845c#file-output-issue1270

Could you perhaps share how you are running from "within an IDE" so I can try to reproduce?

**Comment by sualeh** [comment]
I am trying to reproduce your issue.

**Comment by Whatshiywl** [comment]
I have packaged your project into a [docker image](https://hub.docker.com/repository/docker/whatshiywl/schemacrawler-issue1270/general). You can run this image and see the error is happening. I'm using the [official maven image](https://hub.docker.com/_/maven) as a base. Here's the command to run this image:

`docker run --rm whatshiywl/schemacrawler-issue1270`

Let me know if you're able to see the error coming from the container.

**Comment by sualeh** [comment]
Thanks. Let me dig deeper. It may be a bug.

**Comment by sualeh** [comment]
@Whatshiywl Please download the latest code from https://github.com/sualeh/schemacrawler-issue1270
I have changed how the assembly is made by taking the all of the [service loader](https://docs.oracle.com/javase/8/docs/api/java/util/ServiceLoader.html) provider-configuration files into account. Now the code will run from the jar file as well.

**Comment by Whatshiywl** [comment]
It's working now, thank you!
