### ISSUE TITLE
SQLite test failing on it_IT.UTF8 system locale

### ISSUE THREAD

**Issue by lucrus73** [schemacrawler/SchemaCrawler#1297]
### Description

I cloned the repo and tried to build the runnable package with

    $ mvn package

but I got a test failure (see logs). The expected output from the SQLite test differs from actual output because of the thousands separator, which is a dot and not a comma in my italian locale setting.

### How to Reproduce

I tried packaging the code on a Debian GNU Linux 12/trixie system with system locale configured as it_IT.UTF8

### Relevant log output

```shell
[INFO] Running schemacrawler.integration.test.VirtualTablesTest

Output does not match - actual output in
/home/lucio/programmi/SchemaCrawler/schemacrawler-sqlite/target/unit_tests_results_output/VirtualTablesTest.count
[ERROR] Tests run: 4, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.169 s <<< FAILURE! -- in schemacrawler.integration.test.VirtualTablesTest
[ERROR] schemacrawler.integration.test.VirtualTablesTest.count(TestContext) -- Time elapsed: 0.034 s <<< FAILURE!
java.lang.AssertionError: 

Expected: <classpath: </VirtualTablesTest.count>>
     but: mismatched on:
>> expected followed by actual:
big_vocabulary                                                1,000 rows
big_vocabulary                                                1.000 rows

	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:6)
	at schemacrawler.integration.test.VirtualTablesTest.run(VirtualTablesTest.java:123)
	at schemacrawler.integration.test.VirtualTablesTest.count(VirtualTablesTest.java:64)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
```

### SchemaCrawler Version

main branch just cloned from GitHub

### Java Version

openjdk version "17.0.2" 2022-01-18

### Operating System and Version

Debian GNU/Linux 12 + trixie + sid

### Relational Database System and Version

libsqlite3-0:amd64 3.43.0-1

### JDBC Driver and Version

none yet

**Comment by sualeh** [comment]
@lucrus73 Please try again.

**Comment by lucrus73** [comment]
> @lucrus73 Please try again.

It now works, thanks.
