### ISSUE TITLE
Filter views by pattern

### ISSUE THREAD

**Issue by meridsa** [schemacrawler/SchemaCrawler#1420]
### Feature Request

I want to be able to filter views using a regex pattern in the same way as I am able to filter tables.

Configuration option could be: `schemacrawler.view.pattern.exclude`

### Possible Alternatives

I have considered filtering the output text using sed or similar utility.

**Comment by sualeh** [comment]
@meridsa SchemaCrawler treats all table-like objects as tables - these include temporary tables, views, materialized views, etc. SchemaCrawler provides for a single include + exclude regular expression to filter these out by fully qualified name. I do not plan to provide a separate regular expression pair for each type of table-like object.

**Comment by meridsa** [comment]
Thanks for the response! I'll do that.
