### ISSUE TITLE
when I use captial letter in database name in sql server, schema crawler can't match the database name and returns empty value.

### ISSUE THREAD

**Issue by pastelto** [schemacrawler/SchemaCrawler#1460]
### Description

I have a same issue with this. 
[https://github.com/schemacrawler/SchemaCrawler/issues/176#issuecomment-810962748](url)

When I make database in sql server with captial letter, schema crawler can't getSchema. 
Since sql server is case-sensitive and schema crawler is(might be) not case-sensitive, I think that's why schema crawler can't get the schema.

it's working fine when database name is 'user' in all small letter, but not working with 'User' which includes a captial letter.
could you make case-sensitive in sql server version please?

### How to Reproduce

Create database name Start with captial or includes captial letter using sql server.

### SchemaCrawler Version

16.19.9

### Java Version

11

### Operating System and Version

IntelliJ 2022.03.01

### Relational Database System and Version

sql server 2022

### JDBC Driver and Version

mssql-jdbc : 12.2.0.jre8 and ojdbc8 : 21.9.0.0

**Comment by sualeh** [comment]
If the database reports that that object names are case-sensitive, SchemaCrawler will enclose the names with double-quotes. Please provide more details of the actual command-line you are using.

**Comment by pastelto** [comment]
The database doesn't report any messages. I'm using it as a library, and it just returns that there is no schema, although there is.

When I have a database name list in SQL Server, for example: ['user', 'user1', 'User2', 'user3'], and I want to get all the schemas from 'User2', the same thing happens like this:
![image](https://github.com/schemacrawler/SchemaCrawler/assets/80407403/87873524-f50b-43d0-8705-8c663c17e276)

The real schema name value is 'User2', but when it goes through the normalizeCatalogName function, it returns the name in lowercase. Then the returned value, which is 'user2', can't be found in the database name list in SQL Server, which I wrote as an example: ['user', 'user1', 'User2', 'user3']. I think it doesn't recognize the 'User2' with 'user2' then it means sql server is case-sensitivie when getting a schema.
![image](https://github.com/schemacrawler/SchemaCrawler/assets/80407403/a9a825e0-77c6-4f7f-a7fe-44b29b93efe2)

It works okay with Oracle because Oracle is not case-sensitive. However, when it comes to SQL Server, if a user saves the database name as 'UserName', it will be saved exactly like that. So, I think the return value should be the exact same name as the real schema value, not the lowercase applied one.

This case can be reproduced easily just creating a database name in sql server with only lower case letter and one starts with a capital letter.

**Comment by pastelto** [comment]
Oh I accidently closed the issue.

**Comment by pastelto** [comment]
Oh I accidently closed the issue.

**Comment by sualeh** [comment]
@pastelto I cannot read your code from the screenshot. Please could you paste that code snippet in text on this issue?

**Comment by pastelto** [comment]
Oh, Those screenshot are from [https://github.com/schemacrawler/SchemaCrawler/issues/176#issuecomment-810962748](https://github.com/schemacrawler/SchemaCrawler/issues/url). Because it was exactly same issue with mine. 

I'm using library and so I can't debug deeper.. I can debug until here. 

`    private void crawlSchemas() throws Exception {
        SchemaRetriever retriever = new SchemaRetriever(this.retrieverConnection, this.catalog, this.options);
        this.taskRunner.add("retrieveSchemas", () -> {
            retriever.retrieveSchemas(this.options.getLimitOptions().get(DatabaseObjectRuleForInclusion.ruleForSchemaInclusion));
        }, new SchemaInfoRetrieval[0]).submit();
        this.taskRunner.add("filterAndSortSchemas", () -> {
            this.catalog.reduce(Schema.class, ReducerFactory.getSchemaReducer(this.options));
        }, new SchemaInfoRetrieval[0]).submit();
        **NamedObjectList<SchemaReference> schemas = retriever.getAllSchemas();**
        if (schemas.isEmpty()) {
            throw new ExecutionRuntimeException("No matching schemas found");
        } else {
            LOGGER.log(Level.INFO, new StringFormat("Retrieved %d schemas", new Object[]{schemas.size()}));
        }
    }`
    
 and those bold code is where I get a error. All the data are correct until there and then after "retriever.getAllSchemas()" I can't get the schema and I do have tables and column in that database. It works okay perfectly with all lower case database name but it doesn't work when database name has a single captial letter. I tested a lot with database name.

**Comment by sualeh** [comment]
@pastelto I will need your code, so I can see what you are doing, and try to reproduce it. Can you create some sample code in a GitHub Gist, and send me a link? I will debug through the SchemaCrawler code once I have a test case set up.

**Comment by pastelto** [comment]
Okay. I will make a sample code and send you a link.

Thanks for your help.

2024년 2월 8일 (목) 오전 12:36, Sualeh Fatehi ***@***.***>님이 작성:

**Comment by pastelto** [comment]
https://gist.github.com/pastelto/00b530b025aabaf43263147cd733131a

Thanks for waiting. Here is the code!
It's not working in sql server only when database name starts with capital letter or has a capital letter in the database.

**Comment by sualeh** [comment]
@pastelto Please let me know if you have tried the sample code I provided.

**Comment by pastelto** [comment]
Hello, I've tried to run the sample code, but I couldn't connect to the docker database. I just want to check if there is anything I need to change the provided database url to run the main.java? like changing localhost to another ip address?? <jdbc:sqlserver://**localhost**:1433~

Thanks

**Comment by sualeh** [comment]
@pastelto Please look at the Docker documentation, since I am using an image that is publicly available. Please tweak the code as needed.

**Comment by pastelto** [comment]
Hello, I solved this problem. When it comes to database name contains Uppercase, it returns with extra "" ,for example, ""User"". That was the problem. Thanks a lot. Hope you have a great day.

**Comment by talha31093** [comment]
@pastelto I'm facing a similar problem, 
>> When it comes to database name contains Uppercase, it returns with extra "" ,for example, ""User"". That was the problem
How did you solve this problem, I'm facing this ""User"" too.

**Comment by pastelto** [comment]
> @pastelto I'm facing a similar problem,
> 
> > When it comes to database name contains Uppercase, it returns with extra "" ,for example, ""User"". That was the problem
> 
> How did you solve this problem, I'm facing this ""User"" too. Isn't this a bug?

Hello I also think it's a bug. Anyway I just used replace function to remove extra double quotation.

**Comment by talha31093** [comment]
> > @pastelto I'm facing a similar problem,
> > > When it comes to database name contains Uppercase, it returns with extra "" ,for example, ""User"". That was the problem
> > 
> > 
> > How did you solve this problem, I'm facing this ""User"" too. Isn't this a bug?
> 
> Hello I also think it's a bug. Anyway I just used replace function to remove extra double quotation.

But Identifiers field quoteMixedCaseIdentifiers  is not editable, where did you replace it? Can you please send the code snippet?

**Comment by pastelto** [comment]
`LimitOptionsBuilder.builder().includeSchemas(schema -> Arrays.asList(databaseName).contains(schema.replace("\"", "")))`

I solved it like this.

**Comment by sualeh** [comment]
> Hello I also think it's a bug. Anyway I just used replace function to remove extra double quotation.

@pastelto Please could you help me to reproduce the issue? Please use a PR on https://github.com/sualeh/schemacrawler-issue1460 to show me how to reproduce.
