### ISSUE TITLE
Fluent assertion with assertj

### ISSUE THREAD

**Issue by bekoenig** [schemacrawler/SchemaCrawler#1544]
### Feature Request

Writing junit tests with schema crawler is powerful to check the consistency of a data model change. The catalog api is well designed but also very complex. So it's hard to getting in and the resulting assertion code has a lot of boilerplate and looks like a mess:

```
Table tableEntity1 = catalog.lookupTable(catalog.lookupSchema("EXAMPLE_SCHEMA").orElseThrow(),
			"EXAMPLE_ENTITY1").orElseThrow();
assertThat(tableEntity1.getColumns())
  .anyMatch(x -> x.getName().equals("ENTITY1_ID") && x.getColumnDataType().getName().equals("CHAR") && x.getSize() == 36)
  .anyMatch(x -> x.getName().equals("ATTRIBUTE1") && x.getColumnDataType().getName().equals("VARCHAR") && x.getSize() == 250);
assertThat(tableEntity1.getTableConstraints())
  .anyMatch(x -> x.getName().equals("EXAMPLE_ENTITY1_PK") && x.getConstrainedColumns().stream().anyMatch(y -> y.getName().equals("ENTITY1_ID")));
```

### Possible Alternatives

A new module like "schemacrawler-test" includes an assertion which supports a dsl like:

```
assertThat(catalog)
  .hasSchema("EXAMPLE_SCHEMA")
  .hasTable("EXAMPLE_ENTITY1")
  .hasColumn(withName("ENTITY1_ID").withColumnDataType("CHAR", 36))
  .hasColumn(withName("ATTRIBUTE1").withColumnDataType("VARCHAR", 250))
  .hasTableConstraint(withName("EXAMPLE_ENTITY1_PK").withConstrainedColumn(withName("ENTITY1_ID")));
```

### Additional Context

If you are interested in such an extension, I can start a first implementation and contribute it!

I really like your project and I'm trying to promote it in my company!

**Comment by sualeh** [comment]
@bekoenig That is a great idea! Why don't you start your project, and I will link to it from the SchemaCrawler website.

**Comment by bekoenig** [comment]
@sualeh my initial implementation is completed and the first stable release will be visible at [maven central](https://central.sonatype.com/artifact/io.github.bekoenig/assertj-schemacrawler/overview) in the next hours.

You can link the repository [assertj-schemacrawler](https://github.com/bekoenig/assertj-schemacrawler).
