### ISSUE TITLE
Generated columns with `stored` in sqlite are not marked as generated

### ISSUE THREAD

**Issue by fdietze** [schemacrawler/SchemaCrawler#1589]
### Description

It seems like generated columns with `stored` in sqlite are not marked as generated.

### How to Reproduce

create the following schema with sqlite:

```sql
create table foo(
  id integer primary key,
  bar int not null generated always as (id + 1) stored
);
```

Then, on that column `.isGenerated` is `false`. Without the `stored` keyword, it is `true`.

### SchemaCrawler Version

16.21.1

### Java Version

21

### Operating System and Version

NixOS unstable

### Relational Database System and Version

sqlite

### JDBC Driver and Version

org.xerial:sqlite-jdbc::3.46.0.0

**Comment by sualeh** [comment]
I created issue https://github.com/xerial/sqlite-jdbc/issues/1132 to make the fix.

**Comment by sualeh** [comment]
@fdietze Here is the PR I submitted: https://github.com/xerial/sqlite-jdbc/pull/1133

**Comment by fdietze** [comment]
That was quick. Thank you so much for your work!

**Comment by sualeh** [comment]
@fdietze The SQLite JDBC driver team has merged the PR. Once they release, I will release a new version of SchemaCrawler.

**Comment by sualeh** [comment]
@fdietze Please use SchemaCrawler v16.22.1

**Comment by fdietze** [comment]
You are amazing, thank you so much!
