### ISSUE TITLE
Enhancement request: add support for sqlserver extendedproperties and alike

### ISSUE THREAD

**Issue by mauringhio** [schemacrawler/SchemaCrawler#166]
Hi there,
I am proposing you this feature: integrate sqlserver extendedeproperties and alike (oracle comment) in the generated schema documentation.
How difficult would it be to implment this? If you wish not to do that would you at least give me some pointers on how to implment it?

**Comment by sualeh** [comment]
I tested some code for you. Please take a look at:
https://gist.github.com/sualeh/7442627498eae3b9cfda0f3a63bdc59b

**Comment by mauringhio** [comment]
Thanks for your reply! I'll try your code soon.
