### ISSUE TITLE
Add hash of the zip distribution file

### ISSUE THREAD

**Issue by adriens** [schemacrawler/SchemaCrawler#170]
# Environment

N/A

# Issue

Add binary hash file (md5, SHA512)

**Comment by adriens** [comment]
For the current version, what would be perfect would to get the following file as part of the release :

`schemacrawler-14.19.01-distribution.zip.SHA512`

with the following content :

`3AF5FA852F712CCFD24D4A5799C14D5ADD4574F0D871D6C50086F554FECC7901338E83308B45591AFCCE2AC747AB7E3C660366A68BF35C0F3D3F87F7ACC68F7F`

**Comment by adriens** [comment]
This issue is in a way linked to #168

I can't tell you exactly why but i'm preparing you a little surprise 😸

**Comment by sualeh** [comment]
Fixed with commit 33c59d24ad028fd244ddbd0d3ef0e07cd7a16dee
