### ISSUE TITLE
Columns not retrieved from HR database

### ISSUE THREAD

**Issue by scadgek** [schemacrawler/SchemaCrawler#171]
# Environment
- Schemacrawler version 14.19.0.1
- Java version 8
- OS Linux Mint 18.3
- Database: Oracle 12.2.0.1
- JDBC Driver: ojdbc8

# Issue
Steps to reproduce:
1. Import sample HR schema
2. Run inspection with `retrieveTableColumns = true`

As a result, the tables are inspected, but they lack columns completely.

The reason I found is in the scripts from `oracle.information_schema` folder: they include a where clause condition like `TABLE_CONTRAINTS.OWNER NOT IN (..., 'HR', ...) ` which essentially leads to an empty ResultSet.

If excluding `HR` schema was by design, then there's an inconsistency - since I successfully retrieve tables and some other schema data, but lack some additional data like columns (probably something else, I did not check every aspect). What makes the situation worse is that there's no warning or error which would indicate that the schema data retrieved is not consistent.

Otherwise, the list of excluded `owner`s should be configurable, too. And if I try to retrieve data about HR schema, then HR owner should be removed from exclusions.

**Comment by adriens** [comment]
AH AH, fun fix :smile:
