### ISSUE TITLE
Title for linting report of type text is not definable 

### ISSUE THREAD

**Issue by bekoenig** [schemacrawler/SchemaCrawler#1768]
### Description

Title of text report for lints is static (see [here](https://github.com/schemacrawler/SchemaCrawler/blob/4df17299abd68cd9ecb2f19ce5083a1510975a30/schemacrawler-lint/src/main/java/schemacrawler/tools/lint/formatter/LintReportTextFormatter.java#L130)) and can't be defined by LintReportBuilder.

### SchemaCrawler Version

16.23.2

### Java Version

21

### Operating System and Version

Win 10

### Relational Database System and Version

DB2LUW

### JDBC Driver and Version

current

**Comment by sualeh** [comment]
@bekoenig This is true for all the types of SchemaCrawler reports - it is not customizable. What did you want to customize it to? The position that SchemaCrawler takes is that if you want a custom report, you can use any templating language to create a report to your liking.

**Comment by bekoenig** [comment]
It's not a problem for me, but it was confusing when I set this field and nothing happened.

**Comment by sualeh** [comment]
Thanks for reporting this, @bekoenig I think it is a larger issue with a number of reports. I will fix it.

**Comment by sualeh** [comment]
Thanks for reporting this, @bekoenig It seems to be an issue for many types of SchemaCrawler reports. I will fix it.

**Comment by sualeh** [comment]
@bekoenig Sorry I have gone back and forth on what `LintReport` should be. Since with my changes for this issue the title and crawl information now come from standard sources like other SchemaCrawler reports, `LintReport` has been renamed `Lints`. It only contains lints, is immutable, and has useful lookup and streaming methods.

**Comment by sualeh** [comment]
@bekoenig Please use the latest version of SchemaCrawler for more consistent reports.

**Comment by bekoenig** [comment]
Thanks, works like a charm!
