### ISSUE TITLE
SchemaCrawler issues broken JSON when only one 'table' is eligible for printing

### ISSUE THREAD

**Issue by rhymoid** [schemacrawler/SchemaCrawler#178]
# Environment

Issue encountered with:

* SchemaCrawler v16.14.04
* Oracle JDK 1.8.0.141
* (OS type and version irrelevant)
* Microsoft SQL Server (version irrelevant)
* `com.microsoft.sqlserver.jdbc.SQLServerDriver` (6.4.0.jre8)

Issue reproduced with:

* SchemaCrawler master
* OpenJDK 8u162
* Debian 9.4 ("stretch")
* PostgreSQL 9.6
* `org.postgresql.Driver` (9.4)

# Issue

When SchemaCrawler outputs a JSON-encoded version of the schema which contains only one table, the JSON syntax is violated for any empty arrays and objects in the table object:

    [
    {
      "tables": {
        "foreignKeys": [][

        ],
        "indexes": [][

        ],
        "columns": [
          {
            "size": 10,
            "nullable": true,
            "databaseSpecificType": "int4",
            "generated": false,
            "dataType": "INTEGER",
            "name": "column_a",
            "width": "",
            "decimalDigits": 0,
            "remarks": "",
            "autoIncremented": false
          },
          {
            "size": 10,
            "nullable": true,
            "databaseSpecificType": "int4",
            "generated": false,
            "dataType": "INTEGER",
            "name": "column_b",
            "width": "",
            "decimalDigits": 0,
            "remarks": "",
            "autoIncremented": false
          },
          {
            "size": 10,
            "nullable": true,
            "databaseSpecificType": "int4",
            "generated": false,
            "dataType": "INTEGER",
            "name": "column_c",
            "width": "",
            "decimalDigits": 0,
            "remarks": "",
            "autoIncremented": false
          }
        ],
        "name": "example_view",
        "fullName": "public.example_view",
        "type": "view",
        "triggers": [][

        ],
        "tableConstraints": [][

        ],
        "remarks": "",
        "primaryKey": {}
    {}
      },
      "schemaCrawlerHeaderInfo": {
        "crawlTimestamp": "2018-04-18 10:10:04",
        "title": ""
      }
    }]

Note the `[] []` and the `{} {}`.

This does not occur when the schema contains more than one table, or when the schema contains no tables. I suspect that the issue lies in the JSON serialization code:

* No matter how SchemaCrawler ends up selecting exactly one table or view (either because there is only one entity of the chosen `-tabletypes` present in the database, or a `RegularExpressionRule`/`-tables` ends up filtering the set to only one entity), its behaviour is as described above.
* The debug logs show no interesting differences between the normal case (the database has two views, or two tables, or one view and one table) and the problem case (the database has one table).

Because we consume the JSON programmatically, our current workaround is to select more than one view.

**Comment by rhymoid** [comment]
Oh, also note how the `"tables"` field now contains an object instead of an array.

**Comment by sualeh** [comment]
Please use the latest version of SchemaCrawler - v14.20.05
