### ISSUE TITLE
BUILD FAILURE

### ISSUE THREAD

**Issue by csanyipal** [schemacrawler/SchemaCrawler#180]
# Environment

> Specify the
> * version of SchemaCrawler that you are using
svn co https://github.com/schemacrawler/SchemaCrawler.git
> * version of Java that you are using 
java version "1.8.0_162"
 Oracle JDK 1.8.0.162
> * operating system and version that you are using
Gentoo Linux
> * relational database and version that you are using
SQLite 
sqlite3 -version
3.22.0 2018-01-22 18:45:57 0c55d179733b46d8d0ba4d88e01a25e10677046ee3da1d5b1581e86726f2alt1
> * JDBC driver and version that you are using
sqlite-jdbc-3.21.0.jar
# Issue

> Please explain the issue briefly
'mvn package' command failed.
> * Provide the steps that you took to reproduce the issue
1. svn co https://github.com/schemacrawler/SchemaCrawler.git
2. cd SchemaCrawler.git/trunk/schemacrawler-parent/
3. mvn package
get the following messages:
[INFO] 
[ERROR] Tests run: 45, Failures: 2, Errors: 0, Skipped: 0
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] SchemaCrawler [Parent] ............................. SUCCESS [  3.439 s]
[INFO] SchemaCrawler Test Database ........................ SUCCESS [  4.618 s]
[INFO] SchemaCrawler API .................................. SUCCESS [ 31.060 s]
[INFO] SchemaCrawler Tools ................................ SUCCESS [ 15.884 s]
[INFO] SchemaCrawler Commandline .......................... SUCCESS [ 14.677 s]
[INFO] SchemaCrawler Integrations ......................... FAILURE [02:08 min]
[INFO] SchemaCrawler ...................................... SKIPPED
[INFO] SchemaCrawler Lint ................................. SKIPPED
[INFO] SchemaCrawler for IBM DB2 .......................... SKIPPED
[INFO] SchemaCrawler for HyperSQL ......................... SKIPPED
[INFO] SchemaCrawler for MySQL ............................ SKIPPED
[INFO] SchemaCrawler for Oracle ........................... SKIPPED
[INFO] SchemaCrawler for PostgreSQL ....................... SKIPPED
[INFO] SchemaCrawler for SQLite ........................... SKIPPED
[INFO] SchemaCrawler for Microsoft SQL Server ............. SKIPPED
[INFO] SchemaCrawler for Offline Snapshots ................ SKIPPED
[INFO] SchemaCrawler Example Code ......................... SKIPPED
[INFO] SchemaCrawler - Additional Database Tests .......... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 03:18 min
[INFO] Finished at: 2018-04-22T15:02:59+02:00
[INFO] Final Memory: 44M/362M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.20.1:test (default-test) on project schemacrawler-integrations: There are test failures.
[ERROR] 
[ERROR] Please refer to /home/pali/Irataim/AdatbazisTervezok/SchemaCrawler/SchemaCrawler.git/trunk/schemacrawler-integrations/target/surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date]-jvmRun[N].dump, [date].dumpstream and [date]-jvmRun[N].dumpstream.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :schemacrawler-integrations

> * Provide any steps that you took to solve the issue
I do not know what to do so did nothing.
> * Zip and attach the SchemaCrawler debug logs, which can be obtained by running SchemaCrawler with an additional `-loglevel=ALL` on the command-line argument

I appreciated any advices!

**Comment by sualeh** [comment]
Pál, please make sure that you have installed [Graphviz](http://www.graphviz.org/), and put it on your `PATH`. Please follow instructions on [Using SchemaCrawler in Projects and Building SchemaCrawler](http://www.schemacrawler.com/building.html).

**Comment by csanyipal** [comment]
Sualeh,
I have now the runnuble SchemaCrawler here.
Thank you very much!
