### ISSUE TITLE
Feature request: allow for addition / override of dot attributes

### ISSUE THREAD

**Issue by philCryoport** [schemacrawler/SchemaCrawler#181]
# Environment
*    version of SchemaCrawler that you are using
    schemacrawler-14.20.04-distribution

*    version of Java that you are using
    java version "1.8.0_161"
    Java(TM) SE Runtime Environment (build 1.8.0_161-b12)
    Java HotSpot(TM) 64-Bit Server VM (build 25.161-b12, mixed mode)

*    operating system and version that you are using
    Windows 10 Version 1709 (OS Build 16299.371) 64-bit

*    relational database and version that you are using
    MySQL 5.7.21 (AWS RDS)

*    JDBC driver and version that you are using
    04/19/2018 02:04 PM 825,389 mssql-jdbc-6.2.2.jre8.jar
    04/19/2018 02:04 PM 2,001,778 mysql-connector-java-6.0.6.jar
    (came with SchemaCrawler release)

Other relevant libraries:
03/16/2017 09:36 AM 41,203 slf4j-api-1.7.25-jar.jar
(came with SchemaCrawler release)
01/14/2018 11:09 AM 993,917 graphviz-java-0.2.3-jar.jar
01/14/2018 11:09 AM 661,033 graphviz-java-0.2.3-source.jar
(downloaded the GraphViz native Java libraries using the SchemaCrawler download tool.)

# Issue

> Please explain the issue briefly
> * Provide the steps that you took to reproduce the issue
> * Provide any steps that you took to solve the issue
> * Zip and attach the SchemaCrawler debug logs, which can be obtained by running SchemaCrawler with an additional `-loglevel=ALL` on the command-line argument

I use SchemaCrawler to `-server=mysql -portablenames -Gdpi=300 -outputformat=scdot`.  With the large number of tables and foreign key relationships in my database, this results in a diagram with many near-overlapping edges.

It would be great to be able to provide a configuration file that would allow me to alter the `dot` default values for:
* nodesep
* ranksep

And add a value for:
* splines

Right now it requires me to output a `dot` file and then manually edit that `dot` output file to do a change like this:

```
graph [
    nodesep="0.18"
    ranksep="0.46"
    rankdir="RL"
    fontname="Helvetica"
    fontsize="8"
  ];
```

to this:

```
graph [
    nodesep="1"
    ranksep="1"
    rankdir="RL"
    fontname="Helvetica"
    fontsize="8"
	splines="polyline"
  ];
```

It looks like the `dot` values are hard-coded in https://github.com/schemacrawler/SchemaCrawler/blob/master/schemacrawler-tools/src/main/resources/dot.header.txt 

Would you please update the SchemaCrawler application accordingly?

Thanks!

**Comment by sualeh** [comment]
Good idea. I will look at a way to do this.

**Comment by philCryoport** [comment]
Hi there!  I see you implemented code and code-tests for this feature.  Thank you.

When you have a moment -- and if you haven't already -- would you please update the documentation so I can have example commands to model?

Thanks.

**Comment by sualeh** [comment]
Phil, I am trying to get you a release as soon as possible. :smile:

**Comment by philCryoport** [comment]
Sorry, don't mean to rush you 8)  I saw the commit and wanted to help...

**Comment by sualeh** [comment]
Please use the [latest release, v14.20.06](https://github.com/schemacrawler/SchemaCrawler/releases). You can find documentation [on the SchemaCrawler diagramming page](https://www.schemacrawler.com/diagramming.html).

**Comment by sualeh** [comment]
@philCryoport - did this work for you?

**Comment by philCryoport** [comment]
With schemacrawler-14.20.06-distribution on Windows 10, adding the following two lines to `schemacrawler.config.properties`:

```
schemacrawler.graph.graphviz.graph.ranksep=1.0
schemacrawler.graph.graphviz.graph.splines=polyline
```

Works great with:
* `-outputformat=scdot` or `-outputformat=dot`, and
* `dot -T pdf graph.dot -O`

PDF has no errors and at initial glance does seem complete.

Now, if I then add the following in addition to `schemacrawler.config.properties`:

```
schemacrawler.graph.graphviz.graph.nodesep=1.0
```

...I get the following error message when I open the PDF in Adobe Reader DC:

![image](https://user-images.githubusercontent.com/28901899/39646088-2cc69b94-4f8f-11e8-843b-51e87c3962ae.png)

...and the top of the diagram cuts off:
* the top 8 displayed tables, and
* for the 9th top table, it cuts off the node header and the first 5 lines:
```
id INT NOT NULL
    auto-incremented
a_column INT
b_column INT
c_column INT
```

A diff of the dot files generated with and without the nodesep line shows:
![image](https://user-images.githubusercontent.com/28901899/39647603-7631ba0c-4f94-11e8-8a58-da231a778186.png)
(and later on a comparison of `generated on` dates but that doesn't matter in this case)

**Comment by sualeh** [comment]
Thanks for testing. The problem you describe is a Graphviz or Adobe Acrobat issue, and outside of SchemaCrawler. I would suggest trying opening the PDF file in [Foxit PDF Reader](https://www.foxitsoftware.com/pdf-reader/) to see if you get better results.

**Comment by philCryoport** [comment]
Indeed it does open without complaint or any at-first-glance visual problems in Foxit Reader :)

Thank you for adding the feature!

**Comment by sualeh** [comment]
Glad it worked for you.
