### ISSUE TITLE
schemacrawler-lint misses jackson dependencies

### ISSUE THREAD

**Issue by bekoenig** [schemacrawler/SchemaCrawler#1811]
### Description

schemacrawler-lint imports and uses ObjectMapper, YAMLFactory and CollectionType from jackson, but don't references this dependencies in `pom.xml`. 

These dependencies must be included: 

```
<dependency>
    <groupId>com.fasterxml.jackson.core</groupId>
    <artifactId>jackson-core</artifactId>
    <version>${jackson.version}</version>
</dependency>
<dependency>
    <groupId>com.fasterxml.jackson.core</groupId>
    <artifactId>jackson-databind</artifactId>
    <version>${jackson.version}</version>
</dependency>
<dependency>
    <groupId>com.fasterxml.jackson.dataformat</groupId>
    <artifactId>jackson-dataformat-yaml</artifactId>
    <version>${jackson.version}</version>
</dependency>
```

### How to Reproduce

1. include schema-lint as dependency
2. load config from classpath by LinterConfigUtility#readLinterConfigs
3. `ClassNotFoundException` will be thrown

### SchemaCrawler Version

16.24.2

### Java Version

11

### Operating System and Version

manjaro OS

### Relational Database System and Version

PostgreSQL

### JDBC Driver and Version

postgresql 42.7.4

**Comment by sualeh** [comment]
@bekoenig These were "provided" dependencies in the pom, since they do not need to be loaded for other modules. However, I have made them required for lint. Please use SchemaCrawler 16.24.3.

**Comment by bekoenig** [comment]
Thank you. So is it experimental to include only parts of Schemacrawler in third-party projects?

**Comment by sualeh** [comment]
@bekoenig Not really - it is just that nobody except https://github.com/mbarre/schemacrawler-additional-lints had really done that before. I want to design SchemaCrawler as an API. There are definitely some internal parts to it, and you are the one using them. The "external" API is in https://github.com/schemacrawler/SchemaCrawler/tree/main/schemacrawler-examplecode

**Comment by sualeh** [comment]
@bekoenig The idea was more about not introducing (forcing) more dependencies for people who did not need them.
