### ISSUE TITLE
Publish schemacrawler-diff artifact

### ISSUE THREAD

**Issue by AlecStrong** [schemacrawler/SchemaCrawler#182]
Hello! Thank you for the excellent library. I was wondering if the schemacrawler-diff artifact could be publish to maven in addition to all the current artifacts - right now I'm just copying the `SchemaCrawlerDifferBuilder` into my own codebase. I noticed the pom has a publish plugin ready to go so it might already be uploading to maven?

**Comment by sualeh** [comment]
Alec, the code in `schemacrawler-diff` is experimental, and not of the same quality (in my opinion) as the rest of SchemaCrawler. It is provided for illustrative purposes only, and not really maintained. Please copy and modify the code to your liking, like you have done.

**Comment by AlecStrong** [comment]
yup makes sense! Thanks again for the lib
