### ISSUE TITLE
Primary keys not styled differently

### ISSUE THREAD

**Issue by yissachar** [schemacrawler/SchemaCrawler#183]
When I generate a diagram there is no indication as to which fields are the primary keys for the tables. As far as I can tell from the examples this should be indicated by the field being bold and italicized but that isn't happening for me.

Here is the command I am using:

```
./schemacrawler.sh -server=postgresql -url=jdbc:postgresql://localhost:5432/mydb -schemas=public -portablenames -command=schema -outputformat=png -outputfile=database-diagram.png
```

I'm running this on a Postgres 9.6 database and using version 14.20.05 of SchemaCrawler.

**Comment by sualeh** [comment]
Please zip and attach the SchemaCrawler debug logs, which can be obtained by running SchemaCrawler with an additional `-loglevel=ALL` command-line argument.

**Comment by yissachar** [comment]
Here is an image of the problem:
![database-diagram2](https://user-images.githubusercontent.com/2190867/39586445-0f4de60a-4ec5-11e8-9118-946940c230ce.png)

And the logs: [logs.txt.zip](https://github.com/schemacrawler/SchemaCrawler/files/1971562/logs.txt.zip)

**Comment by sualeh** [comment]
Please run the following SQL statement, and let me know what it returns. If your schema is not called `public`, please change the name of the schema it returns.

```sql
SELECT
  NULL AS table_cat,
  n.nspname AS table_schem,
  ct.relname AS table_name,
  a.attname AS column_name,
  (i.keys).n AS key_seq,
  ci.relname AS pk_name
FROM pg_catalog.pg_class ct
JOIN pg_catalog.pg_attribute a
  ON (ct.oid = a.attrelid)
JOIN pg_catalog.pg_namespace n
  ON (ct.relnamespace = n.oid)
JOIN (SELECT
  i.indexrelid,
  i.indrelid,
  i.indisprimary,
  information_schema._pg_expandarray(i.indkey) AS keys
FROM pg_catalog.pg_index i) i
  ON (a.attnum = (i.keys).x
    AND a.attrelid = i.indrelid)
JOIN pg_catalog.pg_class ci
  ON (ci.oid = i.indexrelid)
WHERE TRUE
AND n.nspname = 'public'
AND i.indisprimary
ORDER BY
  table_name,
  pk_name,
  key_seq
```

**Comment by sualeh** [comment]
Or, you could search for your primary key in this:

```sql
SELECT
  *
FROM
  INFORMATION_SCHEMA.TABLE_CONSTRAINTS
WHERE
  CONSTRAINT_TYPE ='PRIMARY KEY'
```

**Comment by sualeh** [comment]
@yissachar - did you check your database for primary keys using the SQL I gave you?

**Comment by yissachar** [comment]
Hi @sualeh, sorry for the delay.

This is the result I got from your first query:

```
table_cat, table_schem, table_name, column_name, key_seq, pk_name
            "public"	    "test"	 "id"	     1    "test_pkey"
```

**Comment by sualeh** [comment]
Let me try to reproduce. It seems like there is a [known bug with the Postgres JDBC driver](https://www.postgresql.org/message-id/200707231358.l6NDwlWh026230@wwwmaster.postgresql.org) which has still not been fixed. SchemaCrawler may need to work around that.

Meanwhile, please send me the results of:

```sql
SELECT
  *
FROM
  INFORMATION_SCHEMA.TABLE_CONSTRAINTS
WHERE
  CONSTRAINT_TYPE = 'PRIMARY KEY'
```

**Comment by sualeh** [comment]
I cannot reproduce your issue. Please send me your `CREATE TABLE` statement.

**Comment by yissachar** [comment]
Constraints:
```
constraint_catalog, constraint_schema, constraint_name, table_catalog, table_schema, table_name, constraint_type, is_deferrable, initially_deferred
"mydb"	                  "public"	  "test_pkey"	    "mydb"	  "public"	 "test"	  "PRIMARY KEY""NO"	"NO"
```

Create table statement:
```
CREATE TABLE test
(
    id character varying NOT NULL,
    foo character varying,
    CONSTRAINT test_pkey PRIMARY KEY (id)
)
```

**Comment by sualeh** [comment]
I cannot reproduce it. I will put in some more logging into the next version, so you can see what is going on.

I am using:
- SchemaCrawler 14.21.01
- PostgreSQL JDBC Driver 42.2.2
- PostgreSQL 9.6.6 


![database-diagram2](https://user-images.githubusercontent.com/36505153/39790179-7aebbc34-5302-11e8-91ea-52767271ebf5.png)

**Comment by sualeh** [comment]
PS: I also tried with PostgreSQL 9.4.7, and could not reproduce. (You are using PostgreSQL 9.4.4) Please use the next SchemaCrawler version, where I will put in some more logging.

**Comment by yissachar** [comment]
I wonder if it is an OS issue? I am on Mac, but a coworker on Windows was not able to reproduce. I will try with the next version, and also try to upgrade my DB to 9.6 which is what I was supposed to be using.

**Comment by sualeh** [comment]
That could well be the case. It may be that Graphviz works differently on a Mac.
