### ISSUE TITLE
Error: Exception retrieving table information: Cannot use null results

### ISSUE THREAD

**Issue by blackdrago** [schemacrawler/SchemaCrawler#184]
# Environment

> * version of SchemaCrawler = SchemaCrawler 14.20.05
> * version of Java: openjdk version "1.8.0_161"
> * Centos Linux 7 (Core) [via vagrant]
> * Oracle 11g
> * Driver: Oracle JDBC 6 (ojdbc6.jar)
--

# Issue
In my current setup, Schemacrawler can successfully perform a number of actions, including listing tables and views from all schemas (or a select schema). So I know that it's connecting to the database and able to gather information about schemas and tables without issue. However, I get the following error whenever I set the infolevel parameter to anything above 'minimum':

```
Error: Exception retrieving table information: Cannot use null results

Re-run SchemaCrawler with just the
-?
option for help

Or, re-run SchemaCrawler with an additional
-loglevel=CONFIG
option for details on the error
```
SchemacCrawler captured output/log: 
[schemacrawler-log.zip](https://github.com/schemacrawler/SchemaCrawler/files/1971967/schemacrawler-log.zip)

To be completely clear, the following command works:

> java -classpath $(echo $SCHEMACRAWLERHOME/_schemacrawler/lib/*.jar | tr ' ' ':') schemacrawler.Main -driver=oracle.jdbc.driver.OracleDriver -url=jdbc:oracle:thin:@//#####:1521/##### -urlx=nullNamePatternMatchesAll=true -user=### -password=# -schemas=### -command=list -infolevel=*minimum*

And the following command fails:

> java -classpath $(echo $SCHEMACRAWLERHOME/_schemacrawler/lib/*.jar | tr ' ' ':') schemacrawler.Main -driver=oracle.jdbc.driver.OracleDriver -url=jdbc:oracle:thin:@//#####:1521/##### -urlx=nullNamePatternMatchesAll=true -user=### -password=# -schemas=### -command=list -infolevel=*standard*

It seems to all boil down to this part of the SQL:
```sql
SELECT
  NULL AS TABLE_CAT,
  COLUMNS.OWNER AS TABLE_SCHEM,
  COLUMNS.TABLE_NAME AS TABLE_NAME,
  COLUMNS.COLUMN_NAME AS COLUMN_NAME,
  DECODE(
  (SELECT A.TYPECODE
     FROM ALL_TYPES A
     WHERE A.TYPE_NAME = COLUMNS.DATA_TYPE
     AND (A.OWNER = COLUMNS.OWNER OR A.OWNER IS NULL)),
  'OBJECT', 2002,
  'COLLECTION', 2003,
  DECODE(substr(COLUMNS.data_type, 1, 9),
    'TIMESTAMP',
      DECODE(substr(COLUMNS.data_type, 10, 1),
        '(',
          DECODE(substr(COLUMNS.data_type, 19, 5),
            'LOCAL', -102, 'TIME ', -101, 93),
        DECODE(substr(COLUMNS.data_type, 16, 5),
          'LOCAL', -102, 'TIME ', -101, 93)),
    'INTERVAL ',
      DECODE(substr(COLUMNS.data_type, 10, 3),
       'DAY', -104, 'YEA', -103),
    DECODE(COLUMNS.data_type,
      'BINARY_DOUBLE', 101,
      'BINARY_FLOAT', 100,
      'BFILE', -13,
      'BLOB', 2004,
      'CHAR', 1,
      'CLOB', 2005,
      'COLLECTION', 2003,
      'DATE', 93,
      'FLOAT', 6,
      'LONG', -1,
      'LONG RAW', -4,
      'NCHAR', -15,
      'NCLOB', 2011,
      'NUMBER', 3,
      'NVARCHAR', -9,
      'NVARCHAR2', -9,
      'OBJECT', 2002,
      'OPAQUE/XMLTYPE', 2009,
      'RAW', -3,
      'REF', 2006,
      'ROWID', -8,
      'SQLXML', 2009,
      'UROWID', -8,
      'VARCHAR2', 12,
      'VARRAY', 2003,
      'XMLTYPE', 2009,
      1111)))
  AS DATA_TYPE,
  COLUMNS.DATA_TYPE AS TYPE_NAME,
  DECODE (COLUMNS.DATA_PRECISION, NULL, DECODE(COLUMNS.DATA_TYPE, 'NUMBER', DECODE(COLUMNS.DATA_SCALE, NULL, 0 , 38), DECODE (COLUMNS.DATA_TYPE, 'CHAR', COLUMNS.CHAR_LENGTH, 'VARCHAR', COLUMNS.CHAR_LENGTH, 'VARCHAR2', COLUMNS.CHAR_LENGTH, 'NVARCHAR2', COLUMNS.CHAR_LENGTH, 'NCHAR', COLUMNS.CHAR_LENGTH, 'NUMBER', 0, COLUMNS.DATA_LENGTH) ), COLUMNS.DATA_PRECISION)
  AS COLUMN_SIZE,
  0 AS BUFFER_LENGTH,
  DECODE (COLUMNS.DATA_TYPE, 'NUMBER', DECODE(COLUMNS.DATA_PRECISION, NULL, DECODE(COLUMNS.DATA_SCALE, NULL, -127 , COLUMNS.DATA_SCALE), COLUMNS.DATA_SCALE), COLUMNS.DATA_SCALE)
  AS DECIMAL_DIGITS,
  10 AS NUM_PREC_RADIX,
  DECODE (COLUMNS.NULLABLE, 'N', 0, 1) AS NULLABLE,
  REMARKS.COMMENTS AS REMARKS,
  COLUMNS.DATA_DEFAULT AS COLUMN_DEF,
  0 AS SQL_DATA_TYPE,
  0 AS SQL_DATETIME_SUB,
  COLUMNS.DATA_LENGTH AS CHAR_OCTET_LENGTH,
  COLUMNS.COLUMN_ID AS ORDINAL_POSITION,
  DECODE (COLUMNS.NULLABLE, 'N', 'NO', 'YES') AS IS_NULLABLE,
  NULL AS SCOPE_CATALOG,
  NULL AS SCOPE_SCHEMA,
  NULL AS SCOPE_TABLE,
  NULL AS SOURCE_DATA_TYPE,
  IDENTITY_COLUMN AS IS_AUTOINCREMENT,
  COLUMNS.VIRTUAL_COLUMN IS_GENERATEDCOLUMN
FROM
  ALL_TAB_COLS COLUMNS
  LEFT OUTER JOIN ALL_COL_COMMENTS REMARKS
    ON
      COLUMNS.OWNER = REMARKS.OWNER
      AND COLUMNS.TABLE_NAME = REMARKS.TABLE_NAME
      AND COLUMNS.COLUMN_NAME = REMARKS.COLUMN_NAME
WHERE
  COLUMNS.OWNER NOT IN
    ('ANONYMOUS', 'APEX_PUBLIC_USER', 'APPQOSSYS', 'BI', 'CTXSYS', 'DBSNMP', 'DIP',
    'EXFSYS', 'FLOWS_30000', 'FLOWS_FILES', 'IX', 'LBACSYS',
    'MDDATA', 'MDSYS', 'MGMT_VIEW', 'OE', 'OLAPSYS', 'ORACLE_OCM',
    'ORDPLUGINS', 'ORDSYS', 'OUTLN', 'OWBSYS', 'PM', 'SCOTT', 'SH',
    'SI_INFORMTN_SCHEMA', 'SPATIAL_CSW_ADMIN_USR', 'SPATIAL_WFS_ADMIN_USR',
    'SYS', 'SYSMAN', 'SYSTEM', 'TSMSYS', 'WKPROXY', 'WKSYS', 'WK_TEST',
    'WMSYS', 'XDB', 'XS$NULL', 'RDSADMIN')
  AND NOT REGEXP_LIKE(COLUMNS.OWNER, '^APEX_[0-9]{6}$')
  AND NOT REGEXP_LIKE(COLUMNS.OWNER, '^FLOWS_[0-9]{5,6}$')
  AND REGEXP_LIKE(COLUMNS.OWNER, 'CEBSBIN')
  AND COLUMNS.TABLE_NAME NOT LIKE 'BIN$%'
  AND NOT REGEXP_LIKE(COLUMNS.TABLE_NAME, '^(SYS_IOT|MDOS|MDRS|MDRT|MDOT|MDXT)_.*$')
ORDER BY
  TABLE_SCHEM,
  TABLE_NAME,
  ORDINAL_POSITION
```
Error Msg = ORA-00904: "IDENTITY_COLUMN": invalid identifier

But I'm not sure what I'm doing wrong.

**Comment by sualeh** [comment]
SchemaCrawler support was built for Oracle 12g. A couple of people have reported trying to use Oracle 11g. I will look at Oracle 12g adoption statistics, and see if it it is better to roll back support for Oracle 12g.

**Comment by blackdrago** [comment]
Is this something I can remedy by rolling back to an earlier version of SchemaCrawler? Or is Oracle 12c (and up) only supported? I've used SchemaCrawler before with MySQL and loved the capabilities and results, which is why it was my first choice when working with Oracle, too. But I understand if the database version isn't supported.

**Comment by sualeh** [comment]
Kylie, thank you for using SchemaCrawler! I have recently had a few people ask about Oracle 11g support, and I will modify SchemaCrawler to support both Oracle 11g and Oracle 12c. Meanwhile, you have a couple of options:
1. Use an older version of SchemaCrawler. You can try with [SchemaCrawler 14.17.05](https://github.com/schemacrawler/SchemaCrawler/releases/tag/v14.17.05).
2. Or, you can remove the SchemaCrawler plugin for Oracle, which is in a file that looks like `schemacrawler-oracle*.jar` in the `lib/` folder.

**Comment by sualeh** [comment]
Did it work for you, Kylie @blackdrago?

**Comment by blackdrago** [comment]
@sualeh Yes, it did! Thank you! :)
