### ISSUE TITLE
MonetDB support

### ISSUE THREAD

**Issue by eyalroz** [schemacrawler/SchemaCrawler#187]
[MonetDB](http://www.monetdb.org/) is one of the leading FOSS analytics-oriented DBMSes, and quite popular in academia. It also has a [JDBC driver](https://www.monetdb.org/Documentation/Manuals/SQLreference/Programming/JDBC).

So, please add support for it!

**Comment by schemacrawler** [comment]
SchemaCrawler supports MonetDB out of the box. I have enforced this by means of a new unit test. Please drop the MonetDB JDBC driver jar file into the SchemaCrawler `lib/` folder.

**Comment by adriens** [comment]
@eyalroz : can you just confirm me that you are using the following jdbc driver ?


```xml
<dependency>
    <groupId>monetdb</groupId>
    <artifactId>monetdb-jdbc-new</artifactId>
    <version>2.36</version>
</dependency>
```

**Comment by eyalroz** [comment]
Actually, I'm not using SchemaCrawler, at the moment at all, I was just considering it; and I don't actually do any Java work these days, so - I can't confirm... sorry :-(

**Comment by adriens** [comment]
Ok @eyalroz , once you know, can you please let me know so i add the driver to the debian package install ?
