### ISSUE TITLE
New linter "no non-nullable data columns" in v15.01.01 ?

### ISSUE THREAD

**Issue by ThisGuenter** [schemacrawler/SchemaCrawler#196]
Can't find it in the documentation - what id to use in schemacrawler-linter-configs ?

**Comment by ThisGuenter** [comment]
Problem is not specific to version 15.01.01

Table definition:
CREATE TABLE TABLE_IOT
  (
    ID NUMBER (19) NOT NULL ,
    CONSTRAINT TABLE_IOT_PK PRIMARY KEY ( ID )
  )
  ORGANIZATION INDEX NOLOGGING ;

In the log i found following entry:
Sep 13, 2018 2:01:28 PM schemacrawler.tools.lint.BaseLinter lint
FEIN: Including <user.table_iot.id> since it matches /.*/
Sep 13, 2018 2:01:28 PM schemacrawler.tools.lint.Linter addLint
FEIN: Found lint for user.table_iot: no non-nullable data columns --> null

**Comment by sualeh** [comment]
I will takw a look.

**Comment by sualeh** [comment]
@ThisGuenter  - please take a look at [schemacrawler-linter-configs.xml](https://github.com/schemacrawler/SchemaCrawler/blob/master/schemacrawler-docs/config/schemacrawler-linter-configs.xml#L45-L47). This linter looks for tables that may not store any meaningful data. The documentation is on the [lint](https://www.schemacrawler.com/lint.html) webpage on the SchemaCrawler website.

**Comment by ThisGuenter** [comment]
Thanks Sualeh, the linter with id "schemacrawler.tools.linter.LinterTableAllNullableColumns" is responsible for the message "no non-nullable data columns" - It would be great if the id would also would be reported in the output. For me "AllNullableColumns" does not fit to my table definition (single column NOT NULL)

**Comment by sualeh** [comment]
@ThisGuenter - the linter id is output in the JSON output format. I think it would only add clutter to the text or HTML output. If you need to see the linter id, please generate JSON output, and look for the id. Then you can read the documentation for that id on [the SchemaCrawler website lint page.](https://www.schemacrawler.com/lint.html)
