### ISSUE TITLE
Linting on 15.01.01 > Interfaces have changed for plugins since 14.17.03

### ISSUE THREAD

**Issue by adriens** [schemacrawler/SchemaCrawler#197]
# Context

We plan to upgrade the latest debian package, including additional lints? Still the 15.x has seen a lot of code refactoring causing compile failure. Any guidelines would be greatly apprciated.

# Environment

> Specify the
> * version of SchemaCrawler that you are using **15.01.01**
> * version of Java that you are using **1.8**
> * operating system and version that you are using **Not depending on it**
> * relational datavase and version that you are using **Not depending on it**
> * JDBC driver and version that you are using **Not depending on it**

# Issue

We are trying to upgrade additional-lints (see https://github.com/mbarre/schemacrawler-additional-lints/issues/131) but some interfaces and methods have changed a lot, causing compilation to fail.

## getJavSqlType()

First, ```schemacrawler.​schema.​JavaSqlType``` has lost its ```getJavaSqlType()``` method. Can you tell us what we should put instead ? We were using it to test its kind of type (text vs. numeric vs. binary, see sample below :

```java
public static final boolean isSqlTypeLargeTextBased(ColumnDataType dataType) {
		return dataType.getJavaSqlType().getJavaSqlType() == Types.CLOB
                        || dataType.getJavaSqlType().getJavaSqlType() == Types.LONGVARCHAR
                        || "text".equalsIgnoreCase(dataType.getDatabaseSpecificTypeName());
	}
```

## SchemaCrawlerOptions refactoring

`SchemaCrawlerOptions` also had a big refactoring, the following code cannot run anymore, could you please provide us some guidelines ?

```java
final SchemaCrawlerOptions options = new SchemaCrawlerOptions();
            // Set what details are required in the schema - this affects the
            // time taken to crawl the schema
            options.setSchemaInfoLevel(SchemaInfoLevelBuilder.standard());
            options.setTableNamePattern("test_json");
```

**Comment by sualeh** [comment]
For `SchemaCrawlerOptions` see [ApiExample.java](https://github.com/schemacrawler/SchemaCrawler/blob/master/schemacrawler-examplecode/src/main/java/ApiExample.java#L37-L44)

**Comment by sualeh** [comment]
For `schemacrawler.​schema.​JavaSqlType`, use something like:

```java
  public static final boolean isSqlTypeLargeTextBased(ColumnDataType dataType)
  {
    return EnumSet.of(JavaSqlTypeGroup.binary, JavaSqlTypeGroup.large_object)
      .contains(dataType.getJavaSqlType().getJavaSqlTypeGroup())
           || "text".equalsIgnoreCase(dataType.getDatabaseSpecificTypeName());
  }
```

**Comment by sualeh** [comment]
The reason that `schemacrawler.​schema.​JavaSqlType` has lost its `getJavaSqlType()` method is that Java 8 has made the `java.sql.Types` type number vendor specific. Java 8 adds `java.sql.SQLType` with a `getVendorTypeNumber()`, and the JDBC implementation _is just one_ of the possible implementations. The default implementation is `java.sql.JDBCType`, which wraps the `java.sql.Types` type number in `getVendorTypeNumber()`. However, each database driver is free to provide it's own implementation. 

SchemaCrawler's `schemacrawler.schema.JavaSqlType` is now an enhanced version of Java's `java.sql.JDBCType`.

**Comment by adriens** [comment]
WOW, I did not pay attention to this...this is not a little change for this part of the code. It means we depend on jdbc drivers implementation/database vendor...in a way, ...it sucks :smile:

**Comment by adriens** [comment]
We have to :thinking: about it on our side...
