### ISSUE TITLE
Plugin on 15.01.01 > unable to compile existing plugins

### ISSUE THREAD

**Issue by adriens** [schemacrawler/SchemaCrawler#198]
Hi, while trying to upgrade an existing plugin to the 15.*, I have a lot of exceptions complaining about interfaces changes methods to be overriden....

Can you please confirm me that the archetypes are up to date ? This would be easier to me to figure out what i should change in my code.

Thank you in advance for your help, I have a very fun idea to develop and I need to upgrade my plugin first. 😸

**Comment by adriens** [comment]
About the fun idea that will be followed by a dedicated article : https://www.linkedin.com/feed/update/urn:li:activity:6447386387846037504

I won't tell you more about it... I just can tell you that @michele is aware of the new idea. I'm very excited to start implementing it !!!

**Comment by sualeh** [comment]
Still trying to deploy to Nexus...

**Comment by adriens** [comment]
I've switched all to jitpack...it's just a breeze...

**Comment by adriens** [comment]
Maybe could you give a try to Jfrog, should be also pretty cool and easy.

**Comment by sualeh** [comment]
The new release is deployed to The Central Repository
