### ISSUE TITLE
Feature Request > add outputOptions.setOutputFile(File)

### ISSUE THREAD

**Issue by adriens** [schemacrawler/SchemaCrawler#199]
Hi, while running some test on Windows, I'm facing native runtime issues on the jvm.

Could you consider to add to 

`outputOptions.setOutputFile(Path)`

ths one :

`outputOptions.setOutputFile(File)` ?

**Comment by adriens** [comment]
Hopefully this should make it easier to make testing easier on WIndows.

**Comment by sualeh** [comment]
@adriens - I do not plan to make changes to older versions of SchemaCrawler. Can I help you workaround your issue? Please take a look at [ProjectRoot.java](https://github.com/schemacrawler/SchemaCrawler/blob/master/schemacrawler-distrib/src/test/java/schemacrawler/test/sitegen/ProjectRoot.java) and see how it is used in [SiteGraphVariationsTest.java](https://github.com/schemacrawler/SchemaCrawler/blob/master/schemacrawler-distrib/src/test/java/schemacrawler/test/sitegen/SiteGraphVariationsTest.java).

**Comment by adriens** [comment]
Hmmm, sure, the fact is that I would be interested in getting this on the 15.x series. I'm working on preparing additional lints to support the 15.x. There is some work to do, but it's really worth it.

**Comment by sualeh** [comment]
Please use the approach I have suggested. It is tested on Windows and Linux, and in use every single day on both platforms.

**Comment by adriens** [comment]
Ok, thanks, I'm having a look at it hence.

**Comment by sualeh** [comment]
PS: SchemaCrawler 15.x.x uses `OutputOptionsBuilder`, not `OutputOptions`.

**Comment by adriens** [comment]
Thanks for pointing this too 😄
