### ISSUE TITLE
Offline Snapshots: Slow reading

### ISSUE THREAD

**Issue by patric-r** [schemacrawler/SchemaCrawler#201]
Hi,
the performance for reading/parsing offline snapshots should be improved.
In my case, I use this feature for short-living applications. Reading a 5 MB (zipped) offline snapshot of a mid-sized schema (containing only tables, indices and FKs),
schemacrawler takes up to 6 seconds on a high-end core i7 machine.

I did some basic profiling, most of the time is spent within 
com.thoughtworks.xstream.XStream.unmarshal()

Is there any reason why JAXP/JAXB is not used for XML parsing?

Cheers!

**Comment by sualeh** [comment]
@patric-r you are free to use any serialization and deserialization library that you would like to use. Please take a look at [CatalogSerializationTest.java](https://github.com/schemacrawler/SchemaCrawler/blob/2d98a8d8316ef80f484003a7e830900c0e622a96/schemacrawler-integrations/src/test/java/schemacrawler/integration/test/CatalogSerializationTest.java) for examples on how to do your own serialization and deserialization.

**Comment by sualeh** [comment]
Please use SchemaCrawler 15.01.03 - the serialization strategy has changed.

**Comment by sualeh** [comment]
How fast has the serialization become now?

**Comment by patric-r** [comment]
I'll tell you as soon as I can use it again (because of issue #237 ). 
For now, I have to wait for a new schemacrawler release ;-)

**Comment by sualeh** [comment]
Please use SchemaCrawler 15.03.02

**Comment by patric-r** [comment]
Thanks!

It's now working, thank you!
Reading offline snapshots is now 10 times faster in my use case (dropped from 6 sec. to 600 ms)

Keep up the great work!

**Comment by sualeh** [comment]
Thanks!
