### ISSUE TITLE
Command Archetype generates uncompilable code

### ISSUE THREAD

**Issue by adriens** [schemacrawler/SchemaCrawler#202]
Hi,

when I follow instructions : https://www.schemacrawler.com/plugins.html

Section Plugin New SchemaCrawler Commands :

```
mvn archetype:generate -DgroupId=com.mycompany -DartifactId=my-command-plugin 
-DarchetypeGroupId=us.fatehi -DarchetypeArtifactId=schemacrawler-archetype-plugin-command 
-DinteractiveMode=false
````

The built run just avec code generation is failing :

```
COMPILATION ERROR : 
-------------------------------------------------------------
com/github/adriens/AdditionalCommand.java:[23,8] com.github.adriens.AdditionalCommand is not abstract and does not override abstract method checkAvailibility() in schemacrawler.tools.executable.SchemaCrawlerCommand
com/github/adriens/AdditionalCommandProvider.java:[23,8] com.github.adriens.AdditionalCommandProvider is not abstract and does not override abstract method newSchemaCrawlerCommand(java.lang.String) in schemacrawler.tools.executable.CommandProvider
com/github/adriens/AdditionalCommandProvider.java:[27,3] method does not override or implement a method from a supertype
3 errors 
```

**Comment by adriens** [comment]
Maybe a part of the answer is here :

```
 * 
 * @author Automatically generated by SchemaCrawler 15.01.01
 */
```

**Comment by adriens** [comment]
I'm waiting for your new release to test it as I'm creating a new `command`. I keep the opportunity to test the new archetype.
For now, I hit  ⏸

**Comment by sualeh** [comment]
Please use the 15.01.02 archetype.

**Comment by adriens** [comment]
Here is the output I got when I used the command shown on https://www.schemacrawler.com/plugins.html

![2018-09-21 09_06_39-invite de commandes](https://user-images.githubusercontent.com/5235127/45849475-d1030d80-bd7d-11e8-860c-7691eaf8bdc5.png)

**Comment by adriens** [comment]
See : https://mvnrepository.com/artifact/us.fatehi/schemacrawler-archetype-plugin-command

![2018-09-21 09_12_24-maven repository_ us fatehi schemacrawler-archetype-plugin-command](https://user-images.githubusercontent.com/5235127/45849669-9f3e7680-bd7e-11e8-9481-21d3f39ecfe7.png)

**Comment by sualeh** [comment]
https://search.maven.org/search?q=g:us.fatehi%20AND%20a:schemacrawler-archetype-plugin-command&core=gav
