### ISSUE TITLE
Feature Request > Command archetype : additional properties

### ISSUE THREAD

**Issue by adriens** [schemacrawler/SchemaCrawler#204]
Creating a new command is pretty straightforward with the archtype. Still, it would be even easier if we could add, during the command, a property that gives the **command** name so it could be injected in java and help files.

What's your opinion about that ?

**Comment by sualeh** [comment]
Adrien, I sort of like the idea, but at that point, so much should be made customizable. I think that the name of class itself should be customizable - to make it match the name of the command. This is going to be more work than it is worth doing.

**Comment by adriens** [comment]
:heavy_check_mark:
