### ISSUE TITLE
Missing Maven Archetype For SchemaCrawler Command Plugin 15.01.02 (on central)

### ISSUE THREAD

**Issue by adriens** [schemacrawler/SchemaCrawler#207]
As described in https://github.com/schemacrawler/SchemaCrawler/issues/202

the archetype in `15.01.02` is missing on central :

https://mvnrepository.com/artifact/us.fatehi/schemacrawler-archetype-plugin-command

![2018-09-21 09_12_24-maven repository_ us fatehi schemacrawler-archetype-plugin-command](https://user-images.githubusercontent.com/5235127/45849790-3277ac00-bd7f-11e8-8f03-b96d95cd34f8.png)

**Comment by sualeh** [comment]
https://search.maven.org/search?q=g:us.fatehi%20AND%20a:schemacrawler-archetype-plugin-command&core=gav

**Comment by adriens** [comment]
Still the default mvn command does not "see" it 😢

**Comment by adriens** [comment]
Did you give a try ?

**Comment by adriens** [comment]
Manually forcing the target version does the Job. But no idea why `maven` get stuck on the previous version, hence making the documentation not really working 😈 

```
mvn archetype:generate -DgroupId=com.mycompany -DartifactId=my-command-plugin 
-DarchetypeVersion=15.01.02 -DarchetypeGroupId=us.fatehi
-DarchetypeArtifactId=schemacrawler-archetype-plugin-command 
-DinteractiveMode=false
```

![2018-09-21 09_22_47-schemacrawler-plugin-dashboard](https://user-images.githubusercontent.com/5235127/45850023-26d8b500-bd80-11e8-8dca-c0ecaa62f85c.png)

**Comment by sualeh** [comment]
I will update the documentation to include the version number.
