### ISSUE TITLE
15.01.04 causes build to fail on existing command

### ISSUE THREAD

**Issue by adriens** [schemacrawler/SchemaCrawler#213]
As I tried to upgrade to latest schemacrawler on the csv plugin, the build did not pass :

```java
 getSupportedCommands() has private access in schemacrawler.tools.executable
```
https://travis-ci.com/adriens/schemacrawler-additional-command-lints-as-csv/builds/87999829

complaining about :

```
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /home/travis/build/adriens/schemacrawler-additional-command-lints-as-csv/src/test/java/TestCommandPlugin.java:[16,24] getSupportedCommands() has private access in schemacrawler.tools.executable.CommandRegistry
[INFO] 1 error
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
````

Is it a normal behavior ...or a regression ?

Thank you in advance for your help.

**Comment by adriens** [comment]
Fixed in forthcoming version ?

**Comment by adriens** [comment]
Fixed in `15.01.05` ?

**Comment by sualeh** [comment]
This is a test-only issue. I have fixed the new command plugin in the next version (which is still to be released). I have also submitted a pull request for your CSV project. Did you see that pull request?

**Comment by adriens** [comment]
Hi @sualeh , thanks for the PR that also fixes the runId and linTd issues ! 👍 
I will release this we a new version to follow schemacrawler core software.
