### ISSUE TITLE
Bump xstream from 1.4.10-java7 to 1.4.11-java7

### ISSUE THREAD

**Issue by adriens** [schemacrawler/SchemaCrawler#214]
A minor release is out :smile_cat:

**Comment by sualeh** [comment]
SchemaCrawler no longer uses XStream for serialization - see issues #200 and #201

**Comment by adriens** [comment]
You mean... I do not need to deliver it in my packages ?

**Comment by adriens** [comment]
I also have to through away :

```
xmlpull-1.1.3.1.jar
xpp3_min-1.1.4c.jar
xstream-1.4.10.jar
```

**Comment by sualeh** [comment]
Yes. I switched to [fst](https://search.maven.org/artifact/de.ruedigermoeller/fst/2.57/bundle). I may just switch again to plain Java serialization.

**Comment by adriens** [comment]
Got it :

https://github.com/adriens/schemacrawler-deb/issues/44
https://github.com/adriens/schemacrawler-rpm/issues/22
