### ISSUE TITLE
Honor PGDATABASE when connecting to PostgreSQL

### ISSUE THREAD

**Issue by sualeh** [schemacrawler/SchemaCrawler#217]
Honor the `PGDATABASE` environmental variable when connecting to PostgreSQL.

**Comment by adriens** [comment]
Thick :+1:

**Comment by sualeh** [comment]
Consider supporting:
- `PGDATABASE`
- `PGHOST`
- `PGPORT`
- `PGUSER`

See https://www.postgresql.org/docs/9.1/libpq-envars.html
