### ISSUE TITLE
Shell > Only show regular commands in history

### ISSUE THREAD

**Issue by adriens** [schemacrawler/SchemaCrawler#219]
# Actual behavior of shell CLI

Actually, when we hit the `history` command, we get all the commands, including the one that cannot be understood.

![selection_011](https://user-images.githubusercontent.com/5235127/48035776-8d435680-e1b9-11e8-8bb5-b4fd3e67f941.jpg)

# New proposed behavior

Do not display this command in the history.

**Comment by schemacrawler** [comment]
This issue was moved to schemacrawler/SchemaCrawler-Shell#9
