### ISSUE TITLE
Shell > Exit on Ctrl-D hit

### ISSUE THREAD

**Issue by adriens** [schemacrawler/SchemaCrawler#220]
# Actual beahvior

On most shells, on *nix systems, we can leave the session while hitting `Ctrl-D` keys. As we are in a shell, it would be very cool to implement that so it makes the schemacrawler look even more like  a regular shell :+1: ... as if I was on a `ssh` session.

**Comment by schemacrawler** [comment]
This issue was moved to schemacrawler/SchemaCrawler-Shell#8
