### ISSUE TITLE
Switch from Eclipse to IntelliJ

### ISSUE THREAD

**Issue by adriens** [schemacrawler/SchemaCrawler#226]
I see that you use Eclipse ... with you large and widely used software, you could easily get a free IntelliJ license !
https://www.jetbrains.com/opensource/

**Comment by sualeh** [comment]
I do have a license, but I could not set up IntelliJ IDEA well enough to support my complicated Maven project structure. I am still playing with it. I am generally against committing IDE project files into source code control. I have done this mainly for my own convenience, not necessarily for others.
