### ISSUE TITLE
Provide Current Database Name

### ISSUE THREAD

**Issue by sualeh** [schemacrawler/SchemaCrawler#230]
See https://github.com/adriens/schemacrawler-additional-command-lints-as-csv/issues/9

**Comment by sualeh** [comment]
Use `schemacrawler.schema.DatabaseInfo.getServerInfo()`

**Comment by adriens** [comment]
@sualeh , once in the lint, how should I get the schemacrawler instance, i mean in the 

```java
@Override
    public void execute()
            throws Exception {
```

I intend now to implement https://github.com/adriens/schemacrawler-additional-command-lints-as-csv/issues/9

Can you please provide a little code snippet ?
