### ISSUE TITLE
Shebang on ruby files for *nix systems

### ISSUE THREAD

**Issue by adriens** [schemacrawler/SchemaCrawler#233]
# Description

I saw that you added examples based on `ruby`, see code sample found below :

```
## How to Run
1. Start a command shell in the `postgresql` example directory
2. Run `ruby.cmd tables.rb` (or `ruby.sh tables.rb` on Unix) 
````

You could make files easier to run on *nix systems by adding  a [dedicated ruby shebang](https://stackoverflow.com/questions/17447532/what-is-the-use-of-usr-local-bin-ruby-w-at-the-start-of-a-ruby-program), making script much more simple to run on *nix.

**Comment by sualeh** [comment]
@adriens - Ruby is not needed in the PostgreSQL dump example, and I have removed it.
