### ISSUE TITLE
My SQL (and MariaDB) > Get database name

### ISSUE THREAD

**Issue by adriens** [schemacrawler/SchemaCrawler#243]
# Context

Unfortunately, the database name is not part of the variables sent back by the server. To see that :

1. Connect to an existing database (in my case the `crowl` database)
2. Run `SHOW VARIABLES;`
3. Grep `crowl` (or your custom database name) in the output
4. See that you don't have the `crowl` in the variables

While the dedicated function does the job :

```sql
SELECT DATABASE();
```

# Workaround

Like for Oracle, add a `/schemacrawler-mysql/src/main/resources/SERVER_INFORMATION.sql` file with the following content :

```sql
SELECT 'GLOBAL_NAME' AS NAME,
DATABASE() AS VALUE,
'My SQL Database Name';
```

In this script, I've put the same key than on Oracle as it is an Oracle product... in a way it makes sense 😄 
So we get it as part of the properties Map without any other code change.
It also covers MariaDB as they share (for now) [the same function](https://mariadb.com/kb/en/library/database/).

**Comment by sualeh** [comment]
Fixed. This will be available in the next SchemaCrawler release.
