### ISSUE TITLE
[question] Custom generator based on metadata obtained from schema analysis

### ISSUE THREAD

**Issue by archenroot** [schemacrawler/SchemaCrawler#244]
Hell, just found your project here and would like to reuse it for our purpose, so just not sure in which maven module should I be looking at first.

Scenario:
1. Analyze schema
2. Obtain whole result object including whole schema graph including tables, columns, indexes, primary/foreign keys.

With such object I would like to do my own stuff. Can you point me out where to look in the code base first?

**Comment by sualeh** [comment]
Please use [us.fatehi:schemacrawler](https://search.maven.org/search?q=g:us.fatehi%20AND%20a:schemacrawler) and code from [the examples](https://github.com/schemacrawler/SchemaCrawler/tree/master/schemacrawler-examplecode/src/main/java).
