### ISSUE TITLE
Set <run>false</run> for all linters by default

### ISSUE THREAD

**Issue by bheemreddy181** [schemacrawler/SchemaCrawler#245]
**Describe the solution you'd like**
Can we have all the linters by default set to false , so that who ever uses , can just have their own config-xml and their table patterns to switch the linter on. At-least from my understanding everyone use their own xml now.

Right people who ever are not interested/doesn't want to run these linters have a large XML which kind of gives a overhead to understand things. I know switching them off is a one time thing. Cases where if people want to just run one linter they have to explicitly set <run>false</run> to everything else.

**Describe alternatives you've considered**
Set <run>false</run> for all linters by default or give a provision for user to set them false by passing a variable like `--disbleallLinters = true` and overwrite the linters with the xml passed from command line

Then I will have a small XML on my app like below.

![screen shot 2019-03-06 at 3 56 46 pm](https://user-images.githubusercontent.com/3464623/53916811-b7523b80-4028-11e9-9e8a-88e9ffdc8ee4.png)

**Comment by bheemreddy181** [comment]
@sualeh want to hear your thoughts on this ?

**Comment by sualeh** [comment]
@bheemreddy181 - I think it is a good idea.

**Comment by bheemreddy181** [comment]
@sualeh Is there a way you can develop this app agnostic, like even if I add additional-lints package to lib folder it should switch of all the linters from additional lints as well so that no code changes needed there ?

**Comment by sualeh** [comment]
@bheemreddy181 - yes, I should be able to do that.

**Comment by bheemreddy181** [comment]
As we started on-boarding this tool for our APP’s , is there a ETA you can give me on this? I am not really sure I can ask this but if you can ?

**Comment by adriens** [comment]
:+1: for this feature request, great idea. @bheemreddy181

**Comment by bheemreddy181** [comment]
Thanks @sualeh for this quick development.

**Comment by adriens** [comment]
https://github.com/adriens/chocolatey-schemacrawler/issues/40

**Comment by bheemreddy181** [comment]
This is working as expected 

```
./schemacrawler.sh -server=postgresql -database=test -user=bvennapureddy -password='' -linterconfigs=/test/bin/schemacrawler-linter-configs.xml -c=lint -lintdispatch=terminate_system -runalllinters=false


Lints
========================================================================


portfolio.foos                                                   [table]
------------------------------------------------------------------------

                                                        [lint, critical]
	no primary key

Summary of schema lints:
[critical]*     2- no primary key

```
 With the Above Linter-configs
