### ISSUE TITLE
[MAYBE_ISSUE] : JavaSqlType is returning same value for timestamp column and timestamptz column

### ISSUE THREAD

**Issue by bheemreddy181** [schemacrawler/SchemaCrawler#246]
# Issue [POSTGRESQL]

> Please explain the issue briefly
> * column.getColumnDataType().getJavaSqlType() is returning same value for timestamp column and timestamptz column 

**Sample Table Details** 

`<createTable  tableName="test_timetsamp_type" remarks="table for lint LinterTimeStampWithOutTimeZoneColumn">
<column name="id" type="int" remarks="primary key"/>
<column name="content" type="varchar(20)"/>
<column name="created_at"  type="timestamp" remarks="column timestamp type"/>
<column name="updated_at" type="timestamptz" remarks="column timestamp timezone type"/>
</createTable>`

I am seeing same values for created_at and updated_at columns 

# Environment

> Specify the
> * version of SchemaCrawler : Latest
> * version of Java : Same version as SchemaCrawler
> * operating system and version : Same issue on all versions

**Comment by bheemreddy181** [comment]
Refers to https://github.com/pgjdbc/pgjdbc/issues/1384 , https://github.com/pgjdbc/pgjdbc/issues/1381 , https://github.com/pgjdbc/pgjdbc/issues/996 not and issue with SchemaCrawler

**Comment by bheemreddy181** [comment]
There is a fix created not sure when this will be merged : https://github.com/pgjdbc/pgjdbc/pull/695

**Comment by ghusta** [comment]
I think I reported something similar, but still unresolved, in https://github.com/pgjdbc/pgjdbc/issues/807
