### ISSUE TITLE
Impossible to uprade Derby driver to its latest version

### ISSUE THREAD

**Issue by adriens** [schemacrawler/SchemaCrawler#247]
Upgrading Derby to its latest versions causes schemacraler not to be able to find psql drivers in its classpath

https://github.com/adriens/schemacrawler-deb/issues/81

For now, I've locked derby driver to the same version as schemacrawler official release

**Comment by adriens** [comment]
It made me have headaches ! 😢

**Comment by adriens** [comment]
Were you aware of this @sualeh  ?

**Comment by sualeh** [comment]
@adriens - @bheemreddy181 - I will take a look.

**Comment by adriens** [comment]
I could be du to a java 11 runtime on this very latest version, I already faced the same issue with mssql driver

**Comment by sualeh** [comment]
SchemaCrawler works on Java 8 and above, so it will be officially distributed only with the Apache Derby 10.14.x.x JDBC driver. Newer versions of the driver do not support Java 8.

**Comment by adriens** [comment]
Makes sense 👍
