### ISSUE TITLE
Installer or entrypoint and main GUI would be great

### ISSUE THREAD

**Issue by joeyhub** [schemacrawler/SchemaCrawler#250]
It would be nice to easily install this or at least for the downloading have that in the GUI. The first thing I'm expecting when opening the archive is a main entry point but instead it's nested within strangely named folders (using the _ prefix for private).

I think a lot of people might expect a visualisation tool to be a GUI but in reality it's very much a command line tool which is a bit unexpected. When you run it for the first time you don't get quick usage instructions but instead pages of options you're not going to need just to see it working with basic defaults.

It really helps to have here's how to run it as well as an example of the format fields take to avoid having to look up what a JDBC URL looks like.

It's listed in some places alongside other GUI tools which I think is a mistake as it's not an ease of use tool and doesn't simply work out of the box but rather it appears as a sub-component that would be used as part of a larger GUI utility.

I simply can't get it to work.

**Comment by sualeh** [comment]
@joeyhub - thanks for the feedback.
