### ISSUE TITLE
CommandLine : Error: de/flapdoodle/embed/process/distribution/IVersion 

### ISSUE THREAD

**Issue by huitredelombre** [schemacrawler/SchemaCrawler#251]
# Issue

Hi. I would like to use your tool to generate diagram for a postGreSql database. I may just use it baddly but it do not seem like it. I am sorry if this is the case :(

What did I do:
unzip the : schemacrawler-15.06.01-distribution
go to _schemacrawler directory
Lunch: (where  /tmp/parquedump.sql is a psql dump file)
`./schemacrawler.sh -server postgresql -database /tmp/parquedump.sql -command schema -user postgres -password postgres -outputformat png -outputfile tamere -schemas=public `

Output (Here I use your example case in postgresql-readme.html, this is the same error anyway):
`./postgresql.sh -database example.database -infolevel standard -c schema
SchemaCrawler 15.06.01

Error: de/flapdoodle/embed/process/distribution/IVersion

Re-run SchemaCrawler with just the
-?
option for help

Or, re-run SchemaCrawler with an additional
-loglevel=CONFIG
option for details on the error
`

# Environment
Version of java: java -showversion
 ` 
openjdk version "1.8.0_212"
OpenJDK Runtime Environment (build 1.8.0_212-8u212-b01-1~deb9u1-b01)
OpenJDK 64-Bit Server VM (build 25.212-b01, mixed mode)`

Guest Os: uname -a
`
Linux osboxes 4.9.0-8-amd64 #1 SMP Debian 4.9.144-3.1 (2019-02-19) x86_64 GNU/Linux`
Host Os: Window 10

Psql: psql -V
`
psql (PostgreSQL) 11.2 (Debian 11.2-1.pgdg90+1)`

Here is the full error (example lunch):
[outPut.txt](https://github.com/schemacrawler/SchemaCrawler/files/3043964/outPut.txt)

I briefly tried to  decompile the jar file contening the error but I did not succeed. And I checked the code from github and the error line could not emerge from the indicated line.

**Comment by sualeh** [comment]
@huitredelombre - you will need to use the download script provided with the SchemaCrawler distribution. Please run './download.sh postgresql-embedded` from the download directory. 

This is experimental functionality. It will be removed in future SchemaCrawler versions.
