### ISSUE TITLE
getColumn of table test.abc is null in Mysql

### ISSUE THREAD

**Issue by zhanghuidouble** [schemacrawler/SchemaCrawler#252]
# Issue

- my db of Mysql has a table named test.abc,I can create it like 

![image](https://user-images.githubusercontent.com/28583581/56262188-4a928c80-6110-11e9-91a6-792fea9f4910.png)

- getColumns with SchemaCrawler

```java
 final SchemaCrawlerOptionsBuilder schemaCrawlerOptionsBuilder = SchemaCrawlerOptionsBuilder
                        .builder()
                        .includeSchemas(new RegularExpressionInclusionRule(".*\\." + database + "|" + database))
                        .includeTables(new RegularExpressionInclusionRule(".*\\." + table + "|" + table))
                        .includeColumns(new IncludeAll())
                        .includeRoutines(new ExcludeAll())
                        .noEmptyTables()
                        .grepOnlyMatching(true)
                        .withSchemaInfoLevel(schemaInfoLevel);


 simpleCatalog = SchemaCrawlerUtility.getCatalog(connection,
                                                            options);

```

but the columns of test.abc is null

# Environment

> Specify the
>   compile "us.fatehi:schemacrawler-mysql:15.06.01"

**Comment by sualeh** [comment]
I'll take a look. Do you have the logs?

**Comment by zhanghuidouble** [comment]
```java
四月 18, 2019 10:13:29 上午 schemacrawler.crawl.SchemaCrawler lambda$crawlDatabaseInfo$6
信息: Not retrieving additional JDBC driver information, since this was not requested
四月 18, 2019 10:13:29 上午 schemacrawler.crawl.SchemaCrawler crawlDatabaseInfo
信息: Retrieving SchemaCrawler crawl information
四月 18, 2019 10:13:29 上午 schemacrawler.crawl.SchemaCrawler crawlDatabaseInfo
信息: Total time taken for <crawlDatabaseInfo> - 00:00:00.060 hours
- 75.0% - 00:00:00.045 - <retrieveDatabaseInfo>
-  1.7% - 00:00:00.001 - <retrieveAdditionalDatabaseInfo>
-  1.7% - 00:00:00.001 - <retrieveServerInfo>
- 18.3% - 00:00:00.011 - <retrieveJdbcDriverInfo>
-  1.7% - 00:00:00.001 - <retrieveAdditionalJdbcDriverInfo>
-  1.7% - 00:00:00.001 - <retrieveCrawlInfo>

四月 18, 2019 10:13:29 上午 schemacrawler.crawl.SchemaCrawler crawl
信息: 
-- generated by: SchemaCrawler 15.06.01
-- generated on: 2019-04-18 10:13:29
-- database: MySQL 5.6.22
-- driver: MySQL Connector/J mysql-connector-java-8.0.15 (Revision: 79a4336f140499bd22dd07f02b708e163844e3d5)
-- operating system: Mac OS X 10.13.6
-- JVM system: Oracle Corporation Java HotSpot(TM) 64-Bit Server VM 1.8.0_112-b16

四月 18, 2019 10:13:29 上午 schemacrawler.crawl.SchemaCrawler crawlSchemas
信息: Crawling schemas
四月 18, 2019 10:13:29 上午 schemacrawler.crawl.SchemaRetriever retrieveAllSchemas
信息: Retrieving all schemas
四月 18, 2019 10:13:29 上午 schemacrawler.crawl.SchemaRetriever retrieveAllCatalogs
信息: Retrieving all catalogs
四月 18, 2019 10:13:29 上午 schemacrawler.crawl.SchemaRetriever retrieveAllCatalogs
信息: Processed 17 catalogs
四月 18, 2019 10:13:29 上午 schemacrawler.crawl.SchemaCrawler crawlSchemas
信息: Total time taken for <crawlSchemas> - 00:00:00.046 hours
-100.0% - 00:00:00.046 - <retrieveSchemas>
-  0.0% - 00:00:00.000 - <filterAndSortSchemas>

四月 18, 2019 10:13:29 上午 schemacrawler.crawl.SchemaCrawler crawlSchemas
信息: Retrieved 1 schemas
四月 18, 2019 10:13:29 上午 schemacrawler.crawl.SchemaCrawler crawlColumnDataTypes
信息: Crawling column data types
四月 18, 2019 10:13:29 上午 schemacrawler.crawl.SchemaCrawler lambda$crawlColumnDataTypes$0
信息: Not retrieving system column data types, since this was not requested
四月 18, 2019 10:13:29 上午 schemacrawler.crawl.SchemaCrawler lambda$crawlColumnDataTypes$1
信息: Not retrieving user column data types, since this was not requested
四月 18, 2019 10:13:29 上午 schemacrawler.crawl.SchemaCrawler crawlColumnDataTypes
信息: Total time taken for <crawlColumnDataTypes> - 00:00:00.001 hours
-  0.0% - 00:00:00.000 - <retrieveSystemColumnDataTypes>
-100.0% - 00:00:00.001 - <retrieveUserDefinedColumnDataTypes>

四月 18, 2019 10:13:29 上午 schemacrawler.crawl.SchemaCrawler crawlTables
信息: Crawling tables
四月 18, 2019 10:13:29 上午 schemacrawler.crawl.SchemaCrawler lambda$crawlTables$18
信息: Retrieving table names
四月 18, 2019 10:13:29 上午 schemacrawler.crawl.TableRetriever retrieveTables
信息: Retrieving tables, using fast meta-data retrieval
四月 18, 2019 10:13:30 上午 schemacrawler.crawl.TableRetriever retrieveTablesFromMetadataForAllTables
信息: Processed 203 tables
四月 18, 2019 10:13:30 上午 schemacrawler.crawl.MetadataResultSet close
信息: Processed 203 rows for <retrieveTablesFromMetadataForAllTables>
四月 18, 2019 10:13:30 上午 schemacrawler.crawl.SchemaCrawler crawlTables
信息: Retrieved 0 tables
四月 18, 2019 10:13:30 上午 schemacrawler.crawl.SchemaCrawler crawlRoutines
信息: Not retrieving routines, since this was not requested
四月 18, 2019 10:13:30 上午 schemacrawler.crawl.SchemaCrawler crawlSynonyms
信息: Not retrieving synonyms, since this was not requested
四月 18, 2019 10:13:30 上午 schemacrawler.crawl.SchemaCrawler crawlSequences
信息: Not retrieving sequences, since this was not requested
```

**Comment by zhanghuidouble** [comment]
I found that retrieveTablesFromMetadata will return null if the tableNamePattern is not null,because the tableNamesPattern will parse from t est.abc to abc
![image](https://user-images.githubusercontent.com/28583581/56332457-fac0cd80-61c2-11e9-9c9c-bbadf8bc0e4f.png)


![image](https://user-images.githubusercontent.com/28583581/56332523-3491d400-61c3-11e9-9bfe-8aa52f3cc7a7.png)

**Comment by believems** [comment]
The mysql jdbc driver source code location:
- [DatabaseMetaDataUsingInfoSchema.java:789](https://github.com/mysql/mysql-connector-j/blob/release/8.0/src/main/user-impl/java/com/mysql/cj/jdbc/DatabaseMetaDataUsingInfoSchema.java#L789)
- [DatabaseMetaData.java:3614](https://github.com/mysql/mysql-connector-j/blob/release/8.0/src/main/user-impl/java/com/mysql/cj/jdbc/DatabaseMetaData.java#L3614)

**Comment by zhuxt2015** [comment]
One solution is add blackslash before dot in the table name,
[TableColumnRetriever.java#341](https://github.com/schemacrawler/SchemaCrawler/blob/e1e18306f99fa40fb5361458e66ce919c4a249c3/schemacrawler-api/src/main/java/schemacrawler/crawl/TableColumnRetriever.java#L341)
![image](https://user-images.githubusercontent.com/13765310/56481666-c286fb00-64f2-11e9-933d-e21f8114b92d.png)

**Comment by sualeh** [comment]
> One solution is add blackslash before dot in the table name,
> [TableColumnRetriever.java#341](https://github.com/schemacrawler/SchemaCrawler/blob/e1e18306f99fa40fb5361458e66ce919c4a249c3/schemacrawler-api/src/main/java/schemacrawler/crawl/TableColumnRetriever.java#L341)
> ![image](https://user-images.githubusercontent.com/13765310/56481666-c286fb00-64f2-11e9-933d-e21f8114b92d.png)

I don't think that would work, since the JDBC API would not support it. 

I would highly recommend not naming your database tables with a "." in the name, since the dot is used as an object separator by most databases.

**Comment by sualeh** [comment]
Please use a table column metadata retrieval strategy of "metadata_all" to work around this issue with the JDBC driver. You can take a look at the [commit](https://github.com/schemacrawler/SchemaCrawler/commit/7fefd86b50341efa05b4d9a3bb1ea3cb099d37e5) that I used to replicate the issue.

**Comment by zhanghuidouble** [comment]
Yes, I've solved this problem temporarily, but a new problem is that this strategy does not use table names to filter columns, as follows:
![image](https://user-images.githubusercontent.com/28583581/59238666-84c06c00-8c31-11e9-9bd3-31e588883a65.png)

**Comment by zhanghuidouble** [comment]
I think the fundamental solution is the table filtering method of Mysql JDBC DRIVER. This scheme is feasible at present, but if there are too many tables , the performance will decline. Thank you anyway

**Comment by sualeh** [comment]
@zhanghuidouble - I agree that the fundamental issue is with how the driver filters tables. The driver does not support tables with a dot in the name. Is there any way you could avoid naming tables with a dot in the name?
