### ISSUE TITLE
Question: Is it possible to retrieve specific table type (e.g. IOT)

### ISSUE THREAD

**Issue by patric-r** [schemacrawler/SchemaCrawler#254]
Question here (oracle specific).

Using schemacrawler, is it possible to determine whether a table is an index-organized-table (IOT)?
Or to find all IOT within a schema?

Thank you.

**Comment by sualeh** [comment]
Using the API or command-line?

**Comment by patric-r** [comment]
API

**Comment by sualeh** [comment]
@patric-r - please see the commit that closes this issue. Until the next version of SchemaCrawler is released, you can take a similar approach to get information IOT tables.
