### ISSUE TITLE
Sequence support for H2

### ISSUE THREAD

**Issue by fil512** [schemacrawler/SchemaCrawler#257]
We are using H2 to test our migrated schemas vs our annotated schemas.  Would like sequences included in this comparison, but it appears sequences are not currently supported for H2.

Thanks!
Ken

**Comment by sualeh** [comment]
I think I will need to create a H2 plugin. It should be very similar to the HSQLDB plugin, though. Are you using the command-line? If you are doing this programatically, you can add SQL to obtain sequences to the SchemaCrawler information schema views.

**Comment by fil512** [comment]
Sualeh,

Thank you for the quick response!

Here is how I’m doing it today.  I wouldn’t know how to add that SQL you refer to:

		final SchemaCrawlerOptionsBuilder optionsBuilder = SchemaCrawlerOptionsBuilder
			.builder()
			.withSchemaInfoLevel(SchemaInfoLevelBuilder.standard());

		final OutputOptions outputOptions = OutputOptionsBuilder
			.newOutputOptions(TextOutputFormat.text, theExportFile);

		final SchemaCrawlerExecutable executable = new SchemaCrawlerExecutable("schema");
		executable.setSchemaCrawlerOptions(optionsBuilder.toOptions());
		executable.setOutputOptions(outputOptions);
		executable.setConnection(theSchema.getConnection());
		executable.setAdditionalConfiguration(getConfig());
		executable.execute();
Sincerely,
Ken

**Comment by sualeh** [comment]
Let me cook some code up for you.

**Comment by sualeh** [comment]
Try something like:

```java
final SchemaCrawlerOptionsBuilder optionsBuilder = SchemaCrawlerOptionsBuilder
	.builder()
	.withSchemaInfoLevel(SchemaInfoLevelBuilder.standard());

final OutputOptions outputOptions = OutputOptionsBuilder
	.newOutputOptions(TextOutputFormat.text, theExportFile);

final Connection connection = theSchema.getConnection();
final SchemaRetrievalOptionsBuilder schemaRetrievalOptionsBuilder = SchemaRetrievalOptionsBuilder
	.builder(SchemaCrawlerUtility.matchSchemaRetrievalOptions(connection));
schemaRetrievalOptionsBuilder.withInformationSchemaViewsBuilder().withSql(
	InformationSchemaKey.SEQUENCES,"SELECT * FROM INFORMATION_SCHEMA.SEQUENCES");

final SchemaCrawlerExecutable executable = new SchemaCrawlerExecutable("schema");
executable.setSchemaCrawlerOptions(optionsBuilder.toOptions());
executable.setOutputOptions(outputOptions);
executable.setConnection(connection);
executable.setSchemaRetrievalOptions(schemaRetrievalOptionsBuilder.toOptions());
executable.setAdditionalConfiguration(getConfig());
executable.execute(); 
```

**Comment by sualeh** [comment]
Caution: I have not tested this code!

**Comment by fil512** [comment]
Thanks!

I got your changes to work by also including:

final SchemaCrawlerOptionsBuilder optionsBuilder = SchemaCrawlerOptionsBuilder
  .builder()
  .includeAllSequences()
  .withSchemaInfoLevel(SchemaInfoLevelBuilder.maximum());

**Comment by sualeh** [comment]
Excellent.
