### ISSUE TITLE
Mysql - can not get table comment

### ISSUE THREAD

**Issue by zhuxt2015** [schemacrawler/SchemaCrawler#260]
# Issue
I lookup the code,  it use  `SHOW FULL TABLES ` to get table information,  then mysql database only response Tables_in_test  column and Table_type column. This lack much table information。
![image](https://user-images.githubusercontent.com/13765310/63931506-fc12d880-ca87-11e9-9a68-d48302c54277.png)
I think it can use `SHOW TABLE STATUS ` to get all table information,like this:
![image](https://user-images.githubusercontent.com/13765310/63932049-01bcee00-ca89-11e9-93ef-5ec38389c8be.png)

# Environment

SchemaCrawler：16.1.2
Java:1.8.0_202
OS:mac10.12.6
mysql:5.7.16
JDBC driver:com.mysql.cj.jdbc.Driver 8.0

**Comment by sualeh** [comment]
@zhuxt2015 - this is a [known bug #80473](https://bugs.mysql.com/bug.php?id=80473) with the MySQL driver, and has not been fixed by Oracle yet.

**Comment by sualeh** [comment]
I have added a workaround in SchemaCrawler so you can obtain MySQL table comments from table attributes, using code similar to `table.getAttribute("TABLE_COMMENT")`.

This will be available in SchemaCrawler 16.2.2.
