### ISSUE TITLE
SchemaCrawler has lower performance when using oracle 

### ISSUE THREAD

**Issue by ChinaGDMU** [schemacrawler/SchemaCrawler#270]
Hello Sualeh Fatehi,
    I encountered difficulties when using oracle. When testing mysql's performance, the average time was 1.5 seconds when specifying a specific schema and table, but when using oracle, it took more than 30 seconds.Below are some of my sample code and screenshots, please help me to have a look.
config:
![image](https://user-images.githubusercontent.com/32925705/69297951-67afb080-0c47-11ea-898f-a4cbd57a9e00.png)
mysql:
![image](https://user-images.githubusercontent.com/32925705/69298284-54e9ab80-0c48-11ea-8258-9c465c7ff7fa.png)

oracle:
![image](https://user-images.githubusercontent.com/32925705/69298360-8ebab200-0c48-11ea-824a-c621af0d5938.png)
![image](https://user-images.githubusercontent.com/32925705/69298344-83678680-0c48-11ea-8d3a-04fc7a065607.png)

# Environment
> * Specify the
> * SchemaCrawler 16.2.4 
> * Jdk8
> * Windows 10
> * Oracle 11g
> * Driver: Ojdbc6
                                                                                                                                    Damon

**Comment by sualeh** [comment]
Is the SchemaCrawler Oracle plugin on your classpath?

**Comment by ChinaGDMU** [comment]
Yes, the following dependencies are added to the project
![image](https://user-images.githubusercontent.com/32925705/69301903-bb73c700-0c52-11ea-80c6-60d305ffd5ef.png)

**Comment by sualeh** [comment]
How long does this query take? (Replace `${schemas}` in the query, and also use `DBA` for `${catalogscope}`.)

**Comment by ChinaGDMU** [comment]
我换了其他的schema 和 tables ，时间变快了，很奇怪。是否是某个shema的问题。
![image](https://user-images.githubusercontent.com/32925705/69302858-f62b2e80-0c55-11ea-8637-9915624bdb76.png)
![image](https://user-images.githubusercontent.com/32925705/69302881-06dba480-0c56-11ea-8b38-9a8dab41c359.png)

**Comment by ChinaGDMU** [comment]
I changed the schema and tables, and the time got faster, which is weird.Is it a shema problem?

**Comment by ChinaGDMU** [comment]
![image](https://user-images.githubusercontent.com/32925705/69302962-3e4a5100-0c56-11ea-8b1c-8f0d842e1f69.png)
![image](https://user-images.githubusercontent.com/32925705/69302972-4609f580-0c56-11ea-914a-373dd5355d54.png)

**Comment by sualeh** [comment]
It could be.
