### ISSUE TITLE
Do not alias schemacrawler in Docker

### ISSUE THREAD

**Issue by cadavre** [schemacrawler/SchemaCrawler#274]
# Issue

With `alias` set in .bashrc it's impossible to call `schemacralwer.sh` with docker for one-run. BTW It was extremely difficult to find "binary" because of this. Please do not do that in the future!

**Comment by sualeh** [comment]
If you run
```sh
docker run \
-v /root:/home/schcrwlr/share \
--name schemacrawler \
--rm -d -i -t \
--entrypoint=/bin/bash \
schemacrawler/schemacrawler
```
Something like this would work just fine:
`docker exec -t schemacrawler /opt/schemacrawler/schemacrawler.sh --help`

**Comment by cadavre** [comment]
I did, but one would except image's main binary to be available in PATH.
