### ISSUE TITLE
Avoid getting schema FullName (expensive method) when the log is disabled

### ISSUE THREAD

**Issue by voisintotoro** [schemacrawler/SchemaCrawler#276]
In the SchemaRetriever class in the retrieveSchema method there is this code which logs that a schema is excluded. 
On Db2400, i have a case where i have 4000 differents schemas and 3999 to exclude.
the method schemaRef.getFullName() is very expensive.

2 suggestions : 
* add an if(LOGGER.isLevel(Level.FINER)) (best option in my view)
* prefer the getName instead of the getFullName far cheaper in this situation.

``
      if (!schemaFilter.test(schemaRef))
      {
        LOGGER.log(Level.FINER,
                   new StringFormat("Excluding schema <%s>",
                                    schemaRef.getFullName()));
        iterator.remove();
        // continue
      }
``

**Comment by voisintotoro** [comment]
Thank you :-)

**Comment by sualeh** [comment]
@voisintotoro - I will release a new version of SchemaCrawler soon.

**Comment by voisintotoro** [comment]
alright :-)
