### ISSUE TITLE
12.2.7 - Cannot deserialize catalog (can't read offline db)

### ISSUE THREAD

**Issue by jmbeach** [schemacrawler/SchemaCrawler#277]
# Issue

After serializing a database using the following style command:

`--server=sqlserver ...my-connect-info...  --info-level=maximum --port=49903 --command=serialize -o mydb.yaml --schemas=<my-schema>`

I cannot query the offline db:

`--server=offline --database=mydb.yaml --info-level=maximum --password= --command=schema`

I get the error: `Error: Cannot deserialize catalog: invalid stream header: 2D2D2D0A`

I also tried with JSON. Same error.

Logs:
[debug-logs.zip](https://github.com/schemacrawler/SchemaCrawler/files/3951082/debug-logs.zip)

# Environment

SchemaCrawler version 16.2.7
Java version 1.8.0_221
Windows 10
Microsoft SQL Server

**Comment by sualeh** [comment]
[Deserialization is only supported with the Java serialization format, and not with JSON and YAML.](https://www.schemacrawler.com/serialize.html)

**Comment by jmbeach** [comment]
sorry I missed that

**Comment by sualeh** [comment]
@jmbeach  - Jared, no worries. 😄
