### ISSUE TITLE
--title option not appearing in diagrams

### ISSUE THREAD

**Issue by ppoilbarbe** [schemacrawler/SchemaCrawler#281]
# Issue

The option --title does not work for the "schema" command.
The title is taken into account (appears in text format) but is not part of dot generated files (png, pdf, dot...)

Even on the schemacrawler site where there is an example supposed to show a title: "Show a title on the diagram, use --title "Books and Publishers Schema" on the command-line."
But no title appears in the generated image.

Same behaviour for mysql/mariadb, postgresql and sqlite databases.

# Environment

* SchemaCrawler 16.3.0
* Linux 4.15.0-72-generic (Ubuntu 16.04)
* Oracle Corporation Java HotSpot(TM) 64-Bit Server VM 1.8.0_172-b11

**Edit**: I don't know how to attach a log file if needed...

**Comment by sualeh** [comment]
Fixed with commit 12fcc68a40dc61afbc0871ab792aea608874760d.
Will be available in the next release.

**Comment by sualeh** [comment]
@ppoilbarbe - please use SchemaCrawler 16.3.1
