### ISSUE TITLE
Cannot connect to MS SQL Server

### ISSUE THREAD

**Issue by ifuchs** [schemacrawler/SchemaCrawler#288]
I'm trying to create a schema for a MS SQL Server database. COmmand looks like:

schemacrawler-16.4.1-distribution/_schemacrawler/schemacrawler.sh --server sqlserver --user sa --password:prompt --database dbname --host localhost --port 1433 --log-level=CONFIG --command = schema --info-level=standard

Error: Could not connect to jdbc:sqlserver://localhost:1433;databaseName=SEIS;applicationName=SchemaCrawler, for user 'sa', with properties {}: Login failed for user 'sa'. ClientConnectionId:ca9f2861-7faf-4714-ae3b-fa77d6701b10

I am able to connect to the db with python (sqlalchemy) and sqlcmd. Can anyone help me figure out how to fix this?

**Comment by sualeh** [comment]
Can you try with `--password xxxx` and also with `--schemas myschema.dbo` and let me know what you find?

**Comment by ifuchs** [comment]
I made a change to the sa password authority which may help but I got Error: No matching schemas found. Can you tell me exactly what the command should look like?

**Comment by sualeh** [comment]
Please provide the entire command line.

**Comment by sualeh** [comment]
@ifuchs  - have you been able to resolve your issue?

**Comment by sualeh** [comment]
Closed due to inactivity
