### ISSUE TITLE
Microsoft SQL Server MS_Description

### ISSUE THREAD

**Issue by sarthak-k** [schemacrawler/SchemaCrawler#293]
Hi,

I was trying out SchemaCrawler JAVA API to build the data dictionary of the tables, columns we have in our database. But I guess right now it doesn't include MS_Description (extended property for Microsoft SQL Server to describe objects like tables, comments, etc). Is there a way with which we can achieve this in program?

**Comment by sarthak-k** [comment]
Also, I noticed that when databaseName is given in the connectionUrl, the SchemaCrawler doesn't respect the database mentioned but try to go through every database in server to crawl the information. Also, I might be missing something in the Java API. Can you confirm about this behavior?

**Comment by sualeh** [comment]
> Also, I noticed that when databaseName is given in the connectionUrl, the SchemaCrawler doesn't respect the database mentioned but try to go through every database in server to crawl the information. Also, I might be missing something in the Java API. Can you confirm about this behavior?

You need to specify `--schemas` - please see the documentation at [Database System Support](https://www.schemacrawler.com/database-support.html)

**Comment by sualeh** [comment]
@sarthak-k - 
I wrote some [custom code](https://gist.github.com/sualeh/853b5a1e8800ac37bedb4dc91e5e9157) for you to demonstrate how this is done. You need to provide SQL for additional table attributes, and then you can retrieve that information from the schema metadata. You can use something similar for additional column metadata.

Unfortunately, [Microsoft has decided not to make table and column remarks available in the metadata](https://github.com/microsoft/mssql-jdbc/issues/646) (as defined in the JDBC specification), so you will have to make do with this workaround.

**Comment by sualeh** [comment]
Helpful SQL:

```sql
SELECT
  DB_NAME() AS TABLE_CATALOG,
  S.NAME AS TABLE_SCHEMA,
  O.NAME AS TABLE_NAME,
  EP.VALUE AS REMARKS
FROM 
  SYS.EXTENDED_PROPERTIES EP
  LEFT JOIN SYS.ALL_OBJECTS O 
    ON EP.MAJOR_ID = O.OBJECT_ID
  LEFT JOIN SYS.SCHEMAS S 
    ON O.SCHEMA_ID = S.SCHEMA_ID
WHERE
  EP.NAME = 'MS_Description'
ORDER BY
  TABLE_SCHEMA,
  TABLE_NAME
```

and 

```sql
SELECT
  DB_NAME() AS TABLE_CATALOG,
  S.NAME AS TABLE_SCHEMA,
  O.NAME AS TABLE_NAME,
  C.NAME AS COLUMN_NAME,
  EP.VALUE AS REMARKS
FROM 
  SYS.EXTENDED_PROPERTIES EP
  LEFT JOIN SYS.ALL_OBJECTS O 
    ON EP.MAJOR_ID = O.OBJECT_ID
  LEFT JOIN SYS.SCHEMAS S 
    ON O.SCHEMA_ID = S.SCHEMA_ID
  LEFT JOIN SYS.COLUMNS AS C 
    ON EP.MAJOR_ID = C.OBJECT_ID 
      AND EP.MINOR_ID = C.COLUMN_ID
WHERE
  EP.NAME = 'MS_Description'
  AND EP.MINOR_ID > 0
ORDER BY
  TABLE_SCHEMA,
  TABLE_NAME
```
