### ISSUE TITLE
Latest release download 16.5.0 

### ISSUE THREAD

**Issue by eitan-rosenberg** [schemacrawler/SchemaCrawler#296]
I have a maven project that use SchemaCrawler .

When I use:

	<dependency>
			<groupId>us.fatehi</groupId>
			<artifactId>schemacrawler</artifactId>
			<version>16.5.0</version>
	</dependency>
	
The content in the local repository is missing the schemacrawler-16.5.0.jar  

Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----        3/12/2020   8:54 AM            100 m2e-lastUpdated.properties
-a----        3/12/2020   8:54 AM        1400480 schemacrawler-16.5.0-javadoc.jar
-a----        3/12/2020   8:54 AM             40 schemacrawler-16.5.0-javadoc.jar.sha1
-a----        3/12/2020   8:54 AM           6184 schemacrawler-16.5.0.pom
-a----        3/12/2020   8:54 AM             40 schemacrawler-16.5.0.pom.sha1
-a----        3/12/2020   8:54 AM            220 _remote.repositories

**Comment by sualeh** [comment]
Please try 16.5.1.

**Comment by sualeh** [comment]
@eitan-rosenberg  - looking into it.

**Comment by eitan-rosenberg** [comment]
Thanks !!!

**Comment by eitan-rosenberg** [comment]
Works like a charm !!!
Thanks again and be healthy.
