### ISSUE TITLE
Cant create diagramm

### ISSUE THREAD

**Issue by ThisGuenter** [schemacrawler/SchemaCrawler#297]
[log.txt](https://github.com/schemacrawler/SchemaCrawler/files/4358867/log.txt)
# Issue

> Please explain the issue briefly
I try to generate a diagramm, but i get no diagramm-file
Graphviz is installed and in PATH
# Environment
SchemaCrawler 16.5.2
Windows 10 10.0
Oracle Corporation Java HotSpot(TM) 64-Bit Server VM 1.8.0_172-b11
# Commandline
schemacrawler --command=schema --info-level=default --server=oracle --database=<db> --user=<user> --password=<user> --schemas=<user> --table_types=table --portablenames=true --outputformat=svg --outputfile=user_graph.svg

**Comment by sualeh** [comment]
@ThisGuenter   - please run `schemacrawler --version`. Do you previously install an older version of SchemaCrawler using Chcolatey?

**Comment by ThisGuenter** [comment]
SchemaCrawler 16.5.2
Database schema discovery and comprehension tool
Copyright (c) 2000-2020, Sualeh Fatehi <sualeh@hotmail.com>.

System Information:
Windows 10 10.0
Oracle Corporation Java HotSpot(TM) 64-Bit Server VM 1.8.0_172-b11

**Comment by sualeh** [comment]
@ThisGuenter - SchemaCrawler 16.5.2 will complain about some of the invalid command-line arguments that you have above. Let me try to reproduce the issue, so I can work with you.

**Comment by sualeh** [comment]
@ThisGuenter - as a next step, please could you try:

`
.\schemacrawler.cmd  --command=schema --info-level=standard --server=oracle -database=<database> --user=<USER> --password=<USER> --schemas=<USER> --table-types=table --portable-names=true --output-file=CROWD_graph.jpg
`

Notes on changes:
- --table-types (dash not underscore)
- No need for --outputformat - this is inferred from the output file names
- --outputfile needs a dash - --output-file though you can simply use -o

**Comment by ThisGuenter** [comment]
[log.txt](https://github.com/schemacrawler/SchemaCrawler/files/4385631/log.txt)
Seems to be related to my Graphviz installation/configuration, could you advice me how to set the environment-variables in windows 10(currently i have included the bin and lib directory of Graphviz to my PATH) -  i'm using Graphviz v2.38 - Thanks

**Comment by sualeh** [comment]
@ThisGuenter - please try using the PNG format, and let me know if that is better.

`.\schemacrawler.cmd --command=schema --info-level=standard --server=oracle -database=<database> --user=<USER> --password=<USER> --schemas=<USER> --table-types=table --portable-names=true --output-file=CROWD_graph.png`

**Comment by ThisGuenter** [comment]
Still no success
If i generate a graph.dot-file and issue
dot -T png -o D:\tools\schemacrawler-16.5.2-distribution\_schemacrawler\graph.png graph.dot
I get:
dot: graph is too large for cairo-renderer bitmaps. Scaling by 0.194867 to fit
dot: failure to create cairo surface: out of memory

**Comment by ThisGuenter** [comment]
For smaller schemas i'm able to create diagrams

**Comment by sualeh** [comment]
Sorry, @ThisGuenter - this is something I cannot help you with. This is a limitation of Graphviz itself. You may have to create some smaller diagrams.

**Comment by ThisGuenter** [comment]
Thanks for your effort
