### ISSUE TITLE
Render indexes in diagrams

### ISSUE THREAD

**Issue by PetrKaleta** [schemacrawler/SchemaCrawler#309]
It will be really nice if column indexes can be rendered in diagrams also.

**Comment by sualeh** [comment]
@PetrKaleta  - do you have some examples of what this could look like - or what you would like it to look like?

**Comment by sualeh** [comment]
I am still chewing on this one - I took a look at [How are indexes represented in an ERD?](https://dba.stackexchange.com/questions/23610/how-are-indexes-represented-in-an-erd) to see what people think.

**Comment by sualeh** [comment]
@PetrKaleta - SchemaCrawler now allows you to export your database schema metadata into [Holistics DBML](https://www.dbml.org/home/), which can be used to create diagrams online with [dbdiagram.io](https://dbdiagram.io/home). dbdiagram.io show indexes on the schema diagram. Please use this solution if you want to see indexes on your database diagram. Please see [the SchemaCrawler diagramming page](https://www.schemacrawler.com/diagramming.html) for more information on how to generate DBML.

**Comment by sualeh** [comment]
@PetrKaleta - I have implemented indexes in diagrams. Please use the latest SchemaCrawler release.
