### ISSUE TITLE
DB2 - Schemacrawler Misses Unique Indexes for Named PK Constraints

### ISSUE THREAD

**Issue by lhankins** [schemacrawler/SchemaCrawler#312]
# DB2 - Schemacrawler Misses Indexes that share the PK Constraint Name

DB2 will transparently create a unique index for each primary key. 
 * If the PK constraint is not explicitly named, then DB2 will assign it a system generated name, and the unique index will get a different system generated name.
 * If you DO name the PK constraint, then DB2 will use the same PK constraint name for the name of the unique index.  **BUG:** In this scenario - SchemaCrawler misses the unique index.

Here's a simple example with two tables
 * Foo names its PK constraint
 * Bar does not name the PK constraint

```sql
--- named PK constraint
create table FOO
(
   FOO_ID bigint generated by default as identity,
   NAME   varchar(128) not null,
   constraint FOO_PK primary key (FOO_ID)
);

--- unnamed PK constraint
create table BAR
(
   BAR_ID bigint generated by default as identity,
   NAME   varchar(128) not null,
   primary key (BAR_ID)
);
```
Here is the corresponding SqlCrawler output (note that Foo's unique index is missing).
```text
System Information
========================================================================

generated by                              SchemaCrawler 16.6.1
generated on                              2020-04-25 21:07:34
database version                          DB2/NT64 SQL11012
driver version                            IBM Data Server Driver for JDBC and SQLJ 4.19.77


Tables
========================================================================


FOO                                                              [table]
------------------------------------------------------------------------
  FOO_ID                            BIGINT NOT NULL
                                    auto-incremented
                                    generated
  NAME                              VARCHAR(128) NOT NULL

Primary Key

FOO_PK                                                     [primary key]
  FOO_ID                            ascending



BAR                                                              [table]
------------------------------------------------------------------------
  BAR_ID                            BIGINT NOT NULL
                                    auto-incremented
                                    generated
  NAME                              VARCHAR(128) NOT NULL

Primary Key

SQL200425210709510                                         [primary key]
  BAR_ID                            ascending

Indexes

SQL200425210709460                                        [unique index]
  BAR_ID                            ascending

```

In SQL, you can verify that the unique index is actually present: 
```sql
select INDNAME, OWNERTYPE, TABNAME, COLNAMES, UNIQUERULE
   from SYSCAT.indexes
   where TABNAME in ('FOO', 'BAR');
```
results:

INDNAME | OWNERTYPE | TABNAME | COLNAMES | UNIQUERULE |
----------| -------------| -------------| -------------| -------------
SQL200425210709460 | U | BAR | +BAR\_ID | P |
FOO\_PK | U | FOO | +FOO\_ID | P |

# Environment

Java: 
```
$ java -version
openjdk version "11.0.7" 2020-04-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.7+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.7+10, mixed mode)
```
Schemacrawler / DB2: 
```
generated by                              SchemaCrawler 16.6.1
generated on                              2020-04-25 21:07:34
database version                          DB2/NT64 SQL11012
driver version                            IBM Data Server Driver for JDBC and SQLJ 4.19.77
```
JDBC Driver: 
```
$ java -cp lib/db2-10.5/db2jcc4.jar com.ibm.db2.jcc.DB2Jcc -version
IBM Data Server Driver for JDBC and SQLJ 4.19.77
```

DB2 Version: 
| SERVICE\_LEVEL | FIXPACK\_NUM |
| :--- | :--- |
| DB2 v11.1.2020.1393 | 2 |

OS: 
 * SchemaCrawler running on Ubuntu 19.10 w. OpenJDK 11.0.7
 * DB2 running on Windows Server 2008R2 (64-bit)

**Comment by sualeh** [comment]
@lhankins Lance - thanks for the detailed description of the issue. I can fix it quite easily, but I will need to see if the fix has any impact on other database systems.

**Comment by sualeh** [comment]
@lhankins Lance, please use SchemaCrawler 16.7.1. Please let me know how this works for you.

**Comment by lhankins** [comment]
@sualeh - just tried it out and I can confirm that 16.7.1 fixes this issue. Thanks for the quick turnaround!
