### ISSUE TITLE
Bug in LimitOptionsBuilder on using an empty list for routineTypes(...) variable (fix enclosed in issue description)

### ISSUE THREAD

**Issue by shantstepanian** [schemacrawler/SchemaCrawler#333]
### To reproduce the issue:

 LimitOptionsBuilder.builder().routineTypes(new ArrayList<>())

I need to do this for Sybase ASE and SQL Server as the routine types scanning doesn't seem to work). Equivalent calls work prior to version 16.9.1

### The fix

In LimitOptionsBuilder.toOptions(), on 175, replace this line:

 .map(types -> EnumSet.copyOf(types))

with

 .map(types -> types.isEmpty() ? EnumSet.noneOf(RoutineType.class) : EnumSet.copyOf(types))

EnumSet.copyOf throws an exception when passed an empty list. Hence you need to specify "noneOf" instead

**Comment by sualeh** [comment]
Thanks, @shantstepanian - I will get this fixed. In the meantime, you can use `SchemaInfoLevelBuilder.setRetrieveRoutines` to turn of retrieval of routines.

**Comment by sualeh** [comment]
PS: Routine retrieval for Microsoft SQL Server is working - please take a look at [the Microsoft SQL Server test results](https://github.com/schemacrawler/SchemaCrawler/blob/master/schemacrawler-sqlserver/src/test/resources/testSQLServerWithConnection.8.txt). Please could you clarify the issues that you are seeing, and open a new issue if needed?

**Comment by sualeh** [comment]
@shantstepanian - please use SchemaCrawler 16.9.2
