### ISSUE TITLE
Timestamp Timezone

### ISSUE THREAD

**Issue by afrancht** [schemacrawler/SchemaCrawler#334]
Hi Sualeh,

I was wondering if the `crawl-timestamp` property has any specific timezone or if it's the local timezone? I saw that it was a `iso8601` but no other indication of timezone.

**Comment by sualeh** [comment]
@afrancht - you may be one of the few people using this, since nobody has pointed out this issue before. I will change the API to use an `Instant` behind the scenes, so that it outputs a date and time with the timezone in which the code runs.

**Comment by afrancht** [comment]
Thank you so much! Have a great day.

**Comment by sualeh** [comment]
@afrancht - please use SchemaCrawler 16.9.2 - timezone is in UTC, and you also have an `Instant` if you want to convert to something else
