### ISSUE TITLE
Diagram Example Error

### ISSUE THREAD

**Issue by GPoloVera** [schemacrawler/SchemaCrawler#337]
# Diagram Example Error

> This error I have found it in my local computer but also in Katacoda last course "SchemaCrawler - Examples" (https://www.katacoda.com/schemacrawler/courses/schemacrawler/schemacrawler-examples). If you follow the steps that the course suggest and when you get to the step 6 when you have to run "diagram.sh" script 
The error it shows is:
SchemaCrawler 16.9.1

Error: schemacrawler.schemacrawler.SchemaCrawlerOptionsBuilder.withSchemaInfoLevel(Lschemacrawler/schemacrawler/SchemaInfoLevel;)Lschemacrawler/schemacrawler/SchemaCrawlerOptionsBuilder;

Re-run SchemaCrawler with just the
-h
option for help

# Environment
Katacoda course container

**Comment by sualeh** [comment]
@GPoloVera - thanks for reporting this issue. I have reverted the Katacoda tutorials to an older version of SchemaCrawler, and diagramming now works. (Some other examples do not work.) I will fix the underlying issue in the next SchemaCrawler version.

**Comment by sualeh** [comment]
@GPoloVera - I have refreshed Katacoda with the lates version of SchemaCrawler, and the issues you were seeing are fixed.

**Comment by GPoloVera** [comment]
@sualeh - Thank you very much!
I will install the latest version locally too to test it in a MariaDB DBase.
