### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by JonhSilver** [schemacrawler/SchemaCrawler#340]
Very bad manuals, a huge one and about nothing (not useful info), no info and examples how to run to get result, links is broken, examples links redirect to install files.

`--server=sqlserver --host=localhost --port=1433 --database=eur --schemas=eur.dbo --user=sa --password=1234  --info-level=standard --command=schema --table-types=TABLE`
only return list of tables and propetries

`--server=sqlserver --host=localhost --port=1433 --database=eur --schemas=eur.dbo --user=sa --password=1234  --info-level=standard --command=schema --table-types=TABLE --outputformat=png --outputfile=graph.png ` 

return same result

where file must be saved?
how to create Graphviz schema?

**Comment by sualeh** [comment]
@JonhSilver - that is in interesting way to ask for help - by starting out in a denigrating way. 

Please get command-line help, by running SchemaCrawler with the `-h` option. You will find that the correct command-line arguments are `--output-file=graph.png` (notice the extra dash). You do not need `--output-format=png` (again, extra dash) if the output file name ends in ".png".

I suggest that you try the [Katacoda examples](https://www.katacoda.com/schemacrawler), which walk you through how to create the diagrams. Meanwhile, I will change the one place in the documentation that has incorrect information. If you have found broken links, please report each one separately,

SchemaCrawler is free software. If you are upset that you are not getting your money's worth, please return it for a full refund. On the other hand, [consulting is available](https://www.schemacrawler.com/consulting.html).

**Comment by JonhSilver** [comment]
I got just unreadable table list png

![image](https://user-images.githubusercontent.com/24619483/86721516-bb340a80-c02e-11ea-8f6d-b503407d1fac.png)

no relations shema, as no FK keys exist in tables, --weak-associations=true result the same

**Comment by sualeh** [comment]
@JonhSilver - please use the instructions on [the support page](https://www.schemacrawler.com/consulting.html) to provided more details.
