### ISSUE TITLE
Schemacralwer 16.9.2 exception serializing private table alias objects in db2

### ISSUE THREAD

**Issue by imavo** [schemacrawler/SchemaCrawler#346]
schemacrawler 16.9.2 throws exception on serialize to json for a table ALIAS in Db2.

This is easy to recreate with the sample database.

Using the jdbc driver that comes with schemacrawler, on ubuntu 16.04.04 with local Db2 v11.1 database.

I ran the command below:

`./schemacrawler.sh --server=db2 --host=ip4_address --port=50000 --database=sample --schemas=DB2INST8 --user="db2inst8" --password=whatever --info-level=standard -c serialize --output-format json --log-level=ALL
`

When it tries to process a private table ALIAS  (example: `create alias user1.newname for user1.oldname` )
then it will throw an exception like the one shown below when processing user1.newname.

If I drop the private table aliases,  schemacrawler completes successfully and shows the json output.

My expectation is that schemacrawler should understand the alias objects and handle them correctly, that is to say, it should check syscat.tables.type and when it is 'A' (alias) then simply report the alias definition (by using syscat.tables.base_tabschema and syscat.tables.base_tabname). But it fatals on the first private table alias that it encounters.

Example of the exception (db2inst8.DEPT is a private table alias for real table db2inst8.DEPARTMENT).

> SEVERE: Cannot execute SchemaCrawler command
> 
> Caused by: schemacrawler.schemacrawler.SchemaCrawlerException: Could not serialize catalog: Complete metadata has not been loaded for <DB2INST8.DEPT.ADMRDEPT> (through reference chain: schemacrawler.tools.integration.serialize.JsonSerializedCatalog["catalog"]->schemacrawler.cra      wl.MutableCatalog["tables"]->java.util.ArrayList[6]->schemacrawler.crawl.MutableTable["foreign-keys"]->java.util.ArrayList[0]->schemacrawler.crawl.MutableForeignKey["column-references"]->java.util.ArrayList[1]->schemacrawler.crawl.MutableForeignKeyColumnReference["foreign-key-column"]->schemacrawler.crawl.ColumnPartial["auto-incremented"])
> 30644     at schemacrawler.tools.integration.serialize.BaseJacksonSerializedCatalog.save(BaseJacksonSerializedCatalog.java:119)
> 30645     at schemacrawler.tools.integration.serialize.SerializationCommand.execute(SerializationCommand.java:105)
> 30646     at schemacrawler.tools.executable.BaseCommandChain.executeChain(BaseCommandChain.java:134)
> 30647     at schemacrawler.tools.executable.CommandDaisyChain.execute(CommandDaisyChain.java:115)
> 30648     at schemacrawler.tools.executable.SchemaCrawlerExecutable.execute(SchemaCrawlerExecutable.java:159)
> 30649     at schemacrawler.tools.commandline.command.ExecuteCommand.run(ExecuteCommand.java:166)
> 30650     ... 3 more
>

**Comment by sualeh** [comment]
@imavo - please use SchemaCrawler v16.9.3, and let me know if this fixes your issue.
