### ISSUE TITLE
SchemaCrawler reports all MariaDB database on the command `schema`

### ISSUE THREAD

**Issue by stndn** [schemacrawler/SchemaCrawler#348]
# Bug Report

When running the script to extract the schema for particular database on MariaDB, SchemaCrawler will return all the database on the server. The expected output is that it will only show information for the database defined in the command line options.

For example, the following command will extract and display all database inside `172.31.0.4` in the output instead of just `sc_test`:
`./schemacrawler.sh --url="jdbc:mariadb://172.31.0.4:3306/sc_test?user=root&password=root"  --schema="sc_test"  --info-level=standard -c=schema --output-format=html    -o=/tmp/sc_test3.html --log-level=ALL > /tmp/mariadb-schema-bug.log 2>&1
`

For our test purpose, we created a new database `sc_test` with the following contents:
```
CREATE TABLE `teams` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(30) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `name` (`name`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 ;

CREATE TABLE `users` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `username` varchar(50) NOT NULL,
  `password` varchar(100) DEFAULT NULL,
  `team_id` int(11) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `username` (`username`),
  KEY `team_id` (`team_id`),
  CONSTRAINT `users_ibfk_1` FOREIGN KEY (`team_id`) REFERENCES `teams` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 ;
```

The resulting HTML will include information from other database, such as `matomo` and `sc_test_2` as shown in screenshot below:

![sc-bug-all-schemas-included](https://user-images.githubusercontent.com/790211/88082811-db2e0700-cbb4-11ea-9dd5-11d5075a37e9.png)

Steps to reproduce:
* Run the command to crawl the database, specifying an existing database in the `database` parameter
* View the resulting output

**Environment**

Specify the
* version of SchemaCrawler that you are using: *SchemaCrawler 16.9.2*
* version of Java that you are using:
```
openjdk version "11.0.7" 2020-04-14
OpenJDK Runtime Environment (build 11.0.7+10-post-Ubuntu-2ubuntu218.04)
OpenJDK 64-Bit Server VM (build 11.0.7+10-post-Ubuntu-2ubuntu218.04, mixed mode, sharing)
```
* operating system and version that you are using: *Ubuntu 18.04.4*
* relational database and version that you are using: *MariaDB 10.4.12-MariaDB-1:10.4.12+maria~bionic*
* JDBC driver and version that you are using: *mariadb-java-client-2.6.1.jar*

Error log is attached: [mariadb-schema-bug.log.zip](https://github.com/schemacrawler/SchemaCrawler/files/4955106/mariadb-schema-bug.log.zip).

Thank you.

**Comment by sualeh** [comment]
@stndn - Sutandiono, this is expected behavior, and there are a couple of ways to handle this issue.
1. Do not use the root user - use a database user that only has metadata permissions to the database that you are interested in. This is the preferred method.
2. Use the `--schemas` command-line option to limit the schemas. (You have a spelling mistake in the command-line option.)

**Comment by stndn** [comment]
Hi, @sualeh . Noted, and thanks for pointing the typo on the `--schemas`.

Tried it just now and it works.

And noted on the first suggestion on not using the `root` user. This was only because I didn't create the proper user for this bug report. On other usage, the users are specific to the schema we are researching on.


Thanks again for the quick response.
