### ISSUE TITLE
Icons for primary/foreign keys

### ISSUE THREAD

**Issue by allan-shoup** [schemacrawler/SchemaCrawler#358]
Just a suggestion for something to think about. [SchemaSpy](http://schemaspy.org/) uses two different flavors of a key icon to display next to primary key and foreign key columns ([sample here](http://schemaspy.org/sample/relationships.html)). I thought that was a visually clean way to communicate that info. Offering that as a suggestion to incorporate into SchemaCrawler.

![image](https://user-images.githubusercontent.com/7842213/90981718-45c1c200-e528-11ea-898d-777ffef1fd40.png)

**Comment by sualeh** [comment]
@allan-shoup - I have decided not to implement this functionality. I have added in the ability for SchemaCrawler to output graph data for [mermaid](https://mermaid-js.github.io/mermaid/#/entityRelationshipDiagram) and [dbdiagram.io](https://dbdiagram.io/home) - see the [diagramming page on the SchemaCrawler](https://www.schemacrawler.com/diagramming.html) website. Some of these tools show icons for keys. So, as a workaround, you can use SchemaCrawler to output these other diagramming formats.
