### ISSUE TITLE
retrieve_column_data_types Property Not Working?

### ISSUE THREAD

**Issue by allan-shoup** [schemacrawler/SchemaCrawler#361]
I might not understand what this property is supposed to do:
`schemacrawler.schema_info_level.retrieve_column_data_types=false`

I expected if I have that set, the generated diagram would show the column names but not the column data types. When I set the above property, I could not tell any difference in the diagram output.

**Comment by sualeh** [comment]
@allan-shoup - there was no intention to have an option to not show column data types in SchemaCrawler output. However, you have pointed out a bug, where certain published configuration options do not have any effect. I will remove those options from the example configuration file.
