### ISSUE TITLE
v16.10.1 - Unable to execute defined query

### ISSUE THREAD

**Issue by ThisGuenter** [schemacrawler/SchemaCrawler#372]
# Bug Report

**Issue**
Afer upgrade to newest release i get following error:
Error: Unknown command <query>

Query is defined in schemacrawler.config.properties with v16.9.5 everything works fine 

**Environment**

Specify the
* version of SchemaCrawler that you are using: 16.10.1
* version of Java that you are using: 1.8.0_172 
* operating system and version that you are using: Windows 10
* relational database and version that you are using: 12cR2
* JDBC driver and version that you are using

     [java] Sep. 23, 2020 9:10:49 VORM. schemacrawler.tools.commandline.utility.CommandLineLoggingUtility logFullStackTrace
     [java] SCHWERWIEGEND: Cannot execute SchemaCrawler command
     [java] picocli.CommandLine$ExecutionException: Cannot execute SchemaCrawler command
     [java]     at schemacrawler.tools.commandline.command.ExecuteCommand.run(ExecuteCommand.java:132)
     [java]     at schemacrawler.tools.commandline.SchemaCrawlerCommandLine.executeCommandLine(SchemaCrawlerCommandLine.java:107)
     [java]     at schemacrawler.tools.commandline.SchemaCrawlerCommandLine.execute(SchemaCrawlerCommandLine.java:67)
     [java]     at schemacrawler.Main.main(Main.java:73)
     [java] Caused by: schemacrawler.schemacrawler.SchemaCrawlerException: Unknown command <query.edn,query.tls,query.user_sequences,call.se
t_transform_sqlterminator_false,call.set_transform_param_constraints_false,call.set_transform_param_emit_schema_false,call.set_transform_par
am_storage_false,query.user_tables,call.set_transform_param_partitioning_false,query.user_indexes,query.user_constraints,query.user_ref_cons
traints,query.user_objects,query.user_tab_privs,query.user_tab_comments,query.user_tab_col_comments,query.user_view_col_comments>
     [java]     at schemacrawler.tools.executable.CommandRegistry.findSupportedCommands(CommandRegistry.java:165)
     [java]     at schemacrawler.tools.executable.CommandRegistry.configureNewCommand(CommandRegistry.java:126)
     [java]     at schemacrawler.tools.executable.SchemaCrawlerExecutable.loadCommand(SchemaCrawlerExecutable.java:196)
     [java]     at schemacrawler.tools.executable.SchemaCrawlerExecutable.execute(SchemaCrawlerExecutable.java:89)
     [java]     at schemacrawler.tools.commandline.command.ExecuteCommand.run(ExecuteCommand.java:130)
     [java]     ... 3 more
     [java]
     [java] SchemaCrawler 16.10.1

**Comment by sualeh** [comment]
@ThisGuenter - SchemaCrawler v16.10.1 removes the ability to provide comma-separated commands on the command-line. This is to make way for planned code reorganization in the future. You will need to use the JavaScript chain command to achieve what you need. I can help you through that if you email me.

**Comment by ThisGuenter** [comment]
Hi Sualeh,

thanks for offering your help.

I want to execute several queries - how to achieve this ?
If i try to add several commands with only one query i get following error:

SCHWERWIEGEND: option '--command' (<command>) should be specified only once
picocli.CommandLine$OverwrittenOptionException: option '--command' (<command>) should be specified only once

Regards Günter

This is my current setup with v16.9.5

                        <profile>
                                   <id>database.dump</id>
                                   <activation>
                                               <activeByDefault>false</activeByDefault>
                                   </activation>
                                   <build>
                                               <plugins>
                                                           <plugin>
                                                                       <groupId>org.apache.maven.plugins</groupId>
                                                                       <artifactId>maven-antrun-plugin</artifactId>
                                                                       <executions>
                                                                                  <execution>
                                                                                              <id>database-dump</id>
                                                                                              <phase>compile</phase>
                                                                                              <inherited>true</inherited>
                                                                                              <configuration>
                                                                                                          <target unless="skipDatabase">
                                                                                                                      <mkdir dir="${project.build.directory}/logs" />
                                                                                                                      <echo><![CDATA[+---------------------------------+]]></echo>
                                                                                                                      <echo><![CDATA[| Database Dump: ${dump_name}.dump.txt |]]></echo>
                                                                                                                      <echo><![CDATA[+---------------------------------+]]></echo>
                                                                                                                      <java failonerror="true" classname="${config.schemacrawler.classname}" fork="true">
                                                                                                                                 <classpath>
                                                                                                                                   <fileset dir="${project.build.directory}/schemacrawler">
                                                                                                                                             <include name="*.jar" />
                                                                                                                                   </fileset>
                                                                                                                                 </classpath>
                                                                                                                          <jvmarg value="-Djava.security.policy=${project.build.directory}/config/ojdbc.java.policy" />
                                                                                                                                 <arg value="--server=oracle" />
                                                                                                                                 <arg value="--host=${config.default.connection.host}" />
                                                                                                                                 <arg value="--port=${config.default.connection.port}" />
                                                                                                                                 <arg value="--database=${config.default.connection.service}" />
                                                                                                                                 <arg value="--user=${oltp.default.username}" />
                                                                                                                                 <arg value="--password=${oltp.default.password}" />
                                                                                                                                 <arg value="--schemas=${oltp.default.username}" />
                                                                                                                                  <arg value="--routines=" />
                                                                                                                                 <arg value="--sequences=" />
                                                                                                                                 <arg value="--tables=" />
                                                                                                                                 <arg value="--info-level=minimum" />
                                                                                                                                 <arg value="--output-format=text" />
                                                                                                                                 <arg value="--log-level=SEVERE" />
                                                                                                                                 <arg value="--command=query.edn,query.tls,query.user_sequences,call.set_transform_sqlterminator_false,call.set_transform_param_constraints_false,call.set_transform_param_emit_schema_false,call.set_transform_param_storage_false,query.user_tables,call.set_transform_param_partitioning_false,query.user_indexes,query.user_constraints,query.user_ref_constraints,query.user_objects,query.user_tab_privs,query.user_tab_comments,query.user_tab_col_comments,query.user_view_col_comments" />
                                                                                                                                 <arg value="--config-file=${project.build.directory}/config/schemacrawler.config.properties" />
                                                                                                                                 <arg value="--output-file=${project.build.directory}/logs/${dump_name}.dump.txt" />
                                                                                                                      </java>
                                                                                                                      <echo><![CDATA[+-------------------------------------+]]></echo>
                                                                                                                      <echo><![CDATA[| Database Dump end: ${dump_name}.dump.txt |]]></echo>
                                                                                                                      <echo><![CDATA[+-------------------------------------+]]></echo>
                                                                                                          </target>
                                                                                              </configuration>
                                                                                              <goals>
                                                                                                          <goal>run</goal>
                                                                                              </goals>
                                                                                  </execution>
                                                                       </executions>
                                                           </plugin>
                                               </plugins>
                                   </build>
                        </profile>

Von: Sualeh Fatehi [mailto:notifications@github.com]
Gesendet: Donnerstag, 24. September 2020 02:58
An: schemacrawler/SchemaCrawler <SchemaCrawler@noreply.github.com>
Cc: Guenter Leimbeck <guenter.leimbeck@payback.net>; Mention <mention@noreply.github.com>
Betreff: Re: [schemacrawler/SchemaCrawler] v16.10.1 - Unable to execute defined query (#372)


[WARNING] This message comes from an external organization. Be careful of embedded links.



@ThisGuenter<https://github.com/ThisGuenter> - SchemaCrawler v16.10.1 removes the ability to provide comma-separated commands on the command-line. This is to make way for planned code reorganization in the future. You will need to use the JavaScript chain command to achieve what you need. I can help you through that if you email me.

**Comment by sualeh** [comment]
@ThisGuenter - you will need to use the "chain" command. Please create a JavaScript file called "chain.js", with the following contents:

```javascript
var scCommands = function () {
	chain.addNext("query.edn", "text", "sql1.txt");
	chain.addNext("query.tls", "text", "sql2.txt");
	chain.addNext("query.user_sequences", "text", "sql3.txt");
	chain.addNext("call.set_transform_sqlterminator_false", "text", "sql4.txt");
	chain.addNext("call.set_transform_param_constraints_false", "text", "sql5.txt");
	chain.addNext("call.set_transform_param_emit_schema_false", "text", "sql6.txt");
	chain.addNext("call.set_transform_param_storage_false", "text", "sql7.txt");
	chain.addNext("query.user_tables", "text", "sql8.txt");
	chain.addNext("call.set_transform_param_partitioning_false", "text", "sql9.txt");
	chain.addNext("query.user_indexes", "text", "sql10.txt");
	chain.addNext("query.user_constraints", "text", "sql10.txt");
	chain.addNext("query.user_ref_constraints", "text", "sql11.txt");
	chain.addNext("query.user_objects", "text", "sql12.txt");
	chain.addNext("query.user_tab_privs", "text", "sql13.txt");
	chain.addNext("query.user_tab_comments", "text", "sql14.txt");
	chain.addNext("query.user_tab_col_comments", "text", "sql15.txt");
	chain.addNext("query.user_view_col_comments", "text", "sql16.txt");
	
    chain.execute();
};

scCommands();
```

Then, use the SchemaCrawler "chain" command with the following arguments:

```xml
<arg value="--command=chain" />
<arg value="--script=chain.js" />
```
If you need the output in a single file, you will need to use ant to concatenate the files.

**Comment by sualeh** [comment]
@ThisGuenter - on the other hand, if only one of your SQL statements is actually producing output, then put all of them into a single stored procedure called `SC_COMMAND`. Then, modify "schemacrawler.config.properties" to add a new SQL statement like this:

```
custom.command={call SC_COMMAND}
```

You can use this command in the same way:

```xml
<arg value="--command=custom.command" />
```

**Comment by sualeh** [comment]
Please let me know if either one of the approaches works for you.

**Comment by ThisGuenter** [comment]
[java] Sep. 28, 2020 7:55:07 VORM. schemacrawler.tools.commandline.utility.CommandLineLoggingUtility logFullStackTrace
[java] SCHWERWIEGEND: Cannot execute SchemaCrawler command
[java] picocli.CommandLine$ExecutionException: Cannot execute SchemaCrawler command
[java]     at schemacrawler.tools.commandline.command.ExecuteCommand.run(ExecuteCommand.java:132)
[java]     at schemacrawler.tools.commandline.SchemaCrawlerCommandLine.executeCommandLine(SchemaCrawlerCommandLine.java:107)
[java]     at schemacrawler.tools.commandline.SchemaCrawlerCommandLine.execute(SchemaCrawlerCommandLine.java:67)
[java]     at schemacrawler.Main.main(Main.java:73)
[java] Caused by: schemacrawler.schemacrawler.SchemaCrawlerException: Unknown command <chain>
[java]     at schemacrawler.tools.executable.CommandRegistry.findSupportedCommands(CommandRegistry.java:165)
[java]     at schemacrawler.tools.executable.CommandRegistry.configureNewCommand(CommandRegistry.java:126)
[java]     at schemacrawler.tools.executable.SchemaCrawlerExecutable.loadCommand(SchemaCrawlerExecutable.java:196)
[java]     at schemacrawler.tools.executable.SchemaCrawlerExecutable.execute(SchemaCrawlerExecutable.java:89)
[java]     at schemacrawler.tools.commandline.command.ExecuteCommand.run(ExecuteCommand.java:130)
[java]     ... 3 more
[java]
[java] SchemaCrawler 16.10.1
[java]
[java] Error: Unknown command <chain>

Von: Sualeh Fatehi [mailto:notifications@github.com]
Gesendet: Montag, 28. September 2020 00:44
An: schemacrawler/SchemaCrawler <SchemaCrawler@noreply.github.com>
Cc: Guenter Leimbeck <guenter.leimbeck@payback.net>; Mention <mention@noreply.github.com>
Betreff: Re: [schemacrawler/SchemaCrawler] v16.10.1 - Unable to execute defined query (#372)


[WARNING] This message comes from an external organization. Be careful of embedded links.



@ThisGuenter<https://github.com/ThisGuenter> - you will need to use the "chain" command. Please create a JavaScript file called "chain.js", with the following contents:

var scCommands = function () {

        chain.addNext("query.edn", "text", "sql1.txt");

        chain.addNext("query.tls", "text", "sql2.txt");

        chain.addNext("query.user_sequences", "text", "sql3.txt");

        chain.addNext("call.set_transform_sqlterminator_false", "text", "sql4.txt");

        chain.addNext("call.set_transform_param_constraints_false", "text", "sql5.txt");

        chain.addNext("call.set_transform_param_emit_schema_false", "text", "sql6.txt");

        chain.addNext("call.set_transform_param_storage_false", "text", "sql7.txt");

        chain.addNext("query.user_tables", "text", "sql8.txt");

        chain.addNext("call.set_transform_param_partitioning_false", "text", "sql9.txt");

        chain.addNext("query.user_indexes", "text", "sql10.txt");

        chain.addNext("query.user_constraints", "text", "sql10.txt");

        chain.addNext("query.user_ref_constraints", "text", "sql11.txt");

        chain.addNext("query.user_objects", "text", "sql12.txt");

        chain.addNext("query.user_tab_privs", "text", "sql13.txt");

        chain.addNext("query.user_tab_comments", "text", "sql14.txt");

        chain.addNext("query.user_tab_col_comments", "text", "sql15.txt");

        chain.addNext("query.user_view_col_comments", "text", "sql16.txt");



    chain.execute();

};



scCommands();

Then, use the SchemaCrawler "chain" command with the following arguments:

<arg value="--command=chain" />

<arg value="--script=chain.js" />

If you need the output in a single file, you will need to use ant to concatenate the files.

**Comment by sualeh** [comment]
@ThisGuenter - sorry - the command is `script`, not `chain`.

```xml
<arg value="--command=script" />
<arg value="--script=chain.js" />
```

**Comment by ThisGuenter** [comment]
> Please let me know if either one of the approaches works for you.

I got it to work with your script command suggestion, thanks for your help - Any sugestion what can cause the output of a query to be shown as "<binary>" instead of the columns ? I used a new version of  schemacrawler.config.properties with my old one it works, but i could not figure out the reason for the change.

**Comment by ThisGuenter** [comment]
Solved by using command=script
