### ISSUE TITLE
schemacrawler.graph.graphviz_opts option ignored for Viz.js

### ISSUE THREAD

**Issue by allan-shoup** [schemacrawler/SchemaCrawler#373]
When graphviz-java utilizes Viz.js (instead of GraphViz proper), the `schemacrawler.graph.graphviz_opts` option defined in the config file is ignored.

**Comment by sualeh** [comment]
@allan-shoup - I looked at the API, and it looks like you can set height, width, and dpi. Do you want to set any (or all) of those, or something else?

**Comment by allan-shoup** [comment]
Here's what I'm using it for:
`schemacrawler.graph.graphviz_opts=-Granksep=3`

**Comment by sualeh** [comment]
@allan-shoup - Please try to pass them as attributes - `schemacrawler.graph.graphviz.graph.ranksep=3`. I will try to reproduce as well.

**Comment by sualeh** [comment]
You may have to also set:
```
schemacrawler.graph.graphviz.graph.fontname=Helvetica
schemacrawler.graph.graphviz.graph.labeljust=r
schemacrawler.graph.graphviz.graph.rankdir=RL
schemacrawler.graph.graphviz.graph.ranksep=3
```

**Comment by allan-shoup** [comment]
Yes, that seems to work. I don't need `schemacrawler.graph.graphviz_opts` for my current use case. Thanks!
