### ISSUE TITLE
Ability to override remarks

### ISSUE THREAD

**Issue by ghostd** [schemacrawler/SchemaCrawler#395]
# New Feature Request

**Describe the solution you'd like**
I work on a legacy database with no clear documentations. I crawled the database with SchemaCrawler, but the DDL of my schema does not include any remarks. Adding a simple way to override the crawled metadata would allow to add some external informations. SchemaCrawler could read an external file (JSON? XML? properties? YAML? other?) where we can override metadata :
```json
{
  "tables": {
     "name": "my-table",
     "remark": "some external comment for the table",
     "columns": [
       {
         "name": "my-column",
         "remark": "some external comment for the column",
        }
     ]
  }
}
```
Questions about this approach:
* override only remarks?
* how to handle unknown tables/columns from the file? (error ? warning ?)

Does it make sense?

**Comment by sualeh** [comment]
@ghostd - Vincent - I will consider the idea. are you using the API or the command-line?

**Comment by ghostd** [comment]
I only tested the CLI.

**Comment by sualeh** [comment]
Ok, thanks. I was just thinking about how it could be done, and it would be much easier to do something like this if it was used from the API.

**Comment by sualeh** [comment]
Please use SchemaCrawler v16.12.1 - see the [documentation](https://www.schemacrawler.com/attributes.html).

**Comment by ghostd** [comment]
@sualeh  I tried, and it works for me, thank you!
