### ISSUE TITLE
Add support for mermaid export

### ISSUE THREAD

**Issue by avidenic** [schemacrawler/SchemaCrawler#397]
# Mermaid support

Hi, this is a great project. I've just started using it, so I can automatically create ERD each time a feature is merged for the purpose of documenting the DB. It works really really well.

**Describe the solution you'd like**
When calling schemacrawler.sh I'd like to have an option to specify something like `--output-format=mermaid`. The reason behind is, that we are using [GitLab which has mermaid support in their Wiki](https://docs.gitlab.com/ee/user/markdown.html#mermaid) and it would be great if we could export directly into the documentation not just link the the export results (`svg` in our case). 

**Describe alternatives you've considered**
I've used `--output-format=svg` and `--output-format=htmlx`.

**Additional context**
You can find mermaid documentation for ERD [here](https://mermaid-js.github.io/mermaid/#/entityRelationshipDiagram)

Let me know what you think. Thank you for your time!

**Comment by sualeh** [comment]
Yes, I have been considering this too, so thanks for the push. Mermaid is trying to push the purity of ER diagrams, while SchemaCrawler tries to represent the schema as closely as possible, so there may be some details lost. For example, SchemaCrawler shows a relationship line from a primary key column to a foreign key column, whereas Mermaid shows relationships between tables (or entities). That being said, it is still a good idea for SchemaCrawler to support Mermaid syntax. Stay tuned.

**Comment by avidenic** [comment]
Thank you for looking at this. IMHO anyone who uses Mermaid, accepts these drawbacks.

**Comment by sualeh** [comment]
@avidenic - I ended up creating a [Python script](https://gitlab.com/sualeh/schemacrawler-action-usage-example/-/blob/main/mermaid.py) that plugs into SchemaCrawler to generate mermaid diagrams. Please take a look at the script. Please take a look at the [GitLab sample project](https://gitlab.com/sualeh/schemacrawler-action-usage-example) which generates the mermaid diagram too.

**Comment by sualeh** [comment]
@avidenic - did that work for you?

**Comment by avidenic** [comment]
@sualeh I'll take a look and get back to you. Tnx for your work!

**Comment by adriens** [comment]
@sualeh , will you make a Dev.to post to showcase how mermaid export can be achieved ?

**Comment by sualeh** [comment]
@adriens - done on Feb 12. 😄 [How to Generate Mermaid Diagrams for Your Database](https://dev.to/sualeh/how-to-generate-mermaid-diagrams-for-your-database-33bn)

**Comment by avidenic** [comment]
This is insanely awesome! @sualeh much appreciated!

**Comment by sualeh** [comment]
@avidenic - glad I could help! Also take a look at https://gitlab.com/sualeh/schemacrawler-action-usage-example to see how you can use this functionality. Also take a look at [How to Generate dbdiagram.io Diagrams for Your Database](https://dev.to/sualeh/how-to-generate-dbdiagram-io-diagrams-for-your-database-431l).
