### ISSUE TITLE
provide the content of `schemacrawler --help` as online documentation and link to it from the FAQ

### ISSUE THREAD

**Issue by aisbergde** [schemacrawler/SchemaCrawler#409]
# New Feature Request

I can't find in the weg the documentation of all commands and options, it looks like the only way to get them is  
`schemacrawler --help`

but it is hard to use, hard to read and hard to copy content from the console to a place where it is required.

**Describe the solution you'd like**
Please provide this content also in the web and place a link from here `https://www.schemacrawler.com/faq.html#commands` to this documentation

**Describe alternatives you've considered**
Maybe I need to print the content of the --help into a file to access it. But if this exists in the programs output then I think it exists somewhere in the code. Maybe only the link should be added to find this documentation.

**Comment by sualeh** [comment]
@aisbergde - SchemaCrawler help is interactive. If you want to use `schemacrawler --help`, the best way is via [the Katacoda scenarios](https://www.katacoda.com/schemacrawler).

**Comment by aisbergde** [comment]
This is a bit unusual for typical Windows users who are used to clicking around instead of looking for documentation in consoles. Then I guess we non-console users have to redirect ourselves the contents of the console into a text file to be able to open it with a text editor (with search and navigation).

I was hoping that maybe this already exists somewhere in the source code of the program, and then I would only need to open that file, and it would always have the current state if I cloned the repository.

**Comment by aisbergde** [comment]
I found the file I was looking for:
"D:\Repos\GitHub\schemacrawler\SchemaCrawler\schemacrawler-commandline\src\test\resources\commandline_help_output\help.stdout.txt"
