### ISSUE TITLE
mssql - whatever I try, I always get only some tables and views from different databases, --database has no effect

### ISSUE THREAD

**Issue by aisbergde** [schemacrawler/SchemaCrawler#410]
# Bug Report

**Issue**

I try to use SchemaCrawler on my local mssql databases.

The first problems were related to connecting me to the right instance. The  --host  parameter does not work as expected.
 `--host=localhost\sql2019` or `--host=localhost` both connect to localhost. I only get the connection with `localhost\sql2019` after finding out and specifying the port of this instance.

The parameter `--database` has no effect. Whatever I try, I always get the same list of any tables or views from different databases. I have not yet succeeded in listing all objects of a concrete database.

I have no idea on what principle exactly these tables and views are displayed.

For example

```
System Information
========================================================================

generated by                              SchemaCrawler 16.12.1
generated on                              2021-02-23 10:07:13.119



Tables
========================================================================

DataHandwerk_01.dbo.sysdiagrams                                  [table]
dhw_master.dbo.__RefactorLog                                     [table]
dhw_PerformanceAnalytics.dbo.__RefactorLog                       [table]
dhw_self.dbo.__RefactorLog                                       [table]
dhw_self.dbo.sysdiagrams                                         [table]
"dhw_WideWorldImporters-test".dbo.__RefactorLog                  [table]
dwh_AdventureWorks2017.dbo.AWBuildVersion                        [table]
dwh_AdventureWorks2017.dbo.DatabaseLog                           [table]
dwh_AdventureWorks2017.dbo.ErrorLog                              [table]
EventAnalytics.dbo.sysssislog                                    [table]
"mssql-development-accelerator".dbo.__RefactorLog                [table]
"mssql-development-accelerator".dbo.sysdiagrams                  [table]
"mssql-development-accelerator".dbo.temp01                       [table]
"mssql-development-accelerator".dbo.test01                        [view]
"mssql-development-accelerator".dbo.test01_T                     [table]
"mssql-development-accelerator".dbo.test01_T_Hist                [table]
"mssql-development-accelerator".dbo.test02                        [view]
"mssql-development-accelerator".dbo.test08_T                     [table]
"mssql-development-accelerator".dbo.test08_T_Hist                [table]
repo_AdventureWorks2017.dbo.__RefactorLog                        [table]
repo_DemoSAP.dbo.__RefactorLog                                   [table]
repo_EventAnalytics.dbo.__RefactorLog                            [table]
repo_leer_02.dbo.__RefactorLog                                   [table]
repo_leer_03.dbo.__RefactorLog                                   [table]
repo_leer_04.dbo.__RefactorLog                                   [table]
repo_leer_20200923.dbo.__RefactorLog                             [table]
repo_leer_20201010.dbo.__RefactorLog                             [table]
repo_leer_20201012.dbo.__RefactorLog                             [table]
"repo_leer_2020-12-10".dbo.__RefactorLog                         [table]
repo_PerformanceAnalytics.dbo.__RefactorLog                      [table]
repo_RepoExtension.dbo.__RefactorLog                             [table]
repo_SchemaCompare.dbo.__RefactorLog                             [table]
repo_SchemaCompare_AdventureWorks2017.dbo.__RefactorLog          [table]
repo_TemplateAisbergDe.dbo.__RefactorLog                         [table]
repo_wuerth_logistics.dbo.__RefactorLog                          [table]
SchemaCompare_AdventureWorks2017.dbo.sysssislog                  [table]
"WideWorldImporters-test".dbo.Table_1                            [table]
"WideWorldImporters-test".dbo.Table_2                            [table]
"WideWorldImporters-test".dbo.Table_3                            [table]
"WideWorldImporters-test".dbo.view_1                              [view]
"WideWorldImporters-test".dbo.view_1_T                           [table]
"WideWorldImporters-test".dbo.view_1_T_hist                      [table]
"WideWorldImporters-test".dbo.view_2                              [view]
"WideWorldImporters-test".dbo.view_3_distinct                     [view]
"WideWorldImporters-test".dbo.view_4                              [view]
"WideWorldImporters-test".dbo.view_5                              [view]
"WideWorldImporters-test".dbo.view_6                              [view]
"WideWorldImporters-test".dbo.view_7                              [view]
"WideWorldImporters-test".dbo.view_8                              [view]
```

Please explain the issue briefly
* Provide the steps that you took to reproduce the issue
  - I installed SchemaCrawler using chocolatey.org
  - I did not find how to use integrated security with mssql
  - I created a sql user and granted several rights

* Provide any steps that you took to solve the issue
  * I tried to set different databases per parameter
* Zip and attach the SchemaCrawler debug logs, which can be obtained by running SchemaCrawler with an additional `-loglevel=ALL` on the command-line argument

**Environment**

Specify the
* version of SchemaCrawler that you are using: 16.12.1
* version of Java that you are using: I don't know, the latest wich is available vie chocolatey 
* operating system and version that you are using: Windows 10
* relational database and version that you are using: SQL Server 2017, SQL Server 2019
* JDBC driver and version that you are using:  
I don't know which drivers are used by SchemaCrawler. It looks like nearly every Java Application provides their own drivers and can use different drivers. I think SchemaCrawler was bundled with some drivers. But I also have available many original Microsoft JDBC drivers on my PC, which could be used, if I would know, hot to set them. I have no idea, how Java application makes a decision which driver to use. It looks like this is different in different Java applications. I am not a Java developer.

**Comment by sualeh** [comment]
@aisbergde - thanks for the detailed bug report. The `--database` option is to indicate the starting database when making a connection. However, you will see all the Microsoft SQL Server databases that are available to the database user that you used to make the connection. If you need to filter to a certain database or schema, use `--schemas`. Please read through the [database support](https://www.schemacrawler.com/database-support.html) page, which explains how to create a connection to Microsoft SQL Server. I am leaving this issue open in case you have any further questions.

**Comment by aisbergde** [comment]
@sualeh - Thanks. This was my error. I used the --database, which was wrong in my case. Now I used the `--schemas=dhw_self.*` as described in the documentation and this works fine. This was not very clear for me from reading the documentation, because in the examples also --database is used, and I thought that this filters the database, and that I have an additional optional filter with `--schemas`. But in fact it is probably so that `--database` is only used for the general connection, so normally it is not necessary at all for mssql, because a user is already assigned a default database. Perhaps this could be made a bit clearer in the documentation.

>You need to specify the host, port, database name, and the schemas you are interested in, for Microsoft SQL Server.

This leads a Java-driver-inexperienced user a bit down the wrong path. In principle, the documentation is correct. The question is always whether it is also correctly understood. :-)

**Comment by aisbergde** [comment]
Anyway, it doesn't work on my SQL Server instances, I get only objects from schema dbo or from system views.

I tried this kind of parameters on SQL Server 2019:

`schemacrawler --server=sqlserver --port=52755 --user=documenter --password=xxxxxxx --schemas=WideWorldImporters.* --info-level=standard --command=list`

I also tried this on my SQL Server 2017 instance, and I have the same issue, only dbo and system views are listed

`schemacrawler --server=sqlserver --user=documenter --password=xxxx --schemas=AdventureWorks2017.* --info-level=standard --command=list`

the user documenter has rights, which are enough, when I use this user to connect to the instances in SSMS. I can see all objects and I can read them. this user can also see the definitions and metadata. I also tried to grant this user sysadmin rights, but this doesn't change something.

**Comment by sualeh** [comment]
@aisbergde Germo, if you are can use Docker compose, please take a look at the [instructions on how to get SchemaCrawler working with SQL Server](https://github.com/schemacrawler/SchemaCrawler/tree/master/schemacrawler-docker/docker-compose).

**Comment by aisbergde** [comment]
the link doesn't work, but I found these links and I will try to use docker:

- https://www.schemacrawler.com/docker-image.html
- https://github.com/schemacrawler/SchemaCrawler-Docker

But there is nothing related to SQL Server and I don't know if this will solve the issues.

**Comment by sualeh** [comment]
@aisbergde - were you able to connect to Microsoft SQL Server? Can I close this issue?

**Comment by aisbergde** [comment]
@sualeh I was not able to solve this issue with my current installation. I tried with docker, but first I would need to learn how to use docker: The instructions for use are probably for Linux users and I would first have to figure out how to translate those into instructions for Windows users.

That's why I thought I'd test SchemaCrawler again when I can define virtual additional relations.

**Comment by sualeh** [comment]
Ok, in that case, I will close this issue.

**Comment by aisbergde** [comment]
@sualeh you closed the issue, but it is still not solved. Here are my investigations, bug reports and some solutions

- I am not able to use integrated security
- helpful information is missing, which JDBC driver is currently used
- the documentation to connect with SQL Server needs to be extended: the desired database needs to be defined **twice**: once in the connection and once in the --schemas
- examples how to use --url could be added to the documentation, to make it more easy to use "common" connections strings as defined by the JDBC manufacturer (including examples for usage of instanceName instead of portNumber)

Finally, I got it to work. It is **required to set the database twice**:

>schemacrawler --url=jdbc:sqlserver://localhost;databaseName=AdventureWorks2017; --schemas=AdventureWorks2017.* --info-level=standard --command=list --user=documenter --password=xxx

now I try **not** to set the database inside the url

>schemacrawler --url=jdbc:sqlserver://localhost; --schemas=AdventureWorks2017.* --info-level=standard --command=list --user=documenter --password=xxx

And now I can reproduce the first and main issue: I see only system views and dbo. And now I understand the reason a bit better:

- the default connection will connect only to the default database, which often is master
- all the system views are part of master, thats why they are shown
- only the dbo schema is shown for other databases (I don't understand why)

In other words, the documentation for SQL Server usage should be extended:

- the "default" way using only SchemaCrawler parameters will work only, if the desired database is defined as the default database for the user
- if "--schemas" will define another database, then url (or urlx) must also be used to define the desired database.  
  I did not test with the normal `-database` parameter, because I need the url anyway to define the instanceName instead of the port
- in other words, the desired database needs to be defined **twice**, in the --url and in --schemas. This is not intuitive, and it should be documented to avoid frustration. Otherwise other users will get the same issues. That was hard to figure out and took a lot of time. We want to make life easier for other users :-)

Next issue (not solved):

Now I try **integrated security**, it doesn't work, I need a valid user and valid password (I also tried without the user/password)

```
C:\Users\ggoer>schemacrawler --url=jdbc:sqlserver://localhost;databaseName=AdventureWorks2017;integratedSecurity=true; --schemas=AdventureWorks2017.* --info-level=standard --command=list --user=xxx --password=documenter
SchemaCrawler 16.14.1

Error: Could not connect to jdbc:sqlserver://localhost;databaseName=AdventureWorks2017;integratedSecurity=true;, for user 'documenter', with properties {}: Dieser Treiber ist nicht für integrierte Authentifizierung konfiguriert. ClientConnectionId:53cd5781-2f7a-4ac6-8e21-1a1153826238
```

>The used driver is not configured to use integrated security.

- But how can I know which driver is used?
- And how it could or should be configured to use integrated security?
- I know that JDBC drivers for SQL Server support it, and I don't like to enable SQL Server users only for Java applications (they often have issues with integrated security)
- FeatureRequest: print information about the uses driver into the System information section in the output

Now I will try to use **instanceName** instead of portNumber

>schemacrawler --url=jdbc:sqlserver://localhost;instancename=sql2019;databaseName=WideWorldImporters; --schemas=WideWorldImporters.* --info-level=standard --command=list --user=readonly --password=xxx

This works now, but there is **another issue**:

I have 3 databases:

- WideWorldImporters
- WideWorldImportersDW
- WideWorldImporters-test

When I use the command above:

- I get all objects from WideWorldImporters
- I get dbo and System Objects form WideWorldImportersDW
- I get no objects from WideWorldImporters-test

But this is wrong, only objects in WideWorldImporters should be listed, not in WideWorldImportersDW. there is no placeholder in the database of `--schemas=WideWorldImporters.*`

**Comment by aisbergde** [comment]
regarding --schema: it looks like these are regular expressions. In this case is not a bug, but a feature and this should work:
`WideWorldImporters\.\w*`

**Comment by aisbergde** [comment]
But this doesn't work, but it is valid regex

schemacrawler --url=jdbc:sqlserver://localhost;instancename=sql2019;databaseName=dhw_self; --schemas=dhw_self\.(repo|graph) --info-level=standard --command=list --user=readonly --password=xxx

**Comment by sualeh** [comment]
@aisbergde - as far as possible, I request you to open one targeted issue for each question/ problem that you have.

> But how can I know which driver is used?

Please see the [database support page](https://www.schemacrawler.com/database-support.html) - there is a link to the driver documentation

> And how it could or should be configured to use integrated security?
I know that JDBC drivers for SQL Server support it, and I don't like to enable SQL Server users only for Java applications (they often have issues with integrated security)

SchemaCrawler is a cross-platform tool, and will not document specific use cases. Please refer to specific manufacturer information - https://github.com/Microsoft/mssql-jdbc

> FeatureRequest: print information about the uses driver into the System information section in the output 

Will do.

**Comment by sualeh** [comment]
> But this doesn't work, but it is valid regex
`schemacrawler --url=jdbc:sqlserver://localhost;instancename=sql2019;databaseName=dhw_self; --schemas=dhw_self.(repo|graph) --info-level=standard --command=list --user=readonly --password=xxx`

I cannot tell what is going on. You need to provide detailed logs. Please see [how to report an issue](https://www.schemacrawler.com/consulting.html)
