### ISSUE TITLE
--schemas regex issues: different results in the shell; issues with list of schemas

### ISSUE THREAD

**Issue by aisbergde** [schemacrawler/SchemaCrawler#427]
# Bug Report

**Issue**

some issues with using the --schemas

1. different results interactive and non interactive tor the same --schemas on the same database

interactive shell

```
connect --url=jdbc:sqlserver://localhost;instancename=sql2019;databaseName=WideWorldImporters; --user=readonly --password=readonly
limit --schemas=WideWorldImporters\..* 
load --info-level=standard
execute --command=list --no-info --output-file=./share/schema.txt
```

This should limit the database WideWorldImporters, but in the generated schema.txt also some object from WideWorldImportersDW are listed, but only system views from
- WideWorldImportersDW.INFORMATION_SCHEMA.
- WideWorldImportersDW.sys.

when I use the same filter not interactively

```
schemacrawler --url=jdbc:sqlserver://localhost;instancename=sql2019;databaseName=WideWorldImporters; --schemas=WideWorldImporters\..* --info-level=standard --command=list --user=readonly --password=readonly
```

then it works as required, all object of WideWorldImporters are listed, but no objects of WideWorldImportersDW

2. combining some schemas with "|" doesn't work

example which should list only
WideWorldImporters\.(Purchasing|Sales)

```
schemacrawler --url=jdbc:sqlserver://localhost;instancename=sql2019;databaseName=WideWorldImporters; --schemas=WideWorldImporters\.(Purchasing|Sales)\..* --info-level=standard --command=list --user=readonly --password=readonly
```

this causes an error

```
D:\SchemaCrawler>schemacrawler --url=jdbc:sqlserver://localhost;instancename=sql2019;databaseName=WideWorldImporters; --schemas=WideWorldImporters\.(Purchasing|Sales)\..* --info-level=standard --command=list --user=readonly --password=readonly
Das System kann den angegebenen Pfad nicht finden.
```

and now in the shell

```
schemacrawler> limit --schemas=WideWorldImporters\.(Purchasing|Sales)\..*
limit --schemas=WideWorldImporters\.(Purchasing|Sales)schemacrawler> load --info-level=standard
ERROR: Cannot load catalog
schemacrawler> execute --command=list --no-info --output-file=./share/schemaPS.txt
```

Maybe something needs to be escaped?
But it would be better if regex could be used as it is, then it is easier to compose and check it in regex validators like https://regex101.com/

Please explain the issue briefly
* Provide the steps that you took to reproduce the issue
* Provide any steps that you took to solve the issue
* Zip and attach the SchemaCrawler debug logs, which can be obtained by running SchemaCrawler with an additional `-loglevel=ALL` on the command-line argument

**Environment**

```
schemacrawler> help
SchemaCrawler 16.14.1
Database schema discovery and comprehension tool
https://www.schemacrawler.com/
Copyright (c) 2000-2021, Sualeh Fatehi <sualeh@hotmail.com>.
System Information:
Windows 10 10.0
AdoptOpenJDK OpenJDK 64-Bit Server VM 11.0.10+9
```

**Comment by sualeh** [comment]
@aisbergde - it is probably an escaping issue. SchemaCrawler cannot control this - it depends on the shell you are using. A command may work in the Windows command prompt shell but not in PowerShell and not in Windows Subsystem for Linux. It all depends on the shell. What shell are you using?

**Comment by aisbergde** [comment]
I didn't know, that different shell could work differently with regex. I used just the Windows cmd. But I could also try powershell.

What is the recommended environment for SC on Windows? 

Do you have an idea how the regex function should be tested in general? I always thought: regex is regex. And I just used online regex validators.

**Comment by sualeh** [comment]
Stick with whatever shell you like. I have no recommendations. Let me try with Windows cmd.exe and show you what the regular expression escaping should look like in that shell.

**Comment by aisbergde** [comment]
When I call the SC shell via powershell, I get the same issue.

It is not possible to use the non interactive SC as it is in Powershell:

```
PS D:\SchemaCrawler> PS D:\SchemaCrawler> schemacrawler --url=jdbc:sqlserver://localhost;instancename=sql2019;databaseName=WideWorldImporters; --schemas=WideWorldImporters\..* --info-level=standard --command=list --user=readonly --password=readonly
>> In Zeile:1 Zeichen:104
>> + ... host;instancename=sql2019;databaseName=WideWorldImporters; --schemas= ...
>> +                                                                  ~
>> Ausdruck fehlt nach dem unären Operator "--".
>> In Zeile:1 Zeichen:104
>> + ... baseName=WideWorldImporters; --schemas=WideWorldImporters\..* --info- ...
>> +                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>> Unerwartetes Token "schemas=WideWorldImporters\..*" in Ausdruck oder Anweisung.
>>     + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
>>     + FullyQualifiedErrorId : MissingExpressionAfterOperator
>>
```

So I have to use cmd

**Comment by sualeh** [comment]
😄 Try out the same SchemaCrawler command with PowerShell, and see what happens. You will be surprised if you are not used to PowerShell.

**Comment by sualeh** [comment]
@aisbergde - it is possible to use PowerShell of course - I use PowerShell with SchemaCrawler all the time. But there is a learning curve with any shell, and you will need to learn how to use PowerShell.

**Comment by aisbergde** [comment]
for the second issue with:
`limit --schemas=WideWorldImporters\.(Purchasing|Sales)\..*`

My final goal is just to exclude schemas with system views and system procedures (sys, INFORMATION_SCHEMA).

And because I don't know how to exclude them my only idea is to list all schemas but not the system schemas. Maybe there is another way to exclude system views?

**Comment by sualeh** [comment]
I cannot think of way to exclude system views other than what you are trying to do. Let me figure out the proper escaping for Windows cmd.exe and I will get back to you.

**Comment by aisbergde** [comment]
What about schemacrawler.config.properties
Could this be used?

```
# - Limit Options - inclusion rules for database objects
# ------------------------------------------------------------------------------
# - Regular expression schema pattern to  filter
# - schema names
# - Default: .* for include, <none> for exclude
# - IMPORTANT: Please uncomment the follow patterns only for
# - database that support schemas. SQLite for example does
# - not support schemas
#schemacrawler.schema.pattern.include=.*
#schemacrawler.schema.pattern.exclude=
```

**Comment by sualeh** [comment]
@aisbergde - that should work. Try it out.

**Comment by aisbergde** [comment]
I don't get `schemacrawler.schema.pattern.exclude` to work in any way

but I get it using `schemacrawler.table.pattern.exclude=.*\.sys\..*|.*\.INFORMATION_SCHEMA\..*`

```
# - Limit Options - inclusion rules for database objects
# ------------------------------------------------------------------------------
# - Regular expression schema pattern to  filter
# - schema names
# - Default: .* for include, <none> for exclude
# - IMPORTANT: Please uncomment the follow patterns only for
# - database that support schemas. SQLite for example does
# - not support schemas
#schemacrawler.schema.pattern.include=.*
#it doesn't work in any combination: sys, .*sys.*, sys.*, sys\..* 
#schemacrawler.schema.pattern.exclude=sys
# - Regular expression table and column name pattern to filter table
# - and column names
# - Column regular expression to match fully qualified column names,
# - in the form "CATALOGNAME.SCHEMANAME.TABLENAME.COLUMNNAME"
# - Default: .* for include, <none> for exclude
#schemacrawler.table.pattern.include=.*
schemacrawler.table.pattern.exclude=.*\.sys\..*|.*\.INFORMATION_SCHEMA\..*
```

**Comment by sualeh** [comment]
@aisbergde - great. So do you want to close this issue?

**Comment by aisbergde** [comment]
No, it is filtering too much. it is also filtering the schema repo_sys, which should not be filtered
I have to investigate later...

**Comment by sualeh** [comment]
I am closing this one, since the SchemaCrawler shell can now accept the "`\`" character in regular expressions.
