### ISSUE TITLE
SQL Server - intergrated security doesn't work

### ISSUE THREAD

**Issue by aisbergde** [schemacrawler/SchemaCrawler#433]
# Bug Report

**Issue**

I try integrated security, it doesn't work, I need a valid user and valid password (I also tried without the user/password)

```
C:\Users\ggoer>schemacrawler --url=jdbc:sqlserver://localhost;databaseName=AdventureWorks2017;integratedSecurity=true; --schemas=AdventureWorks2017.* --info-level=standard --command=list --user=documenter --password=documenter
SchemaCrawler 16.14.1

Error: Could not connect to jdbc:sqlserver://localhost;databaseName=AdventureWorks2017;integratedSecurity=true;, for user 'documenter', with properties {}: Dieser Treiber ist nicht für integrierte Authentifizierung konfiguriert. ClientConnectionId:53cd5781-2f7a-4ac6-8e21-1a1153826238
```

error:

>The used driver is not configured to use integrated security.

how it could or should be configured to use integrated security?
I know that JDBC drivers for SQL Server support it, and I don't like to enable SQL Server users only for Java applications (they 

related: #410 

**Environment**

Specify the
* version of SchemaCrawler that you are using 16.14.1
* version of Java that you are using
* operating system and version that you are using Windows 10
* relational database and version that you are using SQL server 2017 an 2019
* JDBC driver and version that you are using - the driver delivered in the package

**Comment by sualeh** [comment]
This documentation is outside the scope of SchemaCrawler. Please consult the official Microsoft JDBC driver documentation. https://github.com/microsoft/mssql-jdbc

**Comment by aisbergde** [comment]
@sualeh the Microsoft JDBC driver works with integrated security. But it looks like that this depends on the Java application if this will be supported and how this will be supported.

From the drivers documentation:

>Download the DLLs
>For some features (e.g. Integrated Authentication and Distributed Transactions), you may need to use the sqljdbc_xa and mssql-jdbc_auth-<version>.<arch> DLLs. They can be downloaded from the Microsoft Download Center. mssql-jdbc_auth-<version>.<arch> can also be downloaded from Maven.

But how I can know how to use these DLLs in the SchemaCrawler?
Should I find a way?
Or maybe it would be better to implement this directly for all SQL Server users into SC?

In SC documentation it is documented that it can be used:

https://www.schemacrawler.com/database-support.html

>--server=sqlserver --host=db.example.com --port=1433 --urlx=integratedSecurity=true --database=schemacrawler --schemas=schemacrawler.dbo --user=xxxxx --password=xxxxx --info-level=standard -command=schema

So my idea was: if it is documented, it should or could work.

Maybe you could reopen the issue? Maybe it will not be solved now, but sometimes in the future, maybe never? Why not just keep some open issues?

**Comment by sualeh** [comment]
SchemaCrawler is distributed with the JDBC driver as well as the DLL (look in the SchemaCrawler "lib/" folder). SchemaCrawler has been tested with named instances. There is nothing more I can do but to include a link to the Microsoft documentation.
