### ISSUE TITLE
shell "help execute" - hint how to get a list of possible execute commands

### ISSUE THREAD

**Issue by aisbergde** [schemacrawler/SchemaCrawler#434]
# New Feature Request

improve user experience when using the shell:  
when calling `help execute` then add hint how to get a list of possible commands

**Describe the solution you'd like**

To use `help load`, `help execute` and so on is intuitive. But this information should be extended with a hint, how to get the list of possible commands

```
schemacrawler> help execute
** Execute a SchemaCrawler command

  -c, --command=<command>   SchemaCrawler command
  -F, --output-format=<outputFormatValue>
                            Format of the SchemaCrawler output
                            Supported formats are dependent on the
                              SchemaCrawler command being executed
```

For example the -F is well documented
But the -c could be better documented (here in the interactive help), to understand, which commands could be used and how to get a list of these commands

**Describe alternatives you've considered**

no idea.
Using katacoda, see some examples and remember (or forget) them

**Comment by aisbergde** [comment]
for example, just write there
>to get a list of Available SchemaCrawler commands, use `help`

**Comment by sualeh** [comment]
Fixed. Will be available in the next SchemaCrawler release.
