### ISSUE TITLE
optional parameter to create a TOC with flexible levels for HTML export

### ISSUE THREAD

**Issue by aisbergde** [schemacrawler/SchemaCrawler#435]
# New Feature Request

Regarding the export to html
`execute --command=schema --output-file=./share/schema.html`

The html document could be very big, and it could be hard to navigate
I want to suggest adding optional TOC to get an overview of objects and to be able to easy jump from the TOC to the object.
In case there is a TOC there could also be links for "jump to top" to get back to the TOC
The TOC could be foldable, if this is possible

An alternative way would be:
- to keep the export as it is
- but to generate 2 additional documents:
  - one containing the TOC
  - another parent document containing the tree on the left and the main document

**Describe the solution you'd like**

a new parameter to define an optional TOC, and it's structure (which levels in which order to be used to create the TOC)
if this parameter is missing, no TOC is generated (to not break existing usage of this export)

example:

- HtmlTocLevels=schemaname,objecttype,objectname  
would generate a TOC containing 3 levels: schemaname, objecttype (table, view, procedure, ...), Objectname  
- HtmlTocLevels=type,schema,object  
would generate a different strucuture

the names for the parameter and the levels are only to demonstrate the idea.
And because objectname would be mandatory in the TOC, it could be also omitted.

**Comment by sualeh** [comment]
@aisbergde - there are an infinite variety of reports that can be generated, and SchemaCrawler allows for templating and scripting to allow you to customize to your heart's content. Please download the SchemaCrawler distribution, and take a look at the templating examples (in the `velocity`, `mustache`, or `thymeleaf` folders) and pick one of these templating solutions to suit your needs. Also please look at the Python, Groovy, Ruby and JavaScript examples for ideas on scripting.
