### ISSUE TITLE
CDN urls for logo resources

### ISSUE THREAD

**Issue by adriens** [schemacrawler/SchemaCrawler#440]
# New Feature Request

Sometimes repositores ask for CDN like resources for logos, providing official ones from SC would be cool.

# Generated ones

I have generated the following one : 

https://cdn.statically.io/gh/schemacrawler/SchemaCrawler/master/schemacrawler-website/src/site/resources/images/schemacrawler_logo.png

based on  : 

https://raw.githubusercontent.com/schemacrawler/SchemaCrawler/master/schemacrawler-website/src/site/resources/images/schemacrawler_logo.png

And used https://statically.io/convert/ service for that

**Comment by sualeh** [comment]
@adriens - very cool! Thank you.

**Comment by adriens** [comment]
👍 ❤️
