### ISSUE TITLE
improve documentation for output formats and possible values (serialize, file export)

### ISSUE THREAD

**Issue by aisbergde** [schemacrawler/SchemaCrawler#450]
# New Feature Request

serialize - inside shell in the help only this is available:

```
** Create an offline catalog snapshot
Command:
command:serialize
For more information, see https://www.schemacrawler.com/serialize.html

Deserialization is possible with the "offline" command for Java serialization
Add command switches to the execute command in the SchemaCrawler Shell
```

The page informs:

>For example, --output-format=json will generate a output in JSON format.

And it points to the examples. There is only one example:

```
@echo off
..\..\_schemacrawler\schemacrawler.cmd --server=hsqldb --database=schemacrawler --user=sa --password= --info-level=standard -c serialize --output-format %1
```

- But where is some documentation about **all** supported output-format and the values to be used? Maybe the values are
  - json
  - yaml
  - ???

**same issue with possible output formats for** 
`execute --command=schema --output-file`
a list of possible file extensions is missing

https://www.schemacrawler.com/index.html

>SchemaCrawler comes with a set of command-line tools that allow database metadata to be output as plain text, HTML5, HTML5 with embedded diagrams,, JavaScript object notation (JSON) or YAML.

but the possible values are not documented

**Describe the solution you'd like**

- improve documentation a bit to be able to find the values for all supported output-format (for serialize and for exporting lists or diagrams)

**Comment by aisbergde** [comment]
For example, I can generate json and yaml, but I have no idea how to create "in Java", because the required file extension is not documented.

```
execute --command=serialize --output-file=./share/dhw_self.json
execute --command=serialize --output-file=./share/dhw_self.yaml
```

**Comment by sualeh** [comment]
Let me work out how I can show help for output formats. Until then, use `--output-format=java` with any output filename.

**Comment by aisbergde** [comment]
Here is an example, how this could be improved:
- only here https://www.schemacrawler.com/offline.html in the example I can find the required extension `.ser`
- why not just to include this information here? https://www.schemacrawler.com/serialize.html
It would be much easier to use, if a user knows, that `.ser` should be used. At the moment, this information can be found somehow, but rather "through the back of the shoulder"

Same issue with possible output formats. In some examples a user can find png and svg. But if so many formats are supported, why not just document them?

**Comment by sualeh** [comment]
I will be fixing this issue shortly, by showing possible output formats for the serialization and lint commands, and updating the website for the offline and serialize pages.

> Same issue with possible output formats. In some examples a user can find png and svg. But if so many formats are supported, why not just document them?
There is already a URL to the Graphviz website in the help and documentation, and I will not repeat Graphviz's documentation on the SchemaCrawler website.

**Comment by adriens** [comment]
👍 
 _I will not repeat Graphviz's documentation on the SchemaCrawler website._

**Comment by aisbergde** [comment]
OK, this is fine. I tested it. You can just use the `--output-format=` in combination with some format listed at Graphviz.

Why this part of the request? I wondered about using the `.scdot` file extension, which is not documented. It seems that there are other formats than the ones mentioned at Graphviz. There seems to be an implicit link between some formats and some file extensions. Hence, the request to document possible output formats. If `.scdot` is not to be documented (and other hidden formats that may exist), then just don't.

**Comment by sualeh** [comment]
Please use SchemaCrawler 16.14.3, which will document output formats in command-line and shell help text.

**Comment by sualeh** [comment]
@aisbergde - also, please note that in SchemaCrawler 16.14.3 the Java serialization format is now called "ser" - so use `--output-format=ser`.
