### ISSUE TITLE
option --keep-schema-names and --suppress-database-names

### ISSUE THREAD

**Issue by aisbergde** [schemacrawler/SchemaCrawler#452]
# New Feature Request

existing option:

```
      --portable-names   Allow for easy comparison between databases, by hiding
                           or showing foreign key names, constraint names,
                           trigger names, specific names for routines, or index
                           and primary key names, and fully-qualified table
                           names
                         --portable-names=<boolean>
                         <boolean> can be true or false
                         Optional, defaults to false
```

The issue is, I **always** need the schema name. That's why I can't use this option `--portable-names`, but I want sometimes

**Describe the solution you'd like**

- a way similar to `--portable-names` but keeping the Schema name
- a way to suppress only the database but to keep all other data

I suggest additional options like these:
- --keep-schema-names (to be combined with the existing --portable-names)
- --suppress-database-names (to be combined with the default)

**Comment by aisbergde** [comment]
For example this command would be useful, if I could include schema name, but suppress the FK names:

`execute --command=details --output-file=./share/repo-repoobject_details_portable.svg --portable-names=true`

**Comment by sualeh** [comment]
I will keep the command-line simple. I will see how I can allow you to show "short names" (schema + object name) using config file properties.

**Comment by aisbergde** [comment]
This request is related to specific databases. When this will be part of the config file, then this will apply to all databases. But there are also simple databases with only one schema.

For flexible use it would make much more sense if this did not happen via a config file, but if you could set it individually when connecting to concrete databases.

The next problem is that the config file must be adapted again with each new SC version. Therefore, this can quickly lead to problems when a new version comes, and if you forget to copy the settings from the previous version.

It also becomes easier to use: I can create templates or something that create the diagrams for all objects in a database. And it would be good if these templates work with the default configuration of the SC and give the desired results with this configuration by default.

**Comment by aisbergde** [comment]
database name in diagrams is not the issue. The issue are the FK names, which I need to suppress. they are very long and they enlarge the diagrams without real value. So an option just to suppress them and nothing else is also OK.

I would not be able to use diff, but Visual Studio has Schema Compare.

**Comment by sualeh** [comment]
@aisbergde - I do not want to clutter the command-line. These options are already available in the config file. You will need to create multiple config files (with just the changes you need), and specify those config files on the command line. You can even pass the options from the command-line, with a "-D" option, if you follow the guidelines from [lightbend/config](https://github.com/lightbend/config). Try something like `-Dschemacrawler.format.hide_foreignkey_names=true` from the command-line, though then you cannot use the shell script ("cmd" file).

I will close this issue, since you can already suppress FK names.

**Comment by sualeh** [comment]
@aisbergde - you can set any option from the SchemaCrawler command-line using Java's "-D" option as shown below. I have tried this out in the regular Windows command-shell.

1. Open a Windows "cmd" command-shell, and "cd" to the SchemaCrawler directory.
2. Run your SchemaCrawler command-line with something like this: `java -Dschemacrawler.format.hide_foreignkey_names=true -classpath ./lib/*;. schemacrawler.Main --url=... --user=... --password=... --schemas=... --info-level standard --command schema`

**Comment by aisbergde** [comment]
Thank you for this solution. It works. And it is hard to use than just a command line option or a config file:

- it is required to locate the right folder, containing schemacrawler.cmd (OK)
- absolute path needs to be used, instead of just going to the folder where a snapshot is located and the output is to be created. (OK)
- I wanted to use the sql command `xp_cmdshell` for batch processing, but `xp_cmdshell` has a fixed working path which can't be changed on demand (issue. Maybe I need to create and call a batch file to be able to change the folder)

I still see the need to also create diagrams without database names but with schema names, or to just suppress FK names, using just command line options (or at least using the config file).

I think it would be better to simply keep some issues open, assign a low priority, so that they can perhaps be implemented at some point, instead of always closing them immediately. And I am unhappy that the issue here has now been closed without me having a clear vision for a working solution for my intended application.
