### ISSUE TITLE
Unable to read cardinality from information_schema.statistics table

### ISSUE THREAD

**Issue by artur-tamazian** [schemacrawler/SchemaCrawler#461]
# Bug Report

**Issue**

Please explain the issue briefly

`Caused by: com.mysql.cj.exceptions.NumberOutOfRange: Value '2589011712' is outside of valid range for type java.lang.Integer`

It looks like SchemaCrawler is using `getInt()` to fetch values from cardinality column from information_schema.statistics table ([code](https://github.com/schemacrawler/SchemaCrawler/blob/d8e2a16b2ec748c879bdec636bd1d58f5a6bdb53/schemacrawler-api/src/main/java/schemacrawler/crawl/IndexRetriever.java#L121)). I believe the actual type is UNSIGNED (see show create table output [here](https://github.com/artur-tamazian/avro-schema-generator/issues/25#issuecomment-825366908)) so potential fix is to use 'getLong()' instead of 'getInt()'

warn: Could not read integer value for column

`java.sql.SQLDataException: Value '2589011712' is outside of valid range for type java.lang.Integer
App > at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:114)
App > at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
App > at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89)
App > at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63)
App > at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:73)
App > at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:92)
App > at com.mysql.cj.jdbc.result.ResultSetImpl.getObject(ResultSetImpl.java:1411)
App > at com.mysql.cj.jdbc.result.ResultSetImpl.getInt(ResultSetImpl.java:816)
App > at com.mysql.cj.jdbc.result.ResultSetImpl.getInt(ResultSetImpl.java:837)
App > at schemacrawler.crawl.MetadataResultSet.getInt(MetadataResultSet.java:340)
App > at schemacrawler.crawl.IndexRetriever.createIndexForTable(IndexRetriever.java:182)
App > at schemacrawler.crawl.IndexRetriever.createIndexes(IndexRetriever.java:146)
App > at schemacrawler.crawl.IndexRetriever.retrieveIndexesFromMetadata(IndexRetriever.java:343)
App > at schemacrawler.crawl.IndexRetriever.retrieveIndexesFromMetadata(IndexRetriever.java:359)
App > at schemacrawler.crawl.IndexRetriever.retrieveIndexes(IndexRetriever.java:98)
App > at schemacrawler.crawl.SchemaCrawler.lambda$crawlTables$22(SchemaCrawler.java:615)
App > at sf.util.StopWatch.time(StopWatch.java:177)
App > at schemacrawler.crawl.SchemaCrawler.crawlTables(SchemaCrawler.java:609)
App > at schemacrawler.crawl.SchemaCrawler.crawl(SchemaCrawler.java:766)
App > at schemacrawler.utility.SchemaCrawlerUtility.getCatalog(SchemaCrawlerUtility.java:89)
App > at com.at.avro.DbSchemaExtractor.get(DbSchemaExtractor.java:71)
App > at com.at.avro.DbSchemaExtractor.getForTables(DbSchemaExtractor.java:49)`

**Environment**

Specify the
* version of SchemaCrawler that you are using
 16.2.4
* version of Java that you are using 
* operating system and version that you are using
 Don't know, can clarify if needed 
* relational database and version that you are using
 AWS RDS with mysql version 8.0.23
* JDBC driver and version that you are using
 Don't know, can clarify if needed

**Comment by sualeh** [comment]
@artur-tamazian - thanks for reporting this. Seems like a long-standing bug which needs to be fixed. I will get this sorted out.

**Comment by sualeh** [comment]
Please use SchemaCrawler 16.14.5

**Comment by artur-tamazian** [comment]
Thank you for the quick fix!
