### ISSUE TITLE
API: TimSort Exception (Comparison method violates its general contract) when crawl SQL Database Foreign Keys

### ISSUE THREAD

**Issue by bjjoop** [schemacrawler/SchemaCrawler#466]
Hi,

there seems to be a problem with sorting the tables during crawling with the foreign keys.
I have a big, complex MSSQL database with several foreign keys pointing to tables and vice versae; and also including foreign keys referencing the tables themselves.

While using the API version, timsort now throws the exception "Comparison method violates its general contract" during sorting the foreign keys. Mor specific: the exception is thrown during MutableTable#getTableReferences() being called from MutableTable#getExportedForeignKeys().
From my perspektive, the defined comparator

```java
final Comparator<R> fkComparator =
        nullsLast(
            ((Comparator<R>)
                    (final R one, final R two) -> {
                      final Table oneParent = one.getParent();
                      final Table twoParent = two.getParent();
                      if (oneParent.equals(twoParent)) {
                        return 0;
                      } else if (oneParent.equals(this)) {
                        return -1;
                      } else {
                        return 1;
                      }
                    })
                .thenComparing(naturalOrder()));
```
may be the problem.

The affected table is a rather central database table with
- 1 pk
- 8 outgoing foreign key (one referencing itself as a kind of parent reference)
- 24 incoming foreign keys from other tables referencing the pk.

I am trying to crawl the database with a minimum example of

```java
public interface DatabaseAccessData {
    /**
     * @return user name for db connection
     */
    String getUserName();

    /**
     * @return user password for db connection
     */
    String getPassword();

    /**
     * @return db name
     */
    String getDatabaseName();

    /**
     * @return db schema
     */
    String getDatabaseSchema();
}
```
```java
public class Test {

    public static void main(String[] argvs) throws SchemaCrawlerException, SQLException, ClassNotFoundException {
	DatabaseAccessDataBuilder tempBuilder = DatabaseAccessDataBuilder.create().withUserName("login").withPassword("pwd").withDatabaseSchema("dbo").withDatabaseName("mydb");
	final SchemaCrawlerOptions options = createCrawlOptions(tempBuilder.build());
	// SchemaCrawlerOptionsBuilder.newSchemaCrawlerOptions();

	final Catalog catalog = SchemaCrawlerUtility.getCatalog(createConnection(tempBuilder.build()), options);

	for (final Schema schema : catalog.getSchemas()) {
	    System.out.println(schema);
	    for (final Table table : catalog.getTables(schema)) {
		System.out.print("o--> " + table);
		for (final Column column : table.getColumns()) {
		    System.out.println("     o--> " + column + " (" + column.getColumnDataType() + ")");
		}
	    }
	}
    }

    private static Connection createConnection(DatabaseAccessData aDbAccessData) throws SQLException, ClassNotFoundException {
	Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
	String tempConnectionString = String.format("jdbc:sqlserver://localhost:1433;database=%s;characterEncoding=UTF-8;sendTimeAsDatetime=false;", aDbAccessData.getDatabaseName());
	return DriverManager.getConnection(tempConnectionString, aDbAccessData.getUserName(), aDbAccessData.getPassword());
    }
    private static SchemaCrawlerOptions createCrawlOptions(DatabaseAccessData aDbAccessData) {
	// Set what details are required in the schema - this affects the
	// time taken to crawl the schema
	SchemaInfoLevelBuilder tempSchemaInfoBuilder = SchemaInfoLevelBuilder.builder();
	tempSchemaInfoBuilder.setRetrieveTables(true);
	tempSchemaInfoBuilder.setRetrieveColumnDataTypes(true);
	tempSchemaInfoBuilder.setRetrieveTableColumns(true);
	tempSchemaInfoBuilder.setRetrieveTableColumnPrivileges(true);
	tempSchemaInfoBuilder.setRetrieveForeignKeys(true);
	tempSchemaInfoBuilder.setRetrieveViewInformation(true);

	LoadOptionsBuilder tempLoadOptionsBuilder = LoadOptionsBuilder.builder();
	tempLoadOptionsBuilder.withSchemaInfoLevel(tempSchemaInfoBuilder.toOptions());

	FilterOptionsBuilder tempFilterOptionsBuilder = FilterOptionsBuilder.builder();

	LimitOptionsBuilder tempLimitOptionsBuilder = LimitOptionsBuilder.builder();
	tempLimitOptionsBuilder.includeSchemas(new SchemaInclusionRule(aDbAccessData));
	LoadOptions tempLoadOptions = tempLoadOptionsBuilder.toOptions();
	GrepOptions tempGrepOptions = GrepOptionsBuilder.builder().toOptions();
	final SchemaCrawlerOptions tempCrawlerOptions = SchemaCrawlerOptionsBuilder.newSchemaCrawlerOptions().withLoadOptions(tempLoadOptions).withFilterOptions(tempFilterOptionsBuilder.toOptions())
		.withLimitOptions(tempLimitOptionsBuilder.toOptions()).withGrepOptions(tempGrepOptions);
	return tempCrawlerOptions;
    }
}
```

```java
public final class SchemaInclusionRule implements schemacrawler.inclusionrule.InclusionRule {

    private static final long serialVersionUID = -987073905640076549L;

    private final String databaseName; // name of the db
    private final String schemaName;// name of the schema in the db

    public SchemaInclusionRule(DatabaseAccessData aDbAccessData) {
	databaseName = aDbAccessData.getDatabaseName();
	schemaName = aDbAccessData.getDatabaseSchema();
    }

    @Override
    public boolean test(String aT) {
	return (databaseName + "." + schemaName).equals(aT);
    }
}
```

I am using
- schema crawler 16.14.5 from maven central 
- jdk-11.0.9
- Windows 11
- SQL Server 2017 (latest, running in docker).
- mssql-jdbc 9.2.1.jre11

**Comment by bjjoop** [comment]
Sorry for bad formatting, does not seem to work the way I want it to :(

**Comment by sualeh** [comment]
@bjjoop - no problem. I have reformatted your question. Please could you share the stack-trace? Also, is there a way to share the  DDL script (not need for the data - just the schema), so I can try to reproduce? See https://github.com/microsoft/mssql-scripter. Thanks.

**Comment by bjjoop** [comment]
Thank you for replying so fast:
I have been trimming down the database as much as possible to provide some schema. I did let MSSQL create the table & foreign key creation scripts and attached it (sorry for the bogus names).
[SchemaCrawlerForeignKeyProblem.txt](https://github.com/schemacrawler/SchemaCrawler/files/6434188/SchemaCrawlerForeignKeyProblem.txt)

The database created by the schema causes the exception while trying to sort the foreign keys on Table **R**.

As for the stack trace:
`Exception in thread "main" schemacrawler.schemacrawler.SchemaCrawlerException: Exception retrieving table information: Comparison method violates its general contract!
	at schemacrawler.crawl.SchemaCrawler.crawlTables(SchemaCrawler.java:739)
	at schemacrawler.crawl.SchemaCrawler.crawl(SchemaCrawler.java:146)
	at schemacrawler.tools.catalogloader.SchemaCrawlerCatalogLoader.loadCatalog(SchemaCrawlerCatalogLoader.java:59)
	at schemacrawler.tools.catalogloader.ChainedCatalogLoader.loadCatalog(ChainedCatalogLoader.java:77)
	at schemacrawler.tools.utility.SchemaCrawlerUtility.getCatalog(SchemaCrawlerUtility.java:103)
	at schemacrawler.tools.utility.SchemaCrawlerUtility.getCatalog(SchemaCrawlerUtility.java:85)
	at de.dbtools.Test.main(Test.java:34)
Caused by: java.lang.IllegalArgumentException: Comparison method violates its general contract!
	at java.base/java.util.TimSort.mergeLo(TimSort.java:781)
	at java.base/java.util.TimSort.mergeAt(TimSort.java:518)
	at java.base/java.util.TimSort.mergeCollapse(TimSort.java:448)
	at java.base/java.util.TimSort.sort(TimSort.java:245)
	at java.base/java.util.Arrays.sort(Arrays.java:1515)
	at java.base/java.util.ArrayList.sort(ArrayList.java:1750)
	at java.base/java.util.Collections.sort(Collections.java:179)
	at schemacrawler.crawl.MutableTable.getTableReferences(MutableTable.java:385)
	at schemacrawler.crawl.MutableTable.getExportedForeignKeys(MutableTable.java:128)
	at schemacrawler.filter.TablesReducer.removeForeignKeys(TablesReducer.java:133)
	at schemacrawler.filter.TablesReducer.reduce(TablesReducer.java:64)
	at schemacrawler.crawl.MutableCatalog.reduce(MutableCatalog.java:301)
	at schemacrawler.crawl.SchemaCrawler.lambda$22(SchemaCrawler.java:597)
	at us.fatehi.utility.StopWatch.time(StopWatch.java:130)
	at schemacrawler.crawl.SchemaCrawler.crawlTables(SchemaCrawler.java:592)
	... 6 more
`

I have been experimenting with a slight modification of the existing comparator in _schemacrawler.crawl.MutableTable#getTableReferences(NamedObjectList<? extends ForeignKey>, TableAssociationType)_, a possible fix seems to be instead of returning 1 in the last else statment to return a comparison of the two tables:

Original comparator:
`final Comparator<R> fkComparator = nullsLast(((Comparator<R>) (final R one, final R two) -> {
	    final Table oneParent = one.getParent();
	    final Table twoParent = two.getParent();

	    if (oneParent.equals(twoParent)) {
		return 0;
	    } else if (oneParent.equals(this)) {
		return -1;
	    } else {
		return 1;
	    }
	}).thenComparing(naturalOrder()));`

Suggestion:
`
final Comparator<R> fkComparator = nullsLast(((Comparator<R>) (final R one, final R two) -> {
	    final Table oneParent = one.getParent();
	    final Table twoParent = two.getParent();

	    if (oneParent.equals(twoParent)) {
		return 0;
	    } else if (oneParent.equals(this)) {
		return -1;
	    } else {
		return oneParent.compareTo(twoParent);
	    }
	}).thenComparing(naturalOrder()));`
	
Thanks for the trouble (and I hope formatting works better this time).

**Comment by sualeh** [comment]
Thank you - that script helped me reproduce and fix the issue. I will release a new version of SchemaCrawler soon, once I can incorporate your script as a unit test.

**Comment by sualeh** [comment]
Until you get the new SchemaCrawler version, you can work around this issue by starting java with `-Djava.util.Arrays.useLegacyMergeSort=true`.

**Comment by sualeh** [comment]
Please use SchemaCrawler v16.14.6
