### ISSUE TITLE
SqlServer: foreign keys are ignored if they have the same name

### ISSUE THREAD

**Issue by darkattractions** [schemacrawler/SchemaCrawler#469]
# Bug Report

**Issue**

I add two databases test1/dbo and test2/dbo on the same sqlserver database
I create 2 foreign keys in test1/dbo and test2/dbo that have the same name.
SchemaCrawler ignores the 2nd foreign key in the second databases.

**Comment by darkattractions** [comment]
Sorry I used the version 16.14.5

**Comment by sualeh** [comment]
@darkattractions - this is a tough one to solve. Since SchemaCrawler is a cross-database tool, it has to support database systems that allow cross-schema foreign keys.

**Comment by sualeh** [comment]
Please use SchemaCrawler v16.14.6

**Comment by darkattractions** [comment]
@sualeh - Thank you
