### ISSUE TITLE
SqlServer: get stored procedure body

### ISSUE THREAD

**Issue by darkattractions** [schemacrawler/SchemaCrawler#470]
# Bug Report

**Issue**
There are 2 issues
1. I set all the variables to get the stored procedure body and I can't get the body.
I noticed the sqlserver jdbc driver returns the procedure name ending with ";1" and the query in ROUTINES.sql does not take in account this value (example: routine name is "proc;1" and ROUTINES.sql returns "proc" for ROUTINE_NAME)
I overrided this query but with no success. 
2. So I dig into the code and I noticed the catalog does not recognize the procedure name:
```
for (Routine routine : catalog.getRoutines(schema)) {
    System.out.println(catalog.lookupRoutine(schema, routine.getName()).isPresent()); // this line returns false
}
```

**Comment by sualeh** [comment]
@darkattractions - Please see https://github.com/microsoft/mssql-jdbc/issues/448 - Microsoft is refusing to fix how the SQL Server JDBC driver retrieves procedure names, even though this numbering is a deprecated feature. So I will have to remove the ability for SchemaCrawler to retrieve stored procedure definitions. Sorry.

**Comment by darkattractions** [comment]
@sualeh - Thank you for your quick answer.
I was aware the sqlserver jdbc driver retrieves the name of the procedures appending a number. That's why I tried to overrode ROUTINES.sql for my tests with the following file:
```
          SELECT
            ROUTINE_CATALOG,
            ROUTINE_SCHEMA,
            ROUTINE_NAME+';1' AS ROUTINE_NAME,
            SPECIFIC_NAME+';1' AS SPECIFIC_NAME,
            ROUTINE_TYPE,
            ROUTINE_BODY,
            OBJECT_DEFINITION(OBJECT_ID(ROUTINE_CATALOG + '.' + ROUTINE_SCHEMA + '.' + ROUTINE_NAME))
            AS ROUTINE_DEFINITION,
            *
          FROM
            INFORMATION_SCHEMA.ROUTINES
```
(I suppose, now, sqlserver users do not use anymore the numbering because it is normally deprecated)
but it seems the lookup variable does not recognize the routine in [RoutineExtRetriever:91](https://github.com/schemacrawler/SchemaCrawler/blob/644bb26bfa99c6778caf60851d606234c1b527ba/schemacrawler-api/src/main/java/schemacrawler/crawl/RoutineExtRetriever.java#L91) (logs indicate schemacrawler executes the query) 
So which values are contained in the lookup variable ?
Especially, like I said previously, I tried using `catalog.lookupRoutine` without any success.

**Comment by darkattractions** [comment]
@sualeh - I fixed my problem - even if `routine.getSpecific()` returns the same value as `routine.getName()`, the key records the value `null` for specific name. By changing `ROUTINES.sql` with 
```
SELECT
            ROUTINE_CATALOG,
            ROUTINE_SCHEMA,
            ROUTINE_NAME+';1' AS ROUTINE_NAME,
            null AS SPECIFIC_NAME,
            ROUTINE_TYPE,
            ROUTINE_BODY,
            OBJECT_DEFINITION(OBJECT_ID(ROUTINE_CATALOG + '.' + ROUTINE_SCHEMA + '.' + ROUTINE_NAME))
            AS ROUTINE_DEFINITION,
            *
          FROM
            INFORMATION_SCHEMA.ROUTINES
```
I can get the definition of the procedure.
I let it here if someone come accross the same problem
