### ISSUE TITLE
Do schemacrawler.tools.linter.LinterTableCycles ignore schemacrawler.table.pattern.exclude|include ?

### ISSUE THREAD

**Issue by ThisGuenter** [schemacrawler/SchemaCrawler#496]
# Bug Report

**Issue**
I defined schemacrawler.table.pattern.include only schemacrawler.tools.linter.LinterTableCycles show me a table which violates the include, when defining a schemacrawler.table.pattern.exclude it works

**Environment**
schemacrawler-16.15.2
ojdbc8-19.7.0.0

**Comment by sualeh** [comment]
@ThisGuenter - please send me your schemacrawler.config.properties file, and your linter config file as well. I will try to reproduce the issue.

**Comment by ThisGuenter** [comment]
Without the "LOY_*|" in schemacrawler.table.pattern.exclude I get following output:

            cycles in table relationships   LMS_XX.LOY_ALIASES, LMS_XX.LOY_MEMBERSHIPS

All other linter show only tables that match the schemacrawler.table.pattern.include

Regards Günter



LP-Internal
Von: Sualeh Fatehi ***@***.***>
Gesendet: Donnerstag, 12. August 2021 00:22
An: schemacrawler/SchemaCrawler ***@***.***>
Cc: Guenter Leimbeck ***@***.***>; Mention ***@***.***>
Betreff: Re: [schemacrawler/SchemaCrawler] Do schemacrawler.tools.linter.LinterTableCycles ignore schemacrawler.table.pattern.exclude|include ? (#496)

CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe.


@ThisGuenter<https://deu01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FThisGuenter&data=04%7C01%7Cguenter.leimbeck%40payback.net%7C2da8d1ca90184bea3b1308d95d167004%7Cc89fef16c0d743f38b73bcde5402aa5b%7C0%7C0%7C637643173215711780%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Typ2YY66rFx%2FtND1qnA3SvRo%2Bt%2FCF0dVdLbBT%2BDvKuc%3D&reserved=0> - please send me your schemacrawler.config.properties file, and your linter config file as well. I will try to reproduce the issue.

-
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://deu01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fschemacrawler%2FSchemaCrawler%2Fissues%2F496%23issuecomment-897200476&data=04%7C01%7Cguenter.leimbeck%40payback.net%7C2da8d1ca90184bea3b1308d95d167004%7Cc89fef16c0d743f38b73bcde5402aa5b%7C0%7C0%7C637643173215721736%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=8fRDhGRP1bFauEMe2KNdXnNY6EOFkJxhvdkOKoJpMTI%3D&reserved=0>, or unsubscribe<https://deu01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAEMXIBKINJE3RMDCBAGZ4RTT4LZYNANCNFSM5B54DEIQ&data=04%7C01%7Cguenter.leimbeck%40payback.net%7C2da8d1ca90184bea3b1308d95d167004%7Cc89fef16c0d743f38b73bcde5402aa5b%7C0%7C0%7C637643173215721736%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=XyNT7V0neYlJdf21f%2FMhoNNZFOZeVusaJbl3GeV1UIo%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://deu01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cguenter.leimbeck%40payback.net%7C2da8d1ca90184bea3b1308d95d167004%7Cc89fef16c0d743f38b73bcde5402aa5b%7C0%7C0%7C637643173215721736%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=R%2BOEOUONHe5bMHIH%2BMn8efXQ%2BcS9DwLdVzuh5LI4RTA%3D&reserved=0> or Android<https://deu01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26utm_campaign%3Dnotification-email&data=04%7C01%7Cguenter.leimbeck%40payback.net%7C2da8d1ca90184bea3b1308d95d167004%7Cc89fef16c0d743f38b73bcde5402aa5b%7C0%7C0%7C637643173215731693%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=%2BTZeAO%2F41x8qQRLcCAtxa2guxYq%2B4s%2BJARrTI26ntiE%3D&reserved=0>.

**Comment by sualeh** [comment]
@ThisGuenter - please use SchemaCrawler 16.15.3.
