### ISSUE TITLE
SC API not honoring regex filters

### ISSUE THREAD

**Issue by jseaman-idata** [schemacrawler/SchemaCrawler#503]
# Bug Report

The API isn't respecting schema regex. I can create a scan using the command line utility with the exact same regex and it works correctly. 

**COMMAND LINE(works as expected.) :**
```sh
schemacrawler.cmd --user=xxxxxx --password=xxxxxx --info-level=maximum --command=schema --output-file=c:/temp/scout.html --output-format=html --url=jdbc:snowflake://xxxxxxx.us-east-1.snowflakecomputing.com/ --schemas=^SNOWFLAKE_SAMPLE_DATA\.TPCDS_SF100TCL -tables=^SNOWFLAKE_SAMPLE_DATA\.TPCDS_SF100TCL\..*
```

**API CALL(retuns tables from every schema in catalog):**
```java
String sil = "^SNOWFLAKE_SAMPLE_DATA\.TPCDS_SF100TCL";
Pattern schemaInclusionList = schemaList2Pattern(sil);
schemaExclusionList = schemaList2Pattern(getProperty("Schema Exclusion List", ""));
String tcl = "^SNOWFLAKE_SAMPLE_DATA\.TPCDS_SF100TCL\..*";
Pattern tableInclusionList = tableList2Pattern(tcl);
Pattern tableExclusionList = null;

schemaInfoLevel = SchemaInfoLevelBuilder.maximum();
final LimitOptionsBuilder limitOptionsBuilder =
				LimitOptionsBuilder.builder()
						.includeSchemas(new RegularExpressionRule(schemaInclusionList, schemaExclusionList));
		limitOptionsBuilder.includeTables(new RegularExpressionRule(tableInclusionList, tableExclusionList));

		final LoadOptionsBuilder loadOptionsBuilder =
				LoadOptionsBuilder.builder()
						// Set what details are required in the schema - this affects the
						// time taken to crawl the schema
						.withSchemaInfoLevel(SchemaInfoLevelBuilder.standard());
		final SchemaCrawlerOptions options =
				SchemaCrawlerOptionsBuilder.newSchemaCrawlerOptions()
						.withLimitOptions(limitOptionsBuilder.toOptions())
						.withLoadOptions(loadOptionsBuilder.toOptions());
...
               try (Connection conn = getConnection())    // ensure we close the Connection
		{
			final Catalog catalog = SchemaCrawlerUtility.getCatalog(conn, schemaCrawlerOptions);

...
```

Specify the
* version of SchemaCrawler that you are using
schemacrawler-16.15.4
* version of Java that you are using 
AdoptOpenJDK\jdk-11.0.9.11-hotspot
* operating system and version that you are using
Windows 10 Pro
* relational database and version that you are using
Snowflake (hosted in cloud sample db, version unknown)
* JDBC driver and version that you are using
snowflake-jdbc-3.13.6.jar

**Comment by jseaman-idata** [comment]
Sorry about the mult-attachment of the log and that it inserted it in the code. Hopefully that doesn't confuse things.

**Comment by sualeh** [comment]
@jseaman-idata - I cleaned up the code above. However, your code does not compile. I changed your code to:

```java
String sil = "^SNOWFLAKE_SAMPLE_DATA\\.TPCDS_SF100TCL";
Pattern schemaInclusionList = schemaList2Pattern(sil);
schemaExclusionList = schemaList2Pattern(getProperty("Schema Exclusion List", ""));
String tcl = "^SNOWFLAKE_SAMPLE_DATA\\.TPCDS_SF100TCL\\..*";
Pattern tableInclusionList = tableList2Pattern(tcl);
Pattern tableExclusionList = null;
```

Notice  the double backslashes. Then I created a [test which works](https://gist.github.com/sualeh/950a96308228613026029a58320e5bec). Please take a look at my test code.

Since the test is working, I will need to logs to investigate what is going on. Can you send me the two log files? Thanks.

**Comment by jseaman-idata** [comment]
Yeah, sorry that wasn't my actual code but an aproximation that got the idea across. I forgot about the double slashes. The logs I attached previously were incomplete. The buffer in the window is limited. I went to the log file and am now including the relevent section from that. 
I was only confused by the string escapes because I took the values from my log before calling SchemaCrawler. And the output was from the compiled pattern (java.util.regex.Pattern) output as a string and not the actual original string. 

DEBUG	08:48:33:160	Using Schema Patterns: ^SNOWFLAKE_SAMPLE_DATA\.TPCDS_SF100TCL
DEBUG	08:48:33:160	Excluding Schema Patterns: ^SNOWFLAKE_SAMPLE_DATA\.INFORMATION_SCHEMA
DEBUG	08:48:33:160	Using Table Patterns: ^SNOWFLAKE_SAMPLE_DATA\.TPCDS_SF100TCL\..*
DEBUG	08:48:33:160	Incoming Table Exclusion List =
DEBUG	08:48:33:160	Excluding Table Patterns: null

Here's the log (catalina log where your output goes, not the execution log of my code):
Hmmmm.... it's too big to attach so here's a link:
[https://phoenix.idatainc.com/~jseaman/catalina.2021-08-20.log](url)

**Comment by jseaman-idata** [comment]
Here's a relevant section from the SchemaCrawler logs in "INFO" mode. This shows the settings aren't being honored. 
21-Aug-2021 12:16:03.159 INFO [HubScheduler_Worker-3] schemacrawler.crawl.SchemaCrawler.crawl 
21-Aug-2021 12:16:03.159 INFO [HubScheduler_Worker-3] schemacrawler.crawl.RetrievalStopWatch.reset Running crawlSchemas
21-Aug-2021 12:16:03.174 INFO [HubScheduler_Worker-3] schemacrawler.crawl.RetrievalStopWatch.lambda$time$0 Running retrieveSchemas
21-Aug-2021 12:16:03.174 INFO [HubScheduler_Worker-3] schemacrawler.crawl.SchemaRetriever.retrieveAllSchemas Retrieving all schemas
21-Aug-2021 12:16:03.174 INFO [HubScheduler_Worker-3] schemacrawler.crawl.SchemaRetriever.retrieveAllCatalogs Retrieving all catalogs
21-Aug-2021 12:16:03.221 INFO [HubScheduler_Worker-3] schemacrawler.crawl.SchemaRetriever.retrieveAllCatalogs Processed 2 catalogs
21-Aug-2021 12:16:03.237 INFO [HubScheduler_Worker-3] schemacrawler.crawl.RetrievalStopWatch.lambda$time$0 Running filterAndSortSchemas
21-Aug-2021 12:16:03.237 INFO [HubScheduler_Worker-3] schemacrawler.crawl.RetrievalStopWatch.reset Running none
21-Aug-2021 12:16:03.237 INFO [HubScheduler_Worker-3] schemacrawler.crawl.RetrievalStopWatch.stopAndLogTime Total time taken for <none> - 00:00:00.000 hours

**Comment by jseaman-idata** [comment]
I tried doing a more explicit setup with the last bit to set up a print out of the configured options which I just set. The options I set aren't in the options object. Any idea what's going on?

log:
setSchemaCrawlerOptions: {"limitOptions":{"routineTypes":["procedure","function"],"tableNamePattern":null,"tableTypes":{"includeAll":false,"includeNone":false}},"filterOptions":{"childTableFilterDepth":0,"parentTableFilterDepth":0},"grepOptions":{"grepTableInclusionRule":{"empty":true,"present":false},"grepColumnInclusionRule":{"empty":true,"present":false},"grepDefinitionInclusionRule":{"empty":true,"present":false},"grepInvertMatch":false,"grepRoutineParameterInclusionRule":{"empty":true,"present":false},"grepRoutineParameters":false,"grepColumns":false,"grepTables":false,"grepDefinitions":false},"loadOptions":{"schemaInfoLevel":{"tag":""}}}

code:

	final LimitOptionsBuilder limitOptionsBuilder =
				LimitOptionsBuilder.builder()
						.includeSchemas(new RegularExpressionRule("some regex string", "some regex string"));
		limitOptionsBuilder.includeTables(new RegularExpressionRule("some regex string", "some regex string"));

		SchemaInfoLevelBuilder schemaInfoLevelBuilder = SchemaInfoLevelBuilder.builder()
			.setRetrieveRoutines(true)
			.setRetrieveAdditionalColumnAttributes(true)
			.setRetrieveAdditionalTableAttributes(true)
			.setRetrieveViewInformation(true)
			.setRetrieveViewInformation(true)
			.setRetrieveUserDefinedColumnDataTypes(true)
			.setRetrieveTables(true)
			.setRetrieveTableConstraintInformation(true)
			.setRetrieveTableConstraintDefinitions(true)
			.setRetrieveTableColumns(true)
			.setRetrieveRoutineParameters(true)
			.setRetrieveRoutineInformation(true)
			.setRetrievePrimaryKeys(true)
			.setRetrieveIndexInformation(true)
			.setRetrieveIndexes(true)
			.setRetrieveDatabaseInfo(true)
			.setRetrieveColumnDataTypes(true)
			.setRetrieveAdditionalColumnAttributes(true)
			.setRetrieveAdditionalColumnMetadata(true);

		final LoadOptionsBuilder loadOptionsBuilder =
				LoadOptionsBuilder.builder()
						.withSchemaInfoLevelBuilder(schemaInfoLevelBuilder);

		schemaCrawlerOptions =
				SchemaCrawlerOptionsBuilder.newSchemaCrawlerOptions()
						.withLimitOptions(limitOptionsBuilder.toOptions())
						.withLoadOptions(loadOptionsBuilder.toOptions());

		try{
			ObjectMapper objectMapper = new ObjectMapper();

			log.detail("setSchemaCrawlerOptions: " + objectMapper.writeValueAsString(schemaCrawlerOptions));
		}catch(JsonProcessingException jpe)	{
			log.error("problem converting JSON string from object: " + jpe.getMessage());
		}

**Comment by jseaman-idata** [comment]
I have to admit I really don't understand how the configuration objects work (the stored objects obviously have more in them than is displayed by the object mapper), but my latest changes listed above actually produced the correctly limited list by schema appropriately. Sorry for the trouble.

**Comment by sualeh** [comment]
@jseaman-idata - no worries. If you need to print out the configuration, I would suggest using Jackson instead of `ObjectMapper`.
