### ISSUE TITLE
Provide a way to skip retrieveJdbcDriverInfo or a way to pass in a custom classloader 

### ISSUE THREAD

**Issue by alwaysbemark** [schemacrawler/SchemaCrawler#504]
# Bug Report

Hello, like I've mentioned in previous discussions - SchemaCrawler is absolutely fantastic. Thank you so much for providing it freely. I know that I will be making a sizeable personal donation once I'm done with my project :).

**Issue**

I am trying to run crawl a schema using a connection that's established through a JDBC driver that's loaded dynamically - through a `URLClassLoader`. When the crawl tries to perform `DatabaseInfoRetriever::retrieveJdbcDriverInfo` I get an exception saying that `DriverManager` cannot find the driver, which makes sense, because I didn't register my loaded driver with the manager:

```
java.sql.SQLException: No suitable driver
	at java.sql/java.sql.DriverManager.getDriver(DriverManager.java:298) ~[java.sql:na]
```

Is it possible to either have the ability to disable this specific info retrieval (it looks like it's not a part of the `SchemaInfoRetrieval` enum) or alternatively, allow the user to pass in an instance of a `ClassLoader` to be used when trying to load the class? Thank you so much!

**Environment**

Latest version of SchemaCrawler.

**Comment by sualeh** [comment]
@alwaysbemark - thanks for the resounding appreciation.

You can use `SchemaInfoRetrieval::retrieveDatabaseInfo` to disable `DatabaseInfoRetriever::retrieveJdbcDriverInfo`, unless you are requesting more granular control in [SchemaCrawler::crawlDatabaseInfo](https://github.com/schemacrawler/SchemaCrawler/blob/master/schemacrawler-api/src/main/java/schemacrawler/crawl/SchemaCrawler.java#L215-L239).

**Comment by alwaysbemark** [comment]
Hi @sualeh , yup, I would like to disable it within crawlDatabaseInfo. Thank you!

**Comment by sualeh** [comment]
@alwaysbemark - please use SchemaCrawler v16.15.5. Use `SchemaInfoRetrieval.retrieveAdditionalJdbcDriverInfo` to control the retrieval of JDBC driver information. I have reorganized what gets retrieved, and no calls are made to `DriverManager` if `SchemaInfoRetrieval.retrieveAdditionalJdbcDriverInfo` is false.

**Comment by alwaysbemark** [comment]
Hey @sualeh ! Thank you so much for the quick reply!
I am still encountering a `DriverManager::getDriver` call within `SchemaCrawlerUtility::getCatalog` which results in a `java.sql.SQLException: No suitable driver` exception. Would it be possible to move this as well? It looks like the previous exception masked this one. Unrelated, I made a small donation to say thank you!

**Comment by sualeh** [comment]
Is this happening in the logging call? Would you be able to capture a stack trace?

**Comment by alwaysbemark** [comment]
Sure @sualeh ! , I'm calling `SchemaCrawlerUtility::getCatalog` to crawl the database and am getting this:

```
2021-09-12 23:09:00.535  INFO 74404 --- [0.1-8080-exec-1] s.tools.utility.SchemaCrawlerUtility     : Using database plugin for oracle - Oracle
2021-09-12 23:09:00.686  INFO 74404 --- [0.1-8080-exec-1] s.server.oracle.OracleDatabaseConnector  : Using Oracle data dictionary catalog scope <DBA>
2021-09-12 23:09:00.707  WARN 74404 --- [0.1-8080-exec-1] s.tools.utility.SchemaCrawlerUtility     : Could not log JDBC driver class name

java.sql.SQLException: No suitable driver
	at java.sql/java.sql.DriverManager.getDriver(DriverManager.java:298) ~[java.sql:na]
	at schemacrawler.tools.utility.SchemaCrawlerUtility.logConnection(SchemaCrawlerUtility.java:207) ~[schemacrawler-16.15.5.jar:na]
	at schemacrawler.tools.utility.SchemaCrawlerUtility.getCatalog(SchemaCrawlerUtility.java:101) ~[schemacrawler-16.15.5.jar:na]
```

Thanks again!

**Comment by sualeh** [comment]
@alwaysbemark  - this is strange - there is a catch block here - in [SchemaCrawlerUtility](https://github.com/schemacrawler/SchemaCrawler/blob/master/schemacrawler-tools/src/main/java/schemacrawler/tools/utility/SchemaCrawlerUtility.java#L205-L213).

**Comment by alwaysbemark** [comment]
Oh yeah, the exception doesn't bubble up or crash anything, I just wondered if there is a way to suppress it as not loading the driver via the DriverManager is a legitimate use case. No worries at all if not :)

**Comment by sualeh** [comment]
That is a warning message. I can simply suppress it, if you like.

**Comment by alwaysbemark** [comment]
That would work! Thank you so much!

**Comment by sualeh** [comment]
@alwaysbemark - please try SchemaCrawler v16.15.6.

**Comment by alwaysbemark** [comment]
Works beautifully @sualeh ! Thank you so much for the help with this. Much appreciated!
