### ISSUE TITLE
Release v16.15.2 removed from GitHub

### ISSUE THREAD

**Issue by glasser** [schemacrawler/SchemaCrawler#507]
We install SchemaCrawler in our CI process from GitHub releases. Today we noticed that v16.15.2 is no longer available, which broke our CI.

We upgraded, but are just wondering: is it a normal process to delete old releases from GitHub? Should we be doing something different to make sure our CI keeps working?

**Comment by sualeh** [comment]
I am so sorry! This was human error on my part. This was a one-off - I do not do this on a regular basis.

**Comment by glasser** [comment]
No worries — just good to know that we don't have to do anything differently :)
