### ISSUE TITLE
[Issue]: Graphviz path not being found on SchemaCrawler 16.16.3 docker image

### ISSUE THREAD

**Issue by EsterfanoLopes** [schemacrawler/SchemaCrawler#549]
### Description

Hello!

First, thanks for the awesome lib.

Well, I'm having a trouble while generating the graph that seems to use Graphviz. Searching for the problem on the internet i found that probably it isn't on the PATH variable. I've printed the PATH form pod and it seems to be accurate.

Are the image correct? Someone is having the same problem?

### How to Reproduce

The host and port are from the network configurations on postgres that i'm  running locally; user, password and database are omitted in here.

``` bash
docker run -v $PWD/src/main/resources/db/migration/docs:/share --net docker_default --rm -it schemacrawler/schemacrawler /opt/schemacrawler/schemacrawler.sh \
     --server=postgresql \
     --host=10.10.2.2 \
     --port=5432 \
     --user=<user> \
     --password=<password> \
     --database=<database> \
     --info-level=standard \
     --command=schema \
     --outputformat=png \
     --output-file /share/diagram.png
```

### Relevant log output

```
SchemaCrawler 16.16.3

Error: Graphviz was not available to create the requested diagram.
 
Please reinstall Graphviz, and make it available on the 
system PATH. If you are unable to install Graphviz, make
https://github.com/nidi3/graphviz-java jar files available
to SchemaCrawler, in the lib/ folder. Otherwise, consider 
generating a DOT file in scdot format.


Run SchemaCrawler again with just the
-h
option for help

Or, run SchemaCrawler again with an additional
--log-level=CONFIG
option for details on the error

Additional resources are on the SchemaCrawler website,
https://www.schemacrawler.com
and a live, interactive tutorial is on
https://katacoda.com/schemacrawler


Environment:
  SchemaCrawler 16.16.3
  Linux 5.11.0-43-generic
  Oracle Corporation OpenJDK 64-Bit Server VM 17-ea+14
  PostgreSQL 11.11
  PostgreSQL JDBC Driver 42.3.1

make: *** [Makefile:2: db/diagram] Error 1
```
```


### SchemaCrawler Version

16.16.3

### Java Version

Oracle Corporation OpenJDK 64-Bit Server VM 17-ea+14

### Operating System and Version

Linux 5.11.0-43-generic

### Relational Database System and Version

PostgreSQL 11.11

### JDBC Driver and Version

PostgreSQL JDBC Driver 42.3.1

**Comment by sualeh** [comment]
My guess is that Graphviz cannot write an output file since the Docker volumes may not be mounted right. I will try to reproduce. 

Meanwhile please see the readme file in the docker-compose folder of the project and follow those steps locally.

**Comment by EsterfanoLopes** [comment]
Just an addendum: On version `v16.15.7` it works just fine :+1:

**Comment by sualeh** [comment]
> Just an addendum: On version `v16.15.7` it works just fine 👍

Interesting. I will take a look. @EsterfanoLopes, meanwhile, please could you run it with `--log-level=CONFIG` and send me the logs?

**Comment by sualeh** [comment]
@EsterfanoLopes - I followed the instructions on [How to Visualize Your PostgreSQL Database with One Command (and Nothing to Install)](https://dev.to/sualeh/how-to-visualize-your-postgresql-database-with-one-command-and-nothing-to-install-3e3j) and was not able to reproduce the issue. The output diagram is created successfully.

Please try again with the following modifications to your Docker command:
```sh
docker run --mount type=bind,source="$(pwd)",target=/home/schcrwlr --net docker_default --rm -it schemacrawler/schemacrawler /opt/schemacrawler/schemacrawler.sh \
     --server=postgresql \
     --host=10.10.2.2 \
     --port=5432 \
     --user=<user> \
     --password=<password> \
     --database=<database> \
     --info-level=standard \
     --command=schema \
     --outputformat=png \
     --output-file diagram.png
```
Notice the changes to how the volume is mounted and the name of the output file without the path.

**Comment by sualeh** [comment]
@EsterfanoLopes - were you able to get this working?

**Comment by EsterfanoLopes** [comment]
> @EsterfanoLopes - were you able to get this working?

Yeah, I've made it work. In the end was nothing wrong with the version, but was something with the access (or how i was creating) the path that the image was being save. Probably something with the privilege of write from the user inside the pod.

Sorry for bothering you and thanks for the help.

**Comment by sualeh** [comment]
@EsterfanoLopes  - I am glad you got it to work. Thanks for letting me know.
