### ISSUE TITLE
[Issue]: NoClassDefFoundError when crawling an Oracle schema

### ISSUE THREAD

**Issue by alwaysbemark** [schemacrawler/SchemaCrawler#556]
### Description

When using SchemaCrawlerUtility#getCatalog to crawl an Oracle database, an exception is thrown:

```markdown
java.lang.NoClassDefFoundError: schemacrawler/testdb/SqlScript
	at schemacrawler.server.oracle.OracleCatalogLoader.loadCatalog(OracleCatalogLoader.java:55)
	at schemacrawler.tools.catalogloader.ChainedCatalogLoader.loadCatalog(ChainedCatalogLoader.java:76)
	at schemacrawler.tools.utility.SchemaCrawlerUtility.getCatalog(SchemaCrawlerUtility.java:101)
```

Thrown at this line: https://github.com/schemacrawler/SchemaCrawler/blob/master/schemacrawler-oracle/src/main/java/schemacrawler/server/oracle/OracleCatalogLoader.java#L55

Could it be a test class that leaked into the real implementation? We are including only     us.fatehi:schemacrawler-api and us.fatehi:schemacrawler-oracle. Thank you in advance!

### How to Reproduce

Call the above method to crawl any Oracle database.

### Relevant log output

```markdown
java.lang.NoClassDefFoundError: schemacrawler/testdb/SqlScript
	at schemacrawler.server.oracle.OracleCatalogLoader.loadCatalog(OracleCatalogLoader.java:55)
	at schemacrawler.tools.catalogloader.ChainedCatalogLoader.loadCatalog(ChainedCatalogLoader.java:76)
	at schemacrawler.tools.utility.SchemaCrawlerUtility.getCatalog(SchemaCrawlerUtility.java:101)
```

### SchemaCrawler Version

16.16.7

### Java Version

11

### Operating System and Version

Mac OSX

### Relational Database System and Version

Oracle 19

### JDBC Driver and Version

21.1.0.0

**Comment by sualeh** [comment]
@alwaysbemark - sorry! I will get that fixed. Meanwhile, please use an older version of SchemaCrawler.

**Comment by alwaysbemark** [comment]
All good, thanks for the prompt response!

**Comment by sualeh** [comment]
@alwaysbemark - Please use SchemaCrawler v16.16.8.

**Comment by alwaysbemark** [comment]
@sualeh Getting a new error now with 16.16.8:

```
Script: /schemacrawler-oracle.before.sql -- Could not commit with auto-commit set on
-- APPEND A SQL TERMINATOR TO EACH DDL STATEMENT
{call DBMS_METADATA.SET_TRANSFORM_PARAM(DBMS_METADATA.SESSION_TRANSFORM, 'SQLTERMINATOR', TRUE)}
2022-01-17 08:58:12,486 WARN  [http-nio-127.0.0.1-8080-exec-3] us.fatehi.utility.database.SqlScript: Script: /schemacrawler-oracle.before.sql -- Could not commit with auto-commit set on
```

This same DB used to work before. Has anything changed with the semantics of schema crawler? Do we need to change a specific setting?

```
Oracle Oracle Database 19c Standard Edition 2 Release 19.0.0.0.0 - Production
Version 19.12.0.0.0 
using JDBC driver 
Oracle JDBC driver 21.1.0.0.0
```

**Comment by sualeh** [comment]
Interesting - I am not seeing this error in my tests with Testcontainers, though I test with Oracle 18. Let me revert the changes back and see if that helps.

**Comment by alwaysbemark** [comment]
Specifically 16.16.6 works beautifully for us!

**Comment by sualeh** [comment]
I just noticed an Oracle 21 image out there, so let me try to use that as well, and see if I can fix the issue. Otherwise, I will revert to the 16.16.6 code.

**Comment by alwaysbemark** [comment]
Sounds like it could be an older JDBC driver as well being used in the test perhaps?
https://stackoverflow.com/questions/23953534/java-sql-sqlexception-could-not-commit-with-auto-commit-set-on-at-oracle-jdbc-d/57670792

**Comment by sualeh** [comment]
I doubt it, but I will double check.

**Comment by sualeh** [comment]
@alwaysbemark @holubec-petr - I think your issues have flushed out a couple of problems with the SchemaCrawler test framework 
1. There was an issue with the compilation class path that did not catch test classes used in code. I have fixed this issue with the Maven compilation classpath.
2. The test framework reset the default auto-commit setting, so it did not catch the issue you reported with the SchemaCrawler Oracle plugin. I have fixed this too, by using the default auto-commit setting on connections during tests.

**Comment by sualeh** [comment]
@alwaysbemark  - please see if SchemaCrawler 16.16.9 works for you. Sorry for the trouble.

**Comment by alwaysbemark** [comment]
Seems to work for us, thanks as always @sualeh !!!

**Comment by holubec-petr** [comment]
Works for me too @sualeh, thx.
