### ISSUE TITLE
Add schemacrawler to SDKMAN!

### ISSUE THREAD

**Issue by adriens** [schemacrawler/SchemaCrawler#563]
### Feature Request

> SDKMAN! is a tool for managing parallel versions of multiple Software Development Kits 

Among its SDK we can find java runtime as well as build tools and a lot of [JVM based CLIs](https://sdkman.io/sdks) like : 

- [ant](https://sdkman.io/sdks#ant)
- [hadoop](https://sdkman.io/sdks#hadoop)
- [jbang](https://sdkman.io/sdks#jbang)
- [jreleaser](https://sdkman.io/sdks#jreleaser)
- [kcctl](https://sdkman.io/sdks#kcctl)
- [maven](https://sdkman.io/sdks#maven)
- [visualvm](https://sdkman.io/sdks#visualvm)
- [tomcat](https://sdkman.io/sdks#tomcat)

It really makes install process a breeze. I even do use it on windows from git bash.

The main idea is that it would be really exciting to be able to install liquibase from SDKMAN. So the end user can manage multiple versions, get version upgraded as broadcasts, etc...

### Possible Alternatives

N/A

### Additional Context

# 🚀 Ressources

As you are the owner and maintainer I think that you would make sense if you were doing the publis by yourself if you find it convenient.

![image](https://user-images.githubusercontent.com/5235127/150084580-cc398ac0-e60a-4f8c-9be8-0aa5f3f47196.png)

Here is the [onboardning process
](https://github.com/sdkman/sdkman-cli/wiki/Vendor-onboarding-process).

Maybe will you have to provided a dedicated archive in your CI...by not modifying it too much 🤞

**Comment by adriens** [comment]
Same proposal done to https://github.com/liquibase/liquibase/issues/2381

**Comment by adriens** [comment]
🐦 https://twitter.com/rastadidi/status/1483705680473505793

**Comment by aalmiray** [comment]
Might be worth considering JReleaser for making this happen, alongside the existing Scoop and Chocolatey packages. Perhaps even Homebrew.

**Comment by sualeh** [comment]
https://github.com/users/schemacrawler/projects/1/views/1

**Comment by adriens** [comment]
![image](https://user-images.githubusercontent.com/5235127/150292584-a532c2d4-73a7-4c60-963f-65b0ff80faa1.png)

**Comment by adriens** [comment]
OH OH OH !!! Looks like great things are happening right now !
🎆 ❣️ 
https://twitter.com/SchemaCrawler/status/1486056774369169414

![image](https://user-images.githubusercontent.com/5235127/151059125-10fe3835-2a4a-42cc-b3c1-952bddbba6f2.png)

https://sdkman.io/sdks#schemacrawler

![image](https://user-images.githubusercontent.com/5235127/151059241-f9390c3f-b9b9-479c-a4eb-c2ab74ca2d79.png)

**Comment by adriens** [comment]
[LinkedIn Post](https://www.linkedin.com/posts/adrien-sales_sdk-installation-candidates-activity-6891850875300655104-BllM)

**Comment by adriens** [comment]
SC get properly listed in `sdk`

![image](https://user-images.githubusercontent.com/5235127/152256469-7966e4cb-8abd-4890-b5af-dd69e1a6691e.png)


but I got this while trying to istall it : 


![image](https://user-images.githubusercontent.com/5235127/152256407-71e0449d-082d-4a1f-8f45-c2d93ae998d3.png)

**Comment by sualeh** [comment]
I tried on Ubuntu (on WSL), and it worked. Try running `sdk update` first? After it gets installed, run it with `schemacrawler.sh`, not `schemacrawler`.

**Comment by adriens** [comment]
[Official Tweet](https://twitter.com/sdkman_/status/1488996113935962115)

**Comment by sualeh** [comment]
@aalmiray - what platforms does JReleaser run the sdkman packager? It seems to want to run on Windows and Ubuntu.

**Comment by adriens** [comment]
> I tried on Ubuntu (on WSL), and it worked. Try running `sdk update` first? After it gets installed, run it with `schemacrawler.sh`, not `schemacrawler`.

I did perform the update.

I'm giving a try with a new terminal (Under Git bash under Windows btw)

**Comment by adriens** [comment]
OH GOSH 🎆 

![image](https://user-images.githubusercontent.com/5235127/152256924-fa77dea5-9d3b-4028-a0e9-d7874e07ca6d.png)

**Comment by sualeh** [comment]
Nice!

**Comment by sualeh** [comment]
The shell script does not work in Git Bash, @adriens ☹️

**Comment by aalmiray** [comment]
@sualeh I'd recommend using the maven appassembler plugin to generate the launch scripts. Also check if Sdkman allows unix scripts with `.sh` as suffix

**Comment by aalmiray** [comment]
Just had a quick look at the code. The distribution is created using Ant scripts invoked from maven, the launcher scripts are simple and do not account for unix variants. I definitely recommend switching to appassembler for creating the distritbution and assembly for creating the zip, like it's done here https://github.com/aalmiray/app

**Comment by adriens** [comment]
Under windows Git bash :

```
$ schemacrawler
```

leads to : 

```
bash: /c/ProgramData/chocolatey/bin/schemacrawler: No such file or directory
```

while : 

`$ schemacrawler.bat --version`

leads to :

```
SchemaCrawler 16.16.10
```

@sualeh :maybe documen for Windows users as i'm afradi this could lead to issues beacuase of lack of understanding : what d you think about that ?

**Comment by aalmiray** [comment]
@adriens did you try with `schemacrawler.sh` on Git bash?

**Comment by adriens** [comment]
@aalmiray : 

![image](https://user-images.githubusercontent.com/5235127/152259395-b2e4edb1-85f8-4efc-9c56-360034c56c8c.png)


To summarize, on windows : 


- `schemacrawler.bat` : 👍 
- `schemacrawler.sh` : 👎 because of classpath

**Comment by adriens** [comment]
Makes me notice this too to make things look greater : https://github.com/schemacrawler/SchemaCrawler/issues/591 @sualeh

**Comment by adriens** [comment]
https://twitter.com/rastadidi/status/1489051022660358145

**Comment by adriens** [comment]
AWESOME 💟

**Comment by adriens** [comment]
While browsing home page and checking version badges (scoop, choco, maven) I had this idea : https://github.com/sdkman/sdkman-cli/issues/1045
