### ISSUE TITLE
[Issue]: latest Docker Image (16.16.10) does not work

### ISSUE THREAD

**Issue by pioneer2k** [schemacrawler/SchemaCrawler#568]
### Description

```markdown
We tried to use the latest Docker Image (16.16.10) but we get an error while running it

Status: Downloaded newer image for schemacrawler/schemacrawler:latest
docker: Error response from daemon: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "/opt/schemacrawler/schemacrawler.sh": stat /opt/schemacrawler/schemacrawler.sh: no such file or directory: unknown.
Error: Process completed with exit code 127.
```

### How to Reproduce

```markdown
run Docker Image version 16.16.10
```

### SchemaCrawler Version

16.16.10

### Java Version

?

### Operating System and Version

Ubuntu 20.04

### Relational Database System and Version

MySQL 8.0 (AWS Aurora)

### JDBC Driver and Version

8.0.23

**Comment by sualeh** [comment]
@pioneer2k - Thomas, in 16.16.10, the shell script is "/opt/schemacrawler/bin/schemacrawler.sh". It has been moved under a "bin/" folder to be consistent with convention for binary releases of software. Please could you try that? For more information, please look at the [SchemaCrawler Dockerfile](https://github.com/schemacrawler/SchemaCrawler/blob/master/schemacrawler-docker/Dockerfile).

**Comment by pioneer2k** [comment]
@sualeh yes, that works. Thank you for your help.
