### ISSUE TITLE
No social graph image on www.schemacrawler.com

### ISSUE THREAD

**Issue by adriens** [schemacrawler/SchemaCrawler#591]
### Description

Actullay, social graph preview is not implemented which leads to a non optimal experience on social medias... like on Twitter.

![image](https://user-images.githubusercontent.com/5235127/152260332-d9c46249-680d-4ebd-b1d3-76d5ae34a5f9.png)

### How to Reproduce

Put a reference to www.schemacrawler on twitter and see there is no preview.

### Relevant log output

```shell
N/A
```

### SchemaCrawler Version

N/A

### Java Version

N/A

### Operating System and Version

N/A

### Relational Database System and Version

N/A

### JDBC Driver and Version

N/A

**Comment by sualeh** [comment]
See [OpenGraph](https://www.opengraph.xyz/url/https%3A%2F%2Fwww.schemacrawler.com%2F/)
Recommended image size - 1200x630

**Comment by adriens** [comment]
👀

**Comment by sualeh** [comment]
@adriens - this is fixed now. Try here: https://cards-dev.twitter.com/validator

I debugged the issue. I had specified an SVG file for the logo, and none of the OpenGraph websites support that format. I had to specify a PNG image for it work.

**Comment by adriens** [comment]
![image](https://user-images.githubusercontent.com/5235127/152624796-abd06969-4555-45e1-a78c-580dfac3029b.png)
