### ISSUE TITLE
💡 Add #devops hashtag to choco release tweet

### ISSUE THREAD

**Issue by adriens** [schemacrawler/SchemaCrawler#597]
### Feature Request

for better indexation, I think it wold be interesting to add he `#devops` tag to the choco release tweet as for me it's a very important tool around database quality and comprehension that is automatable

![image](https://user-images.githubusercontent.com/5235127/152416228-f1638b95-746f-4920-a195-a634dec9ff1f.png)

**Comment by sualeh** [comment]
@adriens - this was a manually generated tweet. Tweets generated by JReleaser will have this tag.

**Comment by adriens** [comment]
[#devopstools](https://twitter.com/search?q=%23devopstools&src=typed_query) also is a trending one 😸

**Comment by sualeh** [comment]
Thanks. Added.

**Comment by adriens** [comment]
Done, check 🐦 https://twitter.com/SchemaCrawler/status/1490357117697597444 : 

![image](https://user-images.githubusercontent.com/5235127/152698388-a6f6b80c-1a4c-48eb-8b3b-d665d196d03f.png)
