### ISSUE TITLE
Time to candidate to Github Release Radar

### ISSUE THREAD

**Issue by adriens** [schemacrawler/SchemaCrawler#608]
### Feature Request

Drop a candidate to [GitHub Release Radar](https://github.blog/?s=release+radar)

### Possible Alternatives

N/A, this is probably one of the best opportunities to spread schemacrawler culture to the whole world 😸 

### Additional Context

Talked about that together earlier, but now with automated releases on choco and sdkman (through JReleaser) ..seems like the time has come ❣️ 

1. Go to [homepage](https://github.com/github/release-radar)
2. Fill the [dedicated issue](https://github.com/github/release-radar/issues/new?assignees=MishManners&labels=&template=release-radar-request.yml&title=%5BRelease+Radar+Request%5D+%3Ctitle%3E)
3. 🤞  and wait for SC to appear on the release radar 🤞 🍀

**Comment by sualeh** [comment]
https://github.com/github/release-radar/issues/76
