### ISSUE TITLE
InternalRuntimeException: SchemaCrawler database plugin should be on the CLASSPATH

### ISSUE THREAD

**Issue by prrvchr** [schemacrawler/SchemaCrawler#657]
### Description

Hi,
If I use schemacrawler-16.16.12.jar and schemacrawler-hsqldb-16.16.12.jar, with an HsqlDB connection I get this error (h2 is fine):
schemacrawler.schemacrawler.exceptions.InternalRuntimeException: SchemaCrawler database plugin should be on the CLASSPATH for <jdbc:hsqldb:~/testhsqldb;default_schema=true;hsqldb.default_table_type=cached;get_column_name=false;ifexists=false;shutdown=true>, or the SC_WITHOUT_DATABASE_PLUGIN environmental variable should be set

If I go back to schemacrawler-16.16.11.jar and schemacrawler-hsqldb-16.16.11.jar, everything is fine (hsqldb and h2).

### Relevant log output

```shell
schemacrawler.schemacrawler.exceptions.InternalRuntimeException: SchemaCrawler database plugin should be on the CLASSPATH for <jdbc:hsqldb:~/testhsqldb;default_schema=true;hsqldb.default_table_type=cached;get_column_name=false;ifexists=false;shutdown=true>, or the SC_WITHOUT_DATABASE_PLUGIN environmental variable should be set
schemacrawler.tools.utility.SchemaCrawlerUtility.useMatchedDatabasePlugin(SchemaCrawlerUtility.java:265)
schemacrawler.tools.utility.SchemaCrawlerUtility.buildSchemaRetrievalOptions(SchemaCrawlerUtility.java:159)
schemacrawler.tools.utility.SchemaCrawlerUtility.matchSchemaRetrievalOptions(SchemaCrawlerUtility.java:136)
io.github.prrvchr.hsqldbdriver.SchemaCrawler.getTables(SchemaCrawler.java:69)
io.github.prrvchr.uno.sdb.Connection.getTables(Connection.java:188)
io.github.prrvchr.uno.sdbcx.Driver.getDataDefinitionByConnection(Driver.java:115)
```

### SchemaCrawler Version

16.16.12

### Java Version

Private Build OpenJDK 64-Bit Server VM 17.0.1+12-Ubuntu-120.04

### Operating System and Version

Lubuntu 20.04

### Relational Database System and Version

HsqlDB 2.51

### JDBC Driver and Version

hsqldb-2.5.1.jar

**Comment by prrvchr** [comment]
Hi sualeh,

Thank you for this quick response...

I am sure that schemacrawler-hsqldb-16.16.12.jar is on my CLASSPATH (It's work when I use schemacrawler-hsqldb-16.16.11.jar).

But the driver hsqldb.jar is loaded at runtime (like h2.jar) using code similar to [this file](https://github.com/prrvchr/HsqlDBDriverOOo/blob/master/java/Driver/source/io/github/prrvchr/uno/sdbc/DriverBase.java#L172) and is not in the CLASSPATH to be able to load driver at connection time with the given connection properties "JavaDriverClassPath" who is the location of the driver. But maybe it matters between 16.16.11 and 16.16.12.

If I turn on SchemaCrawler logging to "ALL", I have 2 line before the Relevant log output:

`Mar 22, 2022 9:24:19 PM schemacrawler.tools.databaseconnector.DatabaseConnectorRegistry loadJdbcDrivers
CONFIG: Registered JDBC drivers:

Mar 22, 2022 9:24:19 PM schemacrawler.tools.utility.SchemaCrawlerUtility buildSchemaRetrievalOptions
INFO: Using database plugin for `

**Comment by sualeh** [comment]
@prrvchr - in 16.16.12, a check was added if "schemacrawler-hsqldb-16.16.12.jar" is not present on the CLASSPATH. Have you tried setting "SC_WITHOUT_DATABASE_PLUGIN" = "hsqldb" as either an environmental property or as a Java system property?

You should see a line similar to the one below in the logs. If you do not see this, that means that the plugin jar is not on your CLASSPATH.
```
Mar 22, 2022 7:09:24 PM schemacrawler.tools.utility.SchemaCrawlerUtility buildSchemaRetrievalOptions
INFO: Using database plugin for hsqldb - HyperSQL DataBase
```

I really cannot help you if you do not provide your code and the complete logs. Please provide these.

**Comment by sualeh** [comment]
@prrvchr - the main SchemaCrawler jar and "schemacrawler-hsqldb-16.16.12.jar" should be loaded by the same classloader.

**Comment by prrvchr** [comment]
I am using SchemaCrawler for an UNO LibreOffice / OpenOffice driver which comes in the form of an extension having a Driver.jar archive with a MANIFEST.MF containing: 
```
Manifest-Version: 1.0
RegistrationClassName: io.github.prrvchr.hsqldbdriver.RegistrationHandle
 r
Class-Path: lib/commons-io-2.9.0.jar lib/schemacrawler-16.16.11.jar lib/
 schemacrawler-hsqldb-16.16.11.jar
```
lib is a directory in the same location as the Driver.jar archive.
It's LibreOffice / OpenOffice which loads the JVM and the Driver.jar archive, and hopefully modifies the CLASSPATH...

**Comment by sualeh** [comment]
Please look for the log lines that I mentioned above. If you do not see them, that means the plugin is not loaded.

**Comment by prrvchr** [comment]
Hi sualeh,
You are correct, what prompted me to open this issue is the difference between 16.16.11 and 16.16.12 but you confirmed to me that version 12 checked the CLASSPATH while version 11 did not.
I will close this topic, but could you tell me where to find the CLASSPATH check for version 12 so that I can do more invertigation on my end.
I'm sorry for the inconvenience.

**Comment by sualeh** [comment]
@prrvchr - no worries. The CLASSPATH check happens in [SchemaCrawlerUtility](https://github.com/schemacrawler/SchemaCrawler/blob/master/schemacrawler-tools/src/main/java/schemacrawler/tools/utility/SchemaCrawlerUtility.java)
