### ISSUE TITLE
Loading services (plugins) with the caller's ClassLoader

### ISSUE THREAD

**Issue by prrvchr** [schemacrawler/SchemaCrawler#660]
### Feature Request

First of all congratulations and thank you for this excellent work.

Services or plugins seem to be loaded in two files:

- [DatabaseConnectorRegistry.java](https://github.com/schemacrawler/SchemaCrawler/blob/master/schemacrawler-tools/src/main/java/schemacrawler/tools/databaseconnector/DatabaseConnectorRegistry.java)
- [CatalogLoaderRegistry.java](https://github.com/schemacrawler/SchemaCrawler/blob/master/schemacrawler-tools/src/main/java/schemacrawler/tools/catalogloader/CatalogLoaderRegistry.java)

with the `ServiceLoader.load()` but without ClassLoader who is by default the current Thread's ClassLoader.

My application, a jar file that embeds the two SchemaCrawler archives (schemacrawler-16.16.11.jar and schemacrawler-hsqldb-16.16.11.jar), that wants to use SchemaCrawler is loaded by a URLClassLoader by LibreOffice which extend the CLASSPATH and which has as ClassLoader the current Thread's ClassLoader.

As a result, Services or Plugins can't never see the extended CLASSPATH from my application and never load...
Would it be possible to load the services with the ClassLoader of the caller `this.getClass().getClassLoader()` instead of that of the current Thread.
This will allow CLASSPATH inheritance through ClassLoaders... and this is the normal behaviour of `new Object()` or `Class.forName()`.

Thank you.

**Comment by sualeh** [comment]
@prrvchr - is this what you had in mind? See https://github.com/schemacrawler/SchemaCrawler/commit/3df1e3d10ad4eefbd7e7c9fcce4579e3930d626d

Would you be able to try it out? Are you able to build SchemaCrawler, or should I send you the jars?

**Comment by prrvchr** [comment]
Hi sualeh,

I prefer not to have to build it would take me too much time...
I have already tested with the following changes:

- [DatabaseConnectorRegistry.java](https://github.com/schemacrawler/SchemaCrawler/blob/master/schemacrawler-tools/src/main/java/schemacrawler/tools/databaseconnector/DatabaseConnectorRegistry.java)  

    line 76-77 and 119:
      ```
final ServiceLoader<DatabaseConnector> serviceLoader =
          ServiceLoader.load(DatabaseConnector.class);
```
      ```final ServiceLoader<Driver> serviceLoader = ServiceLoader.load(Driver.class);```

    have been changed to:
      ```
final ServiceLoader<DatabaseConnector> serviceLoader =
          ServiceLoader.load(DatabaseConnector.class, DatabaseConnectorRegistry.class.getClassLoader());
```
      ```final ServiceLoader<Driver> serviceLoader = ServiceLoader.load(Driver.class,  DatabaseConnectorRegistry.class.getClassLoader());```

- [CatalogLoaderRegistry.java](https://github.com/schemacrawler/SchemaCrawler/blob/master/schemacrawler-tools/src/main/java/schemacrawler/tools/catalogloader/CatalogLoaderRegistry.java)  

    line 87:
      ```final ServiceLoader<CatalogLoader> serviceLoader = ServiceLoader.load(CatalogLoader.class);```
 
    have been changed to:
      ```final ServiceLoader<CatalogLoader> serviceLoader = ServiceLoader.load(CatalogLoader.class, this.getClass().getClassLoader());```

Maybe there are other services used in SchemaCrawler whose ClassLoader to use for loading should be modified?

**Comment by sualeh** [comment]
@prrvchr - please try SchemaCrawler v16.16.14 and let me know how that works for you.

**Comment by prrvchr** [comment]
Hi sualeh,

It works perfectly, thank you for your reactivity and your welcome...
