### ISSUE TITLE
Improve LimitOptions by limiting the number of objects to retrieve

### ISSUE THREAD

**Issue by Trillyy** [schemacrawler/SchemaCrawler#674]
### Feature Request

The idea is simple, right now with LimitOptions (Schemacrawler Java API) you can only limit the crawling based on patterns and table types, it would be amazing to forcefully stop the crawling process after a certain number of table/schemas are successfully retrieved.
This an example call:

```
LimitOptions limitOptions =	LimitOptionsBuilder
                                .builder()
                                .topSchemas(10)               
				.includeSchemas(new RegularExpressionInclusionRule(SCHEMA INCLUSION PATTERN))
				.toOptions();
```

I hope I explained myself correctly.

### Additional Context

I really like this project, and if needed I can try implementing this feature myself, since I have some experience in Java. This would be my first contribution in an open-source project.

**Comment by sualeh** [comment]
@Trillyy - you can write this code very easily by implementing `InclusionRule` - something along the lines of the code below. I do not want to include it in the standard SchemaCrawler distribution since I am not sure that it would be generally useful.

```java
public class LimitInclusionRule implements InclusionRule {

  private int count;
  private final int limit;

  public LimitInclusionRule(final int limit) {
    this.limit = limit;
  }

  @Override
  public boolean test(final String t) {
    count = count + 1;
    return count <= limit;
  }
  
}
```

**Comment by sualeh** [comment]
```java
LimitOptions limitOptions =	LimitOptionsBuilder
                                .builder()             
				.includeSchemas(new LimitInclusionRule(10))
				.toOptions();
```
