### ISSUE TITLE
Katacoda is :skull:  (switch to killercoda url)

### ISSUE THREAD

**Issue by adriens** [schemacrawler/SchemaCrawler#781]
### Description

Katacoda is skull (switch to Go to https://killercoda.com/schemacrawler for up-to-date Schemacrawler course url)

![image](https://user-images.githubusercontent.com/5235127/177644651-83e01800-29c9-4bde-b193-552e400ee62f.png)

### How to Reproduce

Clikc on links on the README

### Relevant log output

```shell
Katacoda 404
```

### SchemaCrawler Version

N/A

### Java Version

N/A

### Operating System and Version

N/A

### Relational Database System and Version

N/A

### JDBC Driver and Version

N/A

**Comment by adriens** [comment]
also see https://github.com/schemacrawler/SchemaCrawler-Tutorials/issues/2

**Comment by sualeh** [comment]
Thanks, @adriens - this is fixed now.

**Comment by adriens** [comment]
:zap:
