### ISSUE TITLE
add additionalTableAttributes to `TableRetriever#retrieveTablesFromDataDictionary`

### ISSUE THREAD

**Issue by ltxlouis** [schemacrawler/SchemaCrawler#826]
### Feature Request

When using `retrieveTablesFromDataDictionary`, `schemacrawler.crawl.MetadataResultSet#getAttributes` are not set into table attributes.

If I want additional attributes, I would have to define another `ADDITIONAL_TABLE_ATTRIBUTES` query. In my case, I can use one query to get the table info together with some additional attributes saving one additional `ADDITIONAL_TABLE_ATTRIBUTES` query.

**Comment by sualeh** [comment]
@ltxlouis - that looks like an oversight. I will fix it.

**Comment by sualeh** [comment]
@ltxlouis please use SchemaCrawler v16.17.4, and let me know if that works for you.

**Comment by ltxlouis** [comment]
> @ltxlouis please use SchemaCrawler v16.17.4, and let me know if that works for you.

Yes, it works for me now. Thanks :D
