### ISSUE TITLE
I believe that recent release should be marked a breaking change

### ISSUE THREAD

**Issue by GavinRay97** [schemacrawler/SchemaCrawler#833]
### Description

I upgraded from Schemacrawler `16.17.1` to `16.17.4` and started getting errors when crawling a catalog that the plugin for the DB was not installed and I should install the plugin or set an ENV variable to ignore this.

This should constitute a breaking change I think if the behavior is enabled by default

### SchemaCrawler Version

16.17.4

### Java Version

17

### Operating System and Version

Windows 11

### Relational Database System and Version

All

### JDBC Driver and Version

All

**Comment by sualeh** [comment]
@GavinRay97 - this change was made in v16.16.12 and documented in the [release notes](https://www.schemacrawler.com/changes-report.html). (Probably not very clearly.) I am surprised that you did not encounter this issue in v16.17.1. I will have to find a better way to indicate breaking changes.

**Comment by GavinRay97** [comment]
Oh whoops, it is very strange that I didn't run into it then, maybe stale artifacts?
