### ISSUE TITLE
Error in Trino (AKA Presto): `NPE: Cannot invoke "schemacrawler.crawl.RetrievalTaskRunner.stopAndLogTime()" because "this.taskRunner" is null at schemacrawler.crawl.SchemaCrawler.crawl(SchemaCrawler.java:160)`

### ISSUE THREAD

**Issue by GavinRay97** [schemacrawler/SchemaCrawler#933]
### Description

I will attach a minimal reproduction which contains the Trino database in Docker and a Schemacrawler Maven project with the JDBC driver and code to try to inspect the schema.

But the issue is that the following code produces the below NPE exception:

```java
var connection = DriverManager.getConnection("jdbc:trino://localhost:8080/tpch/sf1?user=trino");

// Trino requires setting custom TypeMap and disabling index retrieval or it will error =(
var schemaRetrievalOptions = SchemaRetrievalOptionsBuilder.builder()
        .withTypeMap(new schemacrawler.utility.TypeMap())
        .toOptions();

var opts = SchemaCrawlerOptionsBuilder.newSchemaCrawlerOptions()
        .withLoadOptions(
                LoadOptionsBuilder.builder()
                        .withSchemaInfoLevelBuilder(
                                SchemaInfoLevelBuilder.builder().setRetrieveIndexes(false))
                        .toOptions()
        );


var dataSource = new DatabaseConnectionSource() {
    // ... snipped unused
    @Override
    public boolean releaseConnection(Connection connection) { return false; }
    @Override
    public Connection get() { return connection; }
};

Catalog catalog = SchemaCrawlerUtility.getCatalog(dataSource,
        schemaRetrievalOptions,
        opts,
        new Config());

for (var schema : catalog.getSchemas()) {
    System.out.println(schema.getFullName());
}
```

```java
/home/user/.sdkman/candidates/java/20.ea.15-open/bin/java
  -Dfile.encoding=UTF-8 -Dsun.stdout.encoding=UTF-8
  -Dsun.stderr.encoding=UTF-8
  -classpath
    /home/user/projects/schemacrawler-trino-repro/target/classes:
    /home/user/.m2/repository/io/trino/trino-jdbc/403/trino-jdbc-403.jar:
    /home/user/.m2/repository/us/fatehi/schemacrawler/16.19.1/schemacrawler-16.19.1.jar
org.example.Main

Exception in thread "main" java.lang.NullPointerException: Cannot invoke "schemacrawler.crawl.RetrievalTaskRunner.stopAndLogTime()" because "this.taskRunner" is null
	at schemacrawler.crawl.SchemaCrawler.crawl(SchemaCrawler.java:160)
	at schemacrawler.tools.catalogloader.SchemaCrawlerCatalogLoader.loadCatalog(SchemaCrawlerCatalogLoader.java:51)
	at schemacrawler.tools.catalogloader.ChainedCatalogLoader.loadCatalog(ChainedCatalogLoader.java:76)
	at schemacrawler.tools.utility.SchemaCrawlerUtility.getCatalog(SchemaCrawlerUtility.java:127)
	at org.example.Main.main(Main.java:51)
```

### How to Reproduce

Here is a zip file with `docker-compose.yaml` and the code above.
- [schemacrawler-trino-repro.zip](https://github.com/schemacrawler/SchemaCrawler/files/10078996/schemacrawler-trino-repro.zip)

1. Run `docker compose up` in one terminal to start the Trino DB on `localhost:8080`
2. Then run the program from IDE, where it should be able to connect to DB but fail due to some other error:

### SchemaCrawler Version

16.19.1

### Java Version

20

### Operating System and Version

Fedora 38

### Relational Database System and Version

Trino 403

### JDBC Driver and Version

Trino 403

**Comment by sualeh** [comment]
@GavinRay97 - I have fixed the problem, and will release a new version of SchemaCrawler soon. Why do you need a new TypeMap? Please take a look at the [Trino test](https://github.com/schemacrawler/SchemaCrawler/blob/master/schemacrawler-dbtest/src/test/java/schemacrawler/integration/test/TrinoTest.java#L83-L99) that I wrote - it works fine.

**Comment by sualeh** [comment]
@GavinRay97 - I have released SchemaCrawler 16.19.2. Please use this version. I have also released a new `schemacrawler-trino` jar so you do not have to use all of that additional code. 

```xml
<dependency>
    <groupId>us.fatehi</groupId>
    <artifactId>schemacrawler-trino</artifactId>
    <version>16.19.2</version>
</dependency>
```

**Comment by GavinRay97** [comment]
It works great, just tested today and integrated it into codebase, thank you!!

**Comment by sualeh** [comment]
Thanks for the confirmation, @GavinRay97 
Did you use the new Trino plugin?

**Comment by GavinRay97** [comment]
I did! Worked beautifully =)

**Comment by sualeh** [comment]
Glad to hear. Hopefully it made your code much simpler.
