### ISSUE TITLE
Deserialization - missing "java.net.*" allowed type

### ISSUE THREAD

**Issue by austalakov** [schemacrawler/SchemaCrawler#961]
### Description

I am using schemacrawler against DB2 with `jt400.jar` as the JDBC provider. This results in one of the system data types called `DATALINK` to be serialized as this in JSON:
![image](https://user-images.githubusercontent.com/32936040/207626911-d0a592b7-e0c7-449c-aa07-8c818460975e.png)
I am trying to deserialize the SER version of th same file, but it is hitting this error:
`Failed to parse schemacrawler file, caused by: Cannot deserialize catalog: Not deserializing class <java.net.URL>`

Tracking this down, it looks like it is because the `java.net.*` is missing from here.
https://github.com/schemacrawler/SchemaCrawler/blob/master/schemacrawler-scripting/src/main/java/schemacrawler/tools/formatter/serialize/CatalogModelInputStream.java#L50

Would it be possible to add that package?
And also, is there a workaround on the serialization side that would not require updating schemacrawler? 
Perhaps skipping the "system data types" section or just this specific data type? There are no actual columns using this type.

### Relevant log output

```shell
{"catalog" : {
    "@uuid" : "38dd1bea-d2e4-4ade-b2d3-36d6e5e4aa8e",
    "name" : "catalog",
    "full-name" : "catalog",
    "crawl-info" : {
      "@uuid" : "985015b6-d49c-411f-8122-8992199c7b7a",
      "crawl-timestamp" : "2022-12-14 13:25:42",
      "crawl-timestamp-instant" : 1671024342.961000000,
      "database-version" : {
        "@uuid" : "6ab83ebf-aa8f-417f-818e-abb954f5f160",
        "product-name" : "DB2 UDB for AS/400",
        "product-version" : "07.03.0000 V7R3m0"
      },
      "jdbc-driver-version" : {
        "@uuid" : "b79dd741-eee9-4785-a395-fb9b6da662f5",
        "product-name" : "AS/400 Toolbox for Java JDBC Driver",
        "product-version" : "12.7"
      },
      "jvm-version" : {
        "@uuid" : "ec13a3c0-a4ac-48db-9dc3-f7c834653170",
        "product-name" : "Oracle Corporation Java HotSpot(TM) 64-Bit Server VM",
        "product-version" : "1.8.0_341-b10"
      },
      "operating-system-version" : {
        "@uuid" : "50812109-a749-47f0-8784-0f6441652db7",
        "product-name" : "Windows Server 2019",
        "product-version" : "10.0"
      },
      "run-id" : "426f7701-8fad-48d4-ad16-8e51d31913c4",
      "schema-crawler-version" : {
        "@uuid" : "fd244ccb-0b23-4640-9adc-878a1e57c6a7",
        "product-name" : "SchemaCrawler",
        "product-version" : "16.16.18"
      }
    },
    "database-info" : {
      "@uuid" : "f1919ee4-fae9-4fcf-a7f6-63c07ef9324a",
      "database-product-name" : "DB2 UDB for AS/400",
      "database-product-version" : "07.03.0000 V7R3m0",
      "product-name" : "DB2 UDB for AS/400",
      "product-version" : "07.03.0000 V7R3m0",
      "properties" : [ ],
      "server-info" : [ ],
      "user-name" : "SVC_TDMTS2"
    },
    "jdbc-driver-info" : {
      "@uuid" : "7ae75990-55dc-4b49-92aa-3bf9b7f98539",
      "connection-url" : "***",
      "driver-class-name" : "",
      "driver-major-version" : 12,
      "driver-minor-version" : 7,
      "driver-name" : "AS/400 Toolbox for Java JDBC Driver",
      "driver-properties" : [ ],
      "driver-version" : "12.7",
      "jdbc-compliant" : false,
      "jdbc-major-version" : 4,
      "jdbc-minor-version" : 0,
      "product-name" : "AS/400 Toolbox for Java JDBC Driver",
      "product-version" : "12.7"
    }
}
}
```

### SchemaCrawler Version

16.16.18

### Java Version

1.8

### Operating System and Version

Windows Server 2019

### Relational Database System and Version

DB2 UDB for AS/400 07.03.0000 V7R3m0

### JDBC Driver and Version

AS/400 Toolbox for Java JDBC Driver 12.7

**Comment by sualeh** [comment]
@austalakov I will fix this in the next SchemaCrawler release, even though I cannot reproduce it.

> And also, is there a workaround on the serialization side that would not require updating schemacrawler?

The only workaround would be to write your own serialization logic using another serialization library like Apache Thrift or Google Protocol Buffers. SchemaCrawler default serialization leaves these choices up to individual developers, and does not introduce too many additional dependencies.

**Comment by austalakov** [comment]
Thank you. I'm going for a temporary hacky workaround of replacing `java.net.URL` with `java.sql.Ref` in the binary SER file (had to find a class that has the same number of characters for it to work). It's fine as a temporary solution on our end since there are no actual columns that use that data type, will update the schemacrawler version when it' out.
