### ISSUE TITLE
cant support Oracle 11g

### ISSUE THREAD

**Issue by zlj921020** [schemacrawler/SchemaCrawler#979]
### Description

SQL 错误 [904] [42000]: ORA-00904: "USERS"."ORACLE_MAINTAINED": 标识符无效

### How to Reproduce

cant support Oracle 11g

### Relevant log output

```shell
cant support Oracle 11g
```

### SchemaCrawler Version

16.19.5

### Java Version

8

### Operating System and Version

WIN 10

### Relational Database System and Version

11g

### JDBC Driver and Version

ojdbc8_g

**Comment by sualeh** [comment]
@zlj921020 SchemaCrawler dropped support for the Oracle 11g plgin starting from [v16.16.14](https://www.schemacrawler.com/changes-report.html). So you can use an older SchemaCrawler version, or use SchemaCrawler with the Oracle plugin.

To use SchemaCrawler without the plugin, you will need to delete (not rename) a jar called "schemacrawler-oracle*.jar" from the SchemaCrawler lib folder, and set an environmental variable called `SC_WITHOUT_DATABASE_PLUGIN` to "oracle".

**Comment by sualeh** [comment]
Here are some [consulting options](https://www.schemacrawler.com/consulting.html) if you want support for the Oracle 11g plugin.
