### ISSUE TITLE
Possible wrong Postgres query on ADDITIONAL_TABLE_ATTRIBUTES.sql

### ISSUE THREAD

**Issue by marciomed1** [schemacrawler/SchemaCrawler#998]
### Description

The query on [ADDITIONAL_TABLE_ATTRIBUTES](https://github.com/schemacrawler/SchemaCrawler/blob/main/schemacrawler-postgresql/src/main/resources/postgresql.information_schema/ADDITIONAL_TABLE_ATTRIBUTES.sql) seems to search for tables and it's schema, but the join between the tables and the schema is done by table's owner, which seems wrong.  
  
Original join:  
  
```
ON C.RELOWNER = NC.NSPOWNER
```
  
Join to fetch table's schema should be:  
```
ON c.relnamespace = nc.oid
```
  
The way the query is written returns way more rows than expected with a hundred of schemas of the same owner.  
We are comming here from another project, where this query is causing [too much execution delay](https://github.com/goldmansachs/obevo/issues/307).  
I'm not sure if the query should really return the schema of the table, or it's Obevo who's using it the wrong way.  

### SchemaCrawler Version

Latest

### Java Version

Latest

### Operating System and Version

Any

### Relational Database System and Version

Postgres

### JDBC Driver and Version

Any

**Comment by sualeh** [comment]
Thanks. I will take a look.

**Comment by sualeh** [comment]
@marciomed1 - this will be fixed in the next release of SchemaCrawler. Thanks for reporting it.
